[package]
name = "quire"
kind = "bin"
unsafe = false

[dependencies]
"array" = ""
"arith" = ""
"builder" = ""
"css" = ""
"file" = ""
"path" = ""
"promise" = ""
"pwa" = ""
"result" = ""
"str" = ""
"widget" = ""
"json" = ""
"sha256" = ""
"xml-tree" = ""
"zip" = ""
"wasm.bats-packages.dev/bridge" = ""
"wasm.bats-packages.dev/decompress" = ""
"wasm.bats-packages.dev/dom" = ""
"wasm.bats-packages.dev/file-input" = ""
"wasm.bats-packages.dev/idb" = ""
