[package]
name = "quire"
kind = "bin"
unsafe = false

[dependencies]
"array" = ""
"arith" = ""
"builder" = ""
"css" = ""
"file" = ""
"path" = ""
"promise" = ""
"pwa" = ""
"result" = ""
"str" = ""
"widget" = ""
"wasm.bats-packages.dev/bridge" = ""
"wasm.bats-packages.dev/dom" = ""
