// Books of pathological structure (#423), generated by code: nothing here
// is committed as a file. KOReader's notes on slow books name the shapes:
// a table cell holding many paragraphs that spans dozens of pages, a
// single-file book (the whole text in one spine item), converters that
// nest a thousand elements, and a chapter without breaks. Each book is a
// valid EPUB 3 (e2e/epubcheck.spec.js checks every entry of `pathologicalBooks`).
//
// Every chapter ends in a paragraph that holds a marker word found nowhere
// else (`TAIL_WORD`), so a test can search for a word on the last page and
// highlight near the end.

/** A word found only in the last paragraph of a chapter that has one */
export const TAIL_WORD = 'Zanzibarquartz';

/** A word found once, in the middle of the deepest nesting */
export const DEEP_WORD = 'Deepestmarker';

/** A word found once, in the middle of the paragraph without a space */
export const NEEDLE_WORD = 'Needlemarker';

const filler = 'lorem ipsum dolor sit amet '.repeat(12);

/** A paragraph that starts with a findable tag, as helpers.chapterBody's do */
const paragraph = (tag, n) => `<p>${tag} ${n} ${filler}</p>`;

/** The last paragraph: it holds TAIL_WORD */
const tailParagraph = (tag) => `<p>${tag} last ${TAIL_WORD} ends here.</p>`;

/** Chapters named in the contents, as createEpub does by default */
export const book = (title, rawChapters) => ({
  title, author: 'Pathological', rawChapters, storeChapters: false,
  toc: rawChapters.map((_, k) => ({ label: `Chapter ${k + 1}`, href: `chapter${k + 1}.xhtml` })),
});

/** A chapter of `count` ordinary paragraphs: the plain chapter a pathological
    one is measured against (same text, same length, no structure) */
export const plainChapter = (count, tag = 'Plain', tail = true) => ({
  body: `<h1>${tag} chapter</h1>` + Array.from({ length: count }, (_, k) => paragraph(tag, k)).join('') + (tail ? tailParagraph(tag) : ''),
});

/** A table whose one cell holds `count` paragraphs: one cell is one box
    that no page break may split by row, so every page across it is a
    slice of the same cell (KOReader's slow_check.pdf) */
export const tableChapter = (count, tag = 'Cell') => ({
  body: `<h1>${tag} chapter</h1><table><tbody><tr><td>` +
    Array.from({ length: count }, (_, k) => paragraph(tag, k)).join('') +
    `</td></tr></tbody></table>` + tailParagraph(tag),
});

/** `depth` nested elements, `inner` inside the deepest, `middle` at half depth */
export const nested = (element, depth, inner, middle = '') =>
  `<${element}>`.repeat(depth / 2) + middle + `<${element}>`.repeat(depth / 2) + inner + `</${element}>`.repeat(depth);

/** A chapter of 10,000 short paragraphs */
export const manyParagraphsChapter = (count, tag = 'Short') => ({
  body: `<h1>${tag} chapter</h1>` + Array.from({ length: count }, (_, k) => `<p>${tag} ${k}</p>`).join('') + tailParagraph(tag),
});

/** A chapter of one paragraph of `bytes` letters with no space, NEEDLE_WORD
    at its middle, between a heading and a closing paragraph. The letters
    cycle through the alphabet, so the paragraph is not one repeated cell. */
export const longParagraphChapter = (bytes, tag = 'Unbroken') => {
  const alphabet = 'abcdefghijklmnopqrstuvwxyz';
  const half = Math.floor((bytes - NEEDLE_WORD.length) / 2);
  const run = (n) => alphabet.repeat(Math.ceil(n / alphabet.length)).slice(0, n);
  return { body: `<h1>${tag} chapter</h1><p>${run(half)}${NEEDLE_WORD}${run(half)}</p>` + tailParagraph(tag) };
};

/** A single-file book of about `bytes` of text: one spine item, as a novel
    converted to one XHTML file is */
export const singleFileChapter = (bytes, tag = 'Novel') => {
  const per = paragraph(tag, 123456).length + 2;
  const count = Math.ceil(bytes / per);
  return { body: `<h1>${tag} chapter</h1>` + Array.from({ length: count }, (_, k) => paragraph(tag, k)).join('') + tailParagraph(tag) };
};

/** Sizes: a table cell of 200 paragraphs is 50 pages or more at the phone
    size; the others are the issue's */
export const CELL_PARAGRAPHS = 200;
export const NOVEL_BYTES = 5 * 1024 * 1024;
/** The yardstick: a chapter of the size page-turn.spec.js measures turns on */
export const NOVEL_SMALL_BYTES = 300 * 1024;
export const NEST_DEPTH = 1000;
export const SHORT_PARAGRAPHS = 10000;
export const UNBROKEN_BYTES = 1024 * 1024;

/** A plain chapter, then a table's, so a turn across the table is measured
    against a turn across text of the same length in the same page */
export const tableBook = () => book('Table Cell', [plainChapter(CELL_PARAGRAPHS), tableChapter(CELL_PARAGRAPHS)]);

/** One spine item of about 5 MB, then a short one */
export const novelBook = (bytes = NOVEL_BYTES) => book('Single File', [singleFileChapter(bytes), plainChapter(3, 'After', false)]);

/** 1000 nested divs, 1000 nested spans (inside one paragraph) and both
    mixed, each chapter holding its DEEP_WORD in the middle of the nesting */
export const nestedBook = () => book('Deep Nesting', [
  { body: `<h1>Divs chapter</h1>` + nested('div', NEST_DEPTH, `<p>Innermost ${DEEP_WORD} text.</p>`, '<p>Halfway down.</p>') + tailParagraph('Divs') },
  { body: `<h1>Spans chapter</h1><p>Before. ` + nested('span', NEST_DEPTH, `${DEEP_WORD} inside.`, 'Halfway. ') + ` After.</p>` + tailParagraph('Spans') },
  { body: `<h1>Mixed chapter</h1>` + nested('div', NEST_DEPTH / 2, `<p>Mixed ${nested('span', NEST_DEPTH / 2, `${DEEP_WORD} inside.`)} done.</p>`) + tailParagraph('Mixed') },
]);

/** 10,000 short paragraphs in one chapter */
export const shortParagraphsBook = () => book('Short Paragraphs', [manyParagraphsChapter(SHORT_PARAGRAPHS)]);

/** One paragraph of 1 MB without a space */
export const unbrokenBook = (bytes = UNBROKEN_BYTES) => book('Unbroken Paragraph', [longParagraphChapter(bytes)]);

/** The registry e2e/epubcheck.spec.js walks */
export const pathologicalBooks = {
  table: { valid: true, opts: tableBook() },
  novel: { valid: true, opts: novelBook() },
  nested: { valid: true, opts: nestedBook() },
  shortParagraphs: { valid: true, opts: shortParagraphsBook() },
  unbroken: { valid: true, opts: unbrokenBook() },
};
