# Generates src/<name>image.bats: a stored record as plain values (an image), the groups that differ
# between two images, and a record patched with the groups of an image.
# usage: python3 gen_image.py book | index
import sys, os
NAME = sys.argv[1]
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from record_tables import tables
GROUPS, KIND = tables(NAME)
P = NAME
C = NAME.capitalize()
fields = [f for g in GROUPS for f in g[2]]
ints = [n for n, k in fields if k == "i"]
strs = [n for n, k in fields if k == "s"]
o = []
w = o.append
w(f"(* {P}image -- a stored {P} as plain values: what differs between two, and a record patched with it.\n   Generated by scripts/gen-image.py {P} *)\n")
w("#target wasm begin\n")
w('#include "share/atspre_staload.hats"\n')
w("#use array as A\n#use arith as AR\n")
for m in ["bytes", "fields", "schema", "record", "bytesarr", f"{P}rec"]:
    w(f'staload "{m}.sats"')
w("")
quant_loc = ",".join(f"{n}_loc" for n in strs)
quant_len = ",".join(f"{n}_len" for n in strs)
decl = []
for n, k in fields:
    decl.append("Int" if k == "i" else f"$A.arr(byte, {n}_loc, {n}_len + 1), int {n}_len")
lencon = "; ".join(f"{n}_len < 256" for n in strs)
w(f"(* A stored {P} as values: numbers, and strings of up to 255 bytes in arrays one longer *)")
w(f"#pub datavtype {P}_image =\n  | {{{quant_loc}:agz}}{{{quant_len}:nat | {lencon}}}\n    {C}Image of ({', '.join(decl)})\n")
w("""fn _copy_array {l:agz}{n:nat | n < 256} (source: !$A.arr(byte, l, n + 1), len: int n): [m:agz] $A.arr(byte, m, n + 1) = let
  val copy = $A.alloc<byte>(len + 1)
  fun go {m:agz}{i:nat | i <= n} .<n - i>. (source: !$A.arr(byte, l, n + 1), copy: !$A.arr(byte, m, n + 1), i: int i): void =
    if i >= len then ()
    else let
      val () = $A.set<byte>(copy, i, $A.get<byte>(source, i))
    in go(source, copy, i + 1) end
  val () = go(source, copy, 0)
in copy end

fn _arrays_equal {l1,l2:agz}{n,m:nat | n < 256; m < 256}
  (a: !$A.arr(byte, l1, n + 1), a_len: int n, b: !$A.arr(byte, l2, m + 1), b_len: int m): bool = let
  fun go {i:nat | i <= n; n == m} .<n - i>. (a: !$A.arr(byte, l1, n + 1), b: !$A.arr(byte, l2, n + 1), len: int n, i: int i): bool =
    if i >= len then true
    else if byte2int0($A.get<byte>(a, i)) <> byte2int0($A.get<byte>(b, i)) then false
    else go(a, b, len, i + 1)
in
  if a_len = b_len then go(a, b, a_len, 0) else false
end
""")
numbers_fields = ", ".join(f"{n} = Int" for n in ints)
w(f"(* The numbers of a stored {P}, by name *)\n#pub typedef {P}_numbers = @{{{numbers_fields}}}\n")
strs_decl = ", ".join(f"{n}: $A.arr(byte, {n}_loc, {n}_len + 1), {n}_len: int {n}_len" for n in strs)
w(f"(* An image of numbers and strings (each in an array one longer than the string, which it takes) *)")
w(f"#pub fun {P}_image_make {{{quant_loc}:agz}}{{{quant_len}:nat | {lencon}}}\n  (numbers: {P}_numbers, {strs_decl}): {P}_image\n")
make_args = ", ".join(f"numbers.{n}" if k == "i" else f"{n}, {n}_len" for n, k in fields)
w(f"implement {P}_image_make (numbers, {', '.join(n + ', ' + n + '_len' for n in strs)}) = {C}Image({make_args})\n")
w(f"(* The numbers of an image *)\n#pub fun {P}_image_numbers (image: !{P}_image): {P}_numbers\n")
pat_all = ", ".join(n if k == "i" else f"_, _" for n, k in fields)
num_rec = ", ".join(f"{n} = {n}" for n in ints)
w(f"implement {P}_image_numbers (image) =\n  case+ image of\n  | {C}Image({pat_all}) => @{{{num_rec}}}\n")
w(f"(* A string of an image: its length, and a copy of its bytes in an array one longer *)")
for n in strs:
    w(f"#pub fun {P}_image_{n} (image: !{P}_image): [l:agz][len:nat | len < 256] @($A.arr(byte, l, len + 1), int len)\n")
    pat_one = ", ".join((f"{m}_loc, {m}_len" if m == n else "_, _") if kk == "s" else "_" for m, kk in fields)
    pat_one = ", ".join((f"s_array, s_len" if m == n else "_, _") if kk == "s" else "_" for m, kk in fields)
    w(f"implement {P}_image_{n} (image) =\n  case+ image of\n  | {C}Image({pat_one}) => let\n      val copy = _copy_array(s_array, s_len)\n    in @(copy, s_len) end\n")
# free
pat_args = ", ".join(f"~{n}" if False else (n if k == "i" else f"{n}, {n}_len") for n, k in fields)
w(f"#pub fun {P}_image_free (image: {P}_image): void\n")
w(f"implement {P}_image_free (image) =\n  case+ image of\n  | ~{C}Image({pat_args}) => let")
for n in strs:
    w(f"      val () = $A.free<byte>({n})")
w("    in () end\n")
# copy
w(f"#pub fun {P}_image_copy (image: !{P}_image): {P}_image\n")
w(f"implement {P}_image_copy (image) =\n  case+ image of\n  | {C}Image({pat_args}) => let")
for n in strs:
    w(f"      val copy_{n} = _copy_array({n}, {n}_len)")
args = ", ".join(n if k == "i" else f"copy_{n}, {n}_len" for n, k in fields)
w(f"    in {C}Image({args}) end\n")
# group bits
bits = {}
for gi, g in enumerate(GROUPS):
    bits[g[0]] = 1 << gi
for g in GROUPS:
    w(f"(* the bit of the group {g[0]} in a mask of groups *)\n#pub fn {P}_group_{g[0].lower()} (): int\n\nimplement {P}_group_{g[0].lower()} () = {bits[g[0]]}\n")
w(f"(* every group *)\n#pub fn {P}_group_all (): int\n\nimplement {P}_group_all () = {(1 << len(GROUPS)) - 1}\n")
# diff
def differs(g, a, b):
    parts = []
    for n, k in g[2]:
        if k == "i":
            parts.append(f"({a}_{n} <> {b}_{n})")
        else:
            parts.append(f"(~_arrays_equal({a}_{n}, {a}_{n}_len, {b}_{n}, {b}_{n}_len))")
    return " || ".join(parts)
def pat(prefix):
    return ", ".join(f"{prefix}_{n}" if k == "i" else f"{prefix}_{n}, {prefix}_{n}_len" for n, k in fields)
w(f"(* The groups whose fields differ in two images, as a mask *)\n#pub fun {P}_image_diff (first: !{P}_image, second: !{P}_image): int\n")
w(f"implement {P}_image_diff (first, second) =\n  case+ first of\n  | {C}Image({pat('a')}) =>\n    (case+ second of\n     | {C}Image({pat('b')}) => let")
for g in GROUPS:
    w(f"         val m_{g[0].lower()} = (if {differs(g,'a','b')} then {bits[g[0]]} else 0): int")
sumexpr = "0"
for g in GROUPS:
    sumexpr = f"$AR.add_int_int({sumexpr}, m_{g[0].lower()})"
w(f"       in {sumexpr} end)\n")
# of / to bookv
Pv = f"{P}v"
bargs = ", ".join(f"b_{n}" for n, _ in fields)
w(f"(* The image of a {P} *)\n#pub fun {P}_image_of {{x:{P}x}} ({P}: !{Pv}(x)): {P}_image\n")
w(f"implement {P}_image_of {{x}} ({P}) =\n  case+ {P} of\n  | {C[0]}{C[1:]}V({bargs}) => let".replace(f"{C[0]}{C[1:]}V(", f"{C}V("))
for n, k in fields:
    if k == "i":
        w(f"      val v_{n} = int32_value(b_{n})")
    else:
        w(f"      val (_ | len_{n}) = blist_len(b_{n})")
        w(f"      val v_{n} = blist_to_array(b_{n})")
iargs = ", ".join(f"v_{n}" if k == "i" else f"v_{n}, len_{n}" for n, k in fields)
w(f"    in {C}Image({iargs}) end\n")
w(f"(* The {P} an image holds *)\n#pub fun {P}_of_image (image: !{P}_image): [x:{P}x] {Pv}(x)\n")
w(f"implement {P}_of_image (image) =\n  case+ image of\n  | {C}Image({pat('a')}) => let")
for n, k in fields:
    if k == "i":
        w(f"      val n_{n} = int32_make(a_{n})")
    else:
        w(f"      val l_{n} = blist_of_array(a_{n}, 0, a_{n}_len)")
cargs = ", ".join(f"n_{n}" if k == "i" else f"l_{n}" for n, k in fields)
w(f"    in {C}V({cargs}) end\n")
# record level
Prec = f"{P}record"
w(f"(* The image of a stored {P}, as read *)\n#pub fun {P}_record_image {{x:{P}x}}{{ver,minver:int}}{{e:extras}} (record: !{Prec}(x, ver, minver, e)): {P}_image\n")
w(f"implement {P}_record_image {{x}}{{ver,minver}}{{e}} (record) =\n  case+ record of {C}Record(_, _, {P}, _) => {P}_image_of({P})\n")
w(f"(* A new record of an image: the format version this Quire writes, and no chunks kept *)\n#pub fun {P}_record_new (image: !{P}_image): [x:{P}x] {Prec}(x, 1, 1, ex_nil())\n")
w(f"implement {P}_record_new (image) = {C}Record(1, 1, {P}_of_image(image), EXV_nil())\n")
# free book
w(f"fn {P}_free_book {{x:{P}x}} ({P}: {Pv}(x)): void =\n  case+ {P} of\n  | ~{C}V({bargs.replace('b_', 'f_')}) => let")
for n, k in fields:
    w(f"      val () = {'int32_free' if k == 'i' else 'blist_free'}(f_{n})")
w("    in () end\n")
w(f"(* A record freed *)\n#pub fun {P}_record_free {{x:{P}x}}{{ver,minver:int}}{{e:extras}} (record: {Prec}(x, ver, minver, e)): void\n")
w(f"implement {P}_record_free {{x}}{{ver,minver}}{{e}} (record) =\n  case+ record of\n  | ~{C}Record(_, _, {P}, extras) => let\n      val () = {P}_free_book({P})\n    in extrasv_free(extras) end\n")
# select
w(f"""fn _choose {{l1,l2:agz}}{{n,m:nat | n < 256; m < 256}}
  (take: bool, base: $A.arr(byte, l1, n + 1), base_len: int n, update: !$A.arr(byte, l2, m + 1), update_len: int m)
  : [l:agz][k:nat | k < 256] @($A.arr(byte, l, k + 1), int k) =
  if take then let
    val () = $A.free<byte>(base)
    val copy = _copy_array(update, update_len)
  in @(copy, update_len) end
  else @(base, base_len)
""")
w(f"(* The record with the groups in the mask taken from the image, and the others as they are *)")
w(f"#pub fun {P}_record_patch {{x:{P}x}}{{ver,minver:int}}{{e:extras}} (record: {Prec}(x, ver, minver, e), image: !{P}_image, mask: int)\n  : [y:{P}x] {Prec}(y, ver, minver, e)\n")
w(f"implement {P}_record_patch {{x}}{{ver,minver}}{{e}} (record, image, mask) =\n  case+ record of\n  | ~{C}Record(ver, minver, {P}, extras) => let\n      val previous = {P}_image_of({P})\n      val () = {P}_free_book({P})\n    in\n      case+ previous of\n      | ~{C}Image({pat('a')}) =>\n        (case+ image of\n         | {C}Image({pat('b')}) => let")
for g in GROUPS:
    w(f"             val take_{g[0].lower()} = $AR.band_int_int(mask, {bits[g[0]]}) <> 0")
for g in GROUPS:
    for n, k in g[2]:
        if k == "i":
            w(f"             val c_{n} = (if take_{g[0].lower()} then b_{n} else a_{n}): Int")
        else:
            w(f"             val @(c_{n}, c_{n}_len) = _choose(take_{g[0].lower()}, a_{n}, a_{n}_len, b_{n}, b_{n}_len)")
cimg = ", ".join(f"c_{n}" if k == "i" else f"c_{n}, c_{n}_len" for n, k in fields)
w(f"             val changed = {C}Image({cimg})\n             val book = {P}_of_image(changed)\n             val () = {P}_image_free(changed)\n           in {C}Record(ver, minver, book, extras) end)\n    end\n")
w("end")
open(f"src/{P}image.bats", "w").write("\n".join(o) + "\n")
