# Generates src/<name>rec.bats: python3 gen_record.py book | index
import sys
NAME = sys.argv[1]
U = NAME.upper()
P = NAME
C = NAME.capitalize()
import os, sys as _s
_s.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from record_tables import tables
GROUPS, KIND = tables(NAME)
fields = [f for g in GROUPS for f in g[2]]

def bytes_lit(tag):
    out = "bnil()"
    for ch in reversed(tag):
        out = f"bcons({ord(ch)}, {out})"
    return out

def static_name(name):
    return name

o = []
w = o.append
w("(* @p@rec -- the library's @p@ record: its groups and fields, generated by scripts/gen-record.py *)\n")
w("#target wasm begin\n")
w('#include "share/atspre_staload.hats"\n')
for m in ["bytes","crc","chunk","seq","fields","schema","record"]:
    w(f'staload "{m}.sats"')
w("")
# datasort
params = ", ".join("int" if k == "i" else "bytes" for _, k in fields)
w(f"#pub datasort @p@x =\n  | @p@x_mk of ({params})\n")
# layouts and specs
def layout(g):
    s = "lo_nil()"
    for _, k in reversed(g[2]):
        s = f"lo_i32({s})" if k == "i" else f"lo_str({s})"
    return s
def default_vals(g):
    s = "fv_nil()"
    for _, k in reversed(g[2]):
        s = f"fv_i32(0, {s})" if k == "i" else f"fv_str(bnil(), {s})"
    return s
spec = "gs_nil()"
for g in reversed(GROUPS):
    spec = f"gs_cons({bytes_lit(g[0])}, {layout(g)}, m_{g[1]}(), {default_vals(g)}, {spec})"
w(f"#pub stadef @U@_SPECS = {spec}\n")
w(f"#pub stadef @U@_KIND = {KIND}\n")
# the spec at run time
def layoutv(g):
    s = "LYV_nil()"
    for _, k in reversed(g[2]):
        s = f"LYV_i32({s})" if k == "i" else f"LYV_str({s})"
    return s
def defaultv(g):
    s = "FVV_nil()"
    for _, k in reversed(g[2]):
        s = f"FVV_i32(int32_zero(), {s})" if k == "i" else f"FVV_str(blist_nil(), {s})"
    return s
def tagv(tag):
    s = "blist_nil()"
    for ch in reversed(tag):
        s = f"blist_cons({ord(ch)}, {s})"
    return s
runtime = "SPV_nil()"
for g in reversed(GROUPS):
    runtime = f"SPV_cons(TAGNOT_mk() | {tagv(g[0])}, {layoutv(g)}, Mode{g[1].capitalize()}(), {defaultv(g)}, {runtime})"
w(f"#pub fun @p@_specs (): specsv(@U@_SPECS, {len(GROUPS)})\n")
w(f"implement @p@_specs () = {runtime}\n")
# @U@V
def vals_term(group_fields_vals):
    pass
def group_vals_static(g):
    s = "fv_nil()"
    for name, k in reversed(g[2]):
        s = f"fv_i32({name}, {s})" if k == "i" else f"fv_str({name}, {s})"
    return s
gv = "gv_nil()"
for g in reversed(GROUPS):
    gv = f"gv_cons({group_vals_static(g)}, {gv})"
names = ", ".join(n for n, _ in fields)
quant_i = ",".join(n for n, k in fields if k == "i")
quant_s = ",".join(n for n, k in fields if k == "s")
w(f"(* @U@V(x, vals): the values of the groups are the fields of the @p@ x *)")
w(f"#pub dataprop @U@V(@p@x, gvals) =\n  | {{{quant_i}:int}}{{{quant_s}:bytes}}\n    @U@V_mk(@p@x_mk({names}), {gv})\n")
# runtime struct
decl = []
for name, k in fields:
    if k == "i":
        decl.append(f"int32v({name})")
    else:
        decl.append(f"blist({name}, {name}_len)")
quant_len = ",".join(n + "_len" for n, k in fields if k == "s")
quant_i_range = "{" + ",".join(n for n, k in fields if k == "i") + ":int}"
w(f"#pub datavtype @p@v(@p@x) =\n  | {quant_i_range}{{{quant_s}:bytes}}{{{quant_len}:nat | " + "; ".join(f"{n}_len < 256" for n, k in fields if k == "s") + f"}}\n    @C@V(@p@x_mk({names})) of ({', '.join(decl)})\n")
# to_vals
w("(* The record as the values of its groups, with the proof that they are its fields *)")
w(f"#pub fun @p@_to_vals {{x:@p@x}} (@p@: !@p@v(x)): [vals:gvals] (@U@V(x, vals) | gvalsv(@U@_SPECS, vals, {len(GROUPS)}))\n")
w("implement @p@_to_vals {x} (@p@) =\n  case+ @p@ of")
pat = ", ".join(n for n, _ in fields)
w(f"  | @C@V({pat}) => (@U@V_mk() | " )
def build(g):
    s = "FVV_nil()"
    for name, k in reversed(g[2]):
        s = f"FVV_i32(int32_copy({name}), {s})" if k == "i" else f"FVV_str(blist_copy({name}), {s})"
    return s
gvv = "GVV_nil()"
for g in reversed(GROUPS):
    gvv = f"GVV_cons({build(g)}, {gvv})"
w(f"    {gvv})\n")

# of_vals
w("(* The record made of the values of its groups, with the proof that they are its fields *)")
w(f"#pub fun @p@_of_vals {{vals:gvals}}{{kv:nat}} (vals: gvalsv(@U@_SPECS, vals, kv)): [x:@p@x] (@U@V(x, vals) | @p@v(x))\n")
def pat(g):
    s = "~FVV_nil()"
    for name, k in reversed(g[2]):
        s = f"~FVV_i32({name}, {s})" if k == "i" else f"~FVV_str({name}, {s})"
    return s
gpat = "~GVV_nil()"
for g in reversed(GROUPS):
    gpat = f"~GVV_cons({pat(g)}, {gpat})"
w("implement @p@_of_vals {vals}{kv} (vals) =")
w(f"  case+ vals of")
w("  | " + gpat + " => (@U@V_mk() | @C@V(" + ", ".join(n for n,_ in fields) + "))\n")

w("""
(* what reading a stored @p@ comes to *)
#pub datasort @p@res =
  | @ql@_ok of (@p@x, int, int, extras)
  | @ql@_loss of (@p@x, int, int, extras, lost)
  | @ql@_notquire of ()
  | @ql@_newer of ()
  | @ql@_damaged of ()

(* @U@ENC(x, ver, minver, e, bs): bs is the @p@ x, written in the format ver,
   readable from minver, with the chunks e kept *)
#pub dataprop @U@ENC(@p@x, int, int, extras, bytes) =
  | {x:@p@x}{ver,minver:int}{e:extras}{vals:gvals}{bs:bytes}
    @U@ENC_mk(x, ver, minver, e, bs) of (@U@V(x, vals), ENCODES(@U@_SPECS, @U@_KIND, rx_mk(ver, minver, vals, e), bs))

(* @U@DEC(bs, res): reading bs as a @p@ comes to res *)
#pub dataprop @U@DEC(bytes, @p@res) =
  | {x:@p@x}{ver,minver:int}{e:extras}{vals:gvals}{bs:bytes}
    @U@DEC_ok(bs, @ql@_ok(x, ver, minver, e)) of (@U@V(x, vals), DECODES(@U@_SPECS, @U@_KIND, bs, rr_ok(rx_mk(ver, minver, vals, e))))
  | {x:@p@x}{ver,minver:int}{e:extras}{t:lost}{vals:gvals}{bs:bytes}
    @U@DEC_loss(bs, @ql@_loss(x, ver, minver, e, t)) of (@U@V(x, vals), DECODES(@U@_SPECS, @U@_KIND, bs, rr_loss(rx_mk(ver, minver, vals, e), t)))
  | {bs:bytes} @U@DEC_notquire(bs, @ql@_notquire()) of DECODES(@U@_SPECS, @U@_KIND, bs, rr_notquire())
  | {bs:bytes} @U@DEC_newer(bs, @ql@_newer()) of DECODES(@U@_SPECS, @U@_KIND, bs, rr_newer())
  | {bs:bytes} @U@DEC_damaged(bs, @ql@_damaged()) of DECODES(@U@_SPECS, @U@_KIND, bs, rr_damaged())

(* @U@EQ(x, y): the @p@s are one *)
#pub dataprop @U@EQ(@p@x, @p@x) =
  | {x:@p@x} @U@EQ_refl(x, x)

(* A @p@ written and read back is the @p@ written, in the same format *)
#pub prfun @p@_roundtrip {x,y:@p@x}{ver,minver,ver2,minver2:int}{e,e2:extras}{bs:bytes}{n:nat}
  (LEN(bs, n), @U@ENC(x, ver, minver, e, bs), @U@DEC(bs, @ql@_ok(y, ver2, minver2, e2)))
  : (@U@EQ(x, y), EQI(ver, ver2), EQI(minver, minver2))

primplement @p@_roundtrip {x,y}{ver,minver,ver2,minver2}{e,e2}{bs}{n} (whole, written, read) =
  case+ written of
  | @U@ENC_mk(fields_written, encoded) =>
    (case+ read of
     | @U@DEC_ok(fields_read, decoded) => let
         prval EQRR_refl() = decodes_functional(whole, encodes_decodes(encoded), decoded)
         prval @U@V_mk() = fields_written
         prval @U@V_mk() = fields_read
       in (@U@EQ_refl(), EQI_refl(), EQI_refl()) end)

(* @U@RES(a, b): the results of reading are one *)
#pub dataprop @U@RES(@p@res, @p@res) =
  | {r:@p@res} @U@RES_refl(r, r)

(* Reading what a @p@ was written as is reading that @p@ *)
#pub prfun @p@_enc_dec {x:@p@x}{ver,minver:int}{e:extras}{bs:bytes}{n:nat}{res:@p@res}
  (LEN(bs, n), @U@ENC(x, ver, minver, e, bs), @U@DEC(bs, res)): @U@RES(res, @ql@_ok(x, ver, minver, e))

primplement @p@_enc_dec {x}{ver,minver}{e}{bs}{n}{res} (whole, written, read) =
  case+ written of
  | @U@ENC_mk(fields_written, encoded) =>
    (case+ read of
     | @U@DEC_ok(fields_read, decoded) => let
         prval EQRR_refl() = decodes_functional(whole, encodes_decodes(encoded), decoded)
         prval @U@V_mk() = fields_written
         prval @U@V_mk() = fields_read
       in @U@RES_refl() end
     | @U@DEC_loss(_, decoded) =>
       (case+ decodes_functional(whole, encodes_decodes(encoded), decoded) of EQRR_refl() =/=> ())
     | @U@DEC_notquire(decoded) =>
       (case+ decodes_functional(whole, encodes_decodes(encoded), decoded) of EQRR_refl() =/=> ())
     | @U@DEC_newer(decoded) =>
       (case+ decodes_functional(whole, encodes_decodes(encoded), decoded) of EQRR_refl() =/=> ())
     | @U@DEC_damaged(decoded) =>
       (case+ decodes_functional(whole, encodes_decodes(encoded), decoded) of EQRR_refl() =/=> ()))

(* a @p@ record at run time: its format version, the least version that reads it, the @p@,
   and the chunks kept *)
#pub datavtype @p@record(@p@x, int, int, extras) =
  | {x:@p@x}{ver,minver:int | 0 <= ver; ver < 256; 0 <= minver; minver <= READER}{e:extras}{ke:nat}
    @C@Record(x, ver, minver, e) of (int ver, int minver, @p@v(x), extrasv(e, ke))

#pub datavtype @p@read(@p@res) =
  | {x:@p@x}{ver,minver:int}{e:extras} @QU@_ok(@ql@_ok(x, ver, minver, e)) of @p@record(x, ver, minver, e)
  | {x:@p@x}{ver,minver:int}{e:extras}{t:lost}{kl:nat} @QU@_loss(@ql@_loss(x, ver, minver, e, t)) of (@p@record(x, ver, minver, e), lostv(t, kl))
  | @QU@_notquire(@ql@_notquire())
  | @QU@_newer(@ql@_newer())
  | @QU@_damaged(@ql@_damaged())

#pub fun @p@_record_write {x:@p@x}{ver,minver:int}{e:extras} (record: !@p@record(x, ver, minver, e))
  : [bs:bytes][m:nat] (@U@ENC(x, ver, minver, e, bs) | blist(bs, m))

implement @p@_record_write {x}{ver,minver}{e} (record) =
  case+ record of
  | @C@Record(ver, minver, @p@, extras) => let
      val specs = @p@_specs()
      val (fields | vals) = @p@_to_vals(@p@)
      val (written | out) = record_write(specs, @K@, ver, minver, vals, extras)
      val () = gvalsv_free(vals)
      val () = specsv_free(specs)
    in (@U@ENC_mk(fields, written) | out) end

#pub fun @p@_record_read {bs:bytes}{n:nat} (list: blist(bs, n)): [res:@p@res] (@U@DEC(bs, res) | @p@read(res))

implement @p@_record_read {bs}{n} (list) = let
  val specs = @p@_specs()
  val (read | out) = record_read(specs, @K@, list)
  val () = specsv_free(specs)
in
  case+ out of
  | ~RR_ok(ver, minver, vals, extras) => let
      val (fields | @p@) = @p@_of_vals(vals)
    in (@U@DEC_ok(fields, read) | @QU@_ok(@C@Record(ver, minver, @p@, extras))) end
  | ~RR_loss(ver, minver, vals, extras, lost) => let
      val (fields | @p@) = @p@_of_vals(vals)
    in (@U@DEC_loss(fields, read) | @QU@_loss(@C@Record(ver, minver, @p@, extras), lost)) end
  | ~RR_notquire() => (@U@DEC_notquire(read) | @QU@_notquire())
  | ~RR_newer() => (@U@DEC_newer(read) | @QU@_newer())
  | ~RR_damaged() => (@U@DEC_damaged(read) | @QU@_damaged())
end

(* A result of reading as another it is the same as *)
#pub fun @p@_read_recast {first,second:@p@res} (same: @U@RES(first, second) | read: @p@read(first)): @p@read(second)

implement @p@_read_recast {first,second} (same | read) = let
  prval @U@RES_refl() = same
in read end

(* A decoding as the decoding it is the same as *)
#pub prfun @p@_dec_recast {bs:bytes}{first,second:@p@res} (@U@RES(first, second), @U@DEC(bs, first)): @U@DEC(bs, second)

primplement @p@_dec_recast {bs}{first,second} (same, dec) = let
  prval @U@RES_refl() = same
in dec end
""")
w("end")
text = "\n".join(o) + "\n"
QU = "BR" if NAME == "book" else "IR"
text = text.replace("@QU@", QU).replace("@ql@", QU.lower()).replace("@K@", str(KIND)).replace("@U@", U).replace("@C@", C).replace("@p@", P)
open(f"src/{P}rec.bats", "w").write(text)
