# Generates src/<name>rec.bats: python3 gen_record.py book | index
import sys
import os
NAME = sys.argv[1]
UPPER = NAME.upper()
PREFIX = NAME
CAPITAL = NAME.capitalize()
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from record_tables import tables
GROUPS, KIND = tables(NAME)
fields = [field for group in GROUPS for field in group[2]]


def bytes_lit(tag):
    result = "bnil()"
    for letter in reversed(tag):
        result = f"bcons({ord(letter)}, {result})"
    return result


lines = []
emit = lines.append
emit("(* @p@rec -- the library's @p@ record: its groups and fields, generated by scripts/gen-record.py *)\n")
emit("#target wasm begin\n")
emit('#include "share/atspre_staload.hats"\n')
for module in ["bytes", "crc", "chunk", "seq", "fields", "schema", "record"]:
    emit(f'staload "{module}.sats"')
emit("")
# datasort
params = ", ".join("int" if kind == "i" else "bytes" for _, kind in fields)
emit(f"#pub datasort @p@x =\n  | @p@x_mk of ({params})\n")


# layouts and specs
def layout(group):
    result = "lo_nil()"
    for _, kind in reversed(group[2]):
        result = f"lo_i32({result})" if kind == "i" else f"lo_str({result})"
    return result


def default_vals(group):
    result = "fv_nil()"
    for _, kind in reversed(group[2]):
        result = f"fv_i32(0, {result})" if kind == "i" else f"fv_str(bnil(), {result})"
    return result


spec = "gs_nil()"
for group in reversed(GROUPS):
    spec = f"gs_cons({bytes_lit(group[0])}, {layout(group)}, m_{group[1]}(), {default_vals(group)}, {spec})"
emit(f"#pub stadef @U@_SPECS = {spec}\n")
emit(f"#pub stadef @U@_KIND = {KIND}\n")


# the spec at run time
def layoutv(group):
    result = "LYV_nil()"
    for _, kind in reversed(group[2]):
        result = f"LYV_i32({result})" if kind == "i" else f"LYV_str({result})"
    return result


def defaultv(group):
    result = "FVV_nil()"
    for _, kind in reversed(group[2]):
        result = f"FVV_i32(int32_zero(), {result})" if kind == "i" else f"FVV_str(blist_nil(), {result})"
    return result


def tagv(tag):
    result = "blist_nil()"
    for letter in reversed(tag):
        result = f"blist_cons({ord(letter)}, {result})"
    return result


runtime = "SPV_nil()"
for group in reversed(GROUPS):
    runtime = f"SPV_cons(TAGNOT_mk() | {tagv(group[0])}, {layoutv(group)}, Mode{group[1].capitalize()}(), {defaultv(group)}, {runtime})"
emit(f"#pub fun @p@_specs (): specsv(@U@_SPECS, {len(GROUPS)})\n")
emit(f"implement @p@_specs () = {runtime}\n")


# @U@V
def group_vals_static(group):
    result = "fv_nil()"
    for name, kind in reversed(group[2]):
        result = f"fv_i32({name}, {result})" if kind == "i" else f"fv_str({name}, {result})"
    return result


group_values = "gv_nil()"
for group in reversed(GROUPS):
    group_values = f"gv_cons({group_vals_static(group)}, {group_values})"
names = ", ".join(name for name, _ in fields)
quant_i = ",".join(name for name, kind in fields if kind == "i")
quant_s = ",".join(name for name, kind in fields if kind == "s")
emit(f"(* @U@V(@p@_value, vals): the values of the groups are the fields of the @p@ @p@_value *)")
emit(f"#pub dataprop @U@V(@p@x, gvals) =\n  | {{{quant_i}:int}}{{{quant_s}:bytes}}\n    @U@V_mk(@p@x_mk({names}), {group_values})\n")
# runtime struct
declared = []
for name, kind in fields:
    if kind == "i":
        declared.append(f"int32v({name})")
    else:
        declared.append(f"blist({name}, {name}_len)")
quant_len = ",".join(name + "_len" for name, kind in fields if kind == "s")
quant_i_range = "{" + ",".join(name for name, kind in fields if kind == "i") + ":int}"
emit(f"#pub datavtype @p@v(@p@x) =\n  | {quant_i_range}{{{quant_s}:bytes}}{{{quant_len}:nat | " + "; ".join(f"{name}_len < 256" for name, kind in fields if kind == "s") + f"}}\n    @C@V(@p@x_mk({names})) of ({', '.join(declared)})\n")
# to_vals
emit("(* The record as the values of its groups, with the proof that they are its fields *)")
emit(f"#pub fun @p@_to_vals {{@p@_value:@p@x}} (@p@: !@p@v(@p@_value)): [vals:gvals] (@U@V(@p@_value, vals) | gvalsv(@U@_SPECS, vals, {len(GROUPS)}))\n")
emit("implement @p@_to_vals {@p@_value} (@p@) =\n  case+ @p@ of")
emit(f"  | @C@V({names}) => (@U@V_mk() | ")


def build(group):
    result = "FVV_nil()"
    for name, kind in reversed(group[2]):
        result = f"FVV_i32(int32_copy({name}), {result})" if kind == "i" else f"FVV_str(blist_copy({name}), {result})"
    return result


values_built = "GVV_nil()"
for group in reversed(GROUPS):
    values_built = f"GVV_cons({build(group)}, {values_built})"
emit(f"    {values_built})\n")

# of_vals
emit("(* The record made of the values of its groups, with the proof that they are its fields *)")
emit(f"#pub fun @p@_of_vals {{vals:gvals}}{{value_count:nat}} (vals: gvalsv(@U@_SPECS, vals, value_count)): [@p@_value:@p@x] (@U@V(@p@_value, vals) | @p@v(@p@_value))\n")


def group_pattern(group):
    result = "~FVV_nil()"
    for name, kind in reversed(group[2]):
        result = f"~FVV_i32({name}, {result})" if kind == "i" else f"~FVV_str({name}, {result})"
    return result


values_pattern = "~GVV_nil()"
for group in reversed(GROUPS):
    values_pattern = f"~GVV_cons({group_pattern(group)}, {values_pattern})"
emit("implement @p@_of_vals {vals}{value_count} (vals) =")
emit(f"  case+ vals of")
emit("  | " + values_pattern + " => (@U@V_mk() | @C@V(" + names + "))\n")

emit("""
(* what reading a stored @p@ comes to *)
#pub datasort @p@res =
  | @ql@_ok of (@p@x, int, int, extras)
  | @ql@_loss of (@p@x, int, int, extras, lost)
  | @ql@_notquire of ()
  | @ql@_newer of ()
  | @ql@_damaged of ()

(* @U@ENC(@p@_value, format_version, least_version, kept_extras, octets): octets is the @p@ @p@_value, written in
   the format format_version, readable from least_version, with the chunks kept_extras kept *)
#pub dataprop @U@ENC(@p@x, int, int, extras, bytes) =
  | {@p@_value:@p@x}{format_version,least_version:int}{kept_extras:extras}{vals:gvals}{octets:bytes}
    @U@ENC_mk(@p@_value, format_version, least_version, kept_extras, octets) of (@U@V(@p@_value, vals), ENCODES(@U@_SPECS, @U@_KIND, rx_mk(format_version, least_version, vals, kept_extras), octets))

(* @U@DEC(octets, outcome): reading octets as a @p@ comes to outcome *)
#pub dataprop @U@DEC(bytes, @p@res) =
  | {@p@_value:@p@x}{format_version,least_version:int}{kept_extras:extras}{vals:gvals}{octets:bytes}
    @U@DEC_ok(octets, @ql@_ok(@p@_value, format_version, least_version, kept_extras)) of (@U@V(@p@_value, vals), DECODES(@U@_SPECS, @U@_KIND, octets, rr_ok(rx_mk(format_version, least_version, vals, kept_extras))))
  | {@p@_value:@p@x}{format_version,least_version:int}{kept_extras:extras}{lost_groups:lost}{vals:gvals}{octets:bytes}
    @U@DEC_loss(octets, @ql@_loss(@p@_value, format_version, least_version, kept_extras, lost_groups)) of (@U@V(@p@_value, vals), DECODES(@U@_SPECS, @U@_KIND, octets, rr_loss(rx_mk(format_version, least_version, vals, kept_extras), lost_groups)))
  | {octets:bytes} @U@DEC_notquire(octets, @ql@_notquire()) of DECODES(@U@_SPECS, @U@_KIND, octets, rr_notquire())
  | {octets:bytes} @U@DEC_newer(octets, @ql@_newer()) of DECODES(@U@_SPECS, @U@_KIND, octets, rr_newer())
  | {octets:bytes} @U@DEC_damaged(octets, @ql@_damaged()) of DECODES(@U@_SPECS, @U@_KIND, octets, rr_damaged())

(* @U@EQ(written_value, read_value): the @p@s are one *)
#pub dataprop @U@EQ(@p@x, @p@x) =
  | {@p@_value:@p@x} @U@EQ_refl(@p@_value, @p@_value)

(* A @p@ written and read back is the @p@ written, in the same format *)
#pub prfun @p@_roundtrip {written_value,read_value:@p@x}{format_version,least_version,read_format_version,read_least_version:int}{kept_extras,read_extras:extras}{octets:bytes}{byte_count:nat}
  (LEN(octets, byte_count), @U@ENC(written_value, format_version, least_version, kept_extras, octets), @U@DEC(octets, @ql@_ok(read_value, read_format_version, read_least_version, read_extras)))
  : (@U@EQ(written_value, read_value), EQI(format_version, read_format_version), EQI(least_version, read_least_version))

primplement @p@_roundtrip {written_value,read_value}{format_version,least_version,read_format_version,read_least_version}{kept_extras,read_extras}{octets}{byte_count} (whole, written, read) =
  case+ written of
  | @U@ENC_mk(fields_written, encoded) =>
    (case+ read of
     | @U@DEC_ok(fields_read, decoded) => let
         prval EQRR_refl() = decodes_functional(whole, encodes_decodes(encoded), decoded)
         prval @U@V_mk() = fields_written
         prval @U@V_mk() = fields_read
       in (@U@EQ_refl(), EQI_refl(), EQI_refl()) end)

(* @U@RES(first, second): the results of reading are one *)
#pub dataprop @U@RES(@p@res, @p@res) =
  | {outcome:@p@res} @U@RES_refl(outcome, outcome)

(* Reading what a @p@ was written as is reading that @p@ *)
#pub prfun @p@_enc_dec {@p@_value:@p@x}{format_version,least_version:int}{kept_extras:extras}{octets:bytes}{byte_count:nat}{outcome:@p@res}
  (LEN(octets, byte_count), @U@ENC(@p@_value, format_version, least_version, kept_extras, octets), @U@DEC(octets, outcome)): @U@RES(outcome, @ql@_ok(@p@_value, format_version, least_version, kept_extras))

primplement @p@_enc_dec {@p@_value}{format_version,least_version}{kept_extras}{octets}{byte_count}{outcome} (whole, written, read) =
  case+ written of
  | @U@ENC_mk(fields_written, encoded) =>
    (case+ read of
     | @U@DEC_ok(fields_read, decoded) => let
         prval EQRR_refl() = decodes_functional(whole, encodes_decodes(encoded), decoded)
         prval @U@V_mk() = fields_written
         prval @U@V_mk() = fields_read
       in @U@RES_refl() end
     | @U@DEC_loss(_, decoded) =>
       (case+ decodes_functional(whole, encodes_decodes(encoded), decoded) of EQRR_refl() =/=> ())
     | @U@DEC_notquire(decoded) =>
       (case+ decodes_functional(whole, encodes_decodes(encoded), decoded) of EQRR_refl() =/=> ())
     | @U@DEC_newer(decoded) =>
       (case+ decodes_functional(whole, encodes_decodes(encoded), decoded) of EQRR_refl() =/=> ())
     | @U@DEC_damaged(decoded) =>
       (case+ decodes_functional(whole, encodes_decodes(encoded), decoded) of EQRR_refl() =/=> ()))

(* a @p@ record at run time: its format version, the least version that reads it, the @p@,
   and the chunks kept *)
#pub datavtype @p@record(@p@x, int, int, extras) =
  | {@p@_value:@p@x}{format_version,least_version:int | 0 <= format_version; format_version < 256; 0 <= least_version; least_version <= READER}{kept_extras:extras}{extra_count:nat}
    @C@Record(@p@_value, format_version, least_version, kept_extras) of (int format_version, int least_version, @p@v(@p@_value), extrasv(kept_extras, extra_count))

#pub datavtype @p@read(@p@res) =
  | {@p@_value:@p@x}{format_version,least_version:int}{kept_extras:extras} @QU@_ok(@ql@_ok(@p@_value, format_version, least_version, kept_extras)) of @p@record(@p@_value, format_version, least_version, kept_extras)
  | {@p@_value:@p@x}{format_version,least_version:int}{kept_extras:extras}{lost_groups:lost}{lost_count:nat} @QU@_loss(@ql@_loss(@p@_value, format_version, least_version, kept_extras, lost_groups)) of (@p@record(@p@_value, format_version, least_version, kept_extras), lostv(lost_groups, lost_count))
  | @QU@_notquire(@ql@_notquire())
  | @QU@_newer(@ql@_newer())
  | @QU@_damaged(@ql@_damaged())

#pub fun @p@_record_write {@p@_value:@p@x}{format_version,least_version:int}{kept_extras:extras} (record: !@p@record(@p@_value, format_version, least_version, kept_extras))
  : [octets:bytes][written_len:nat] (@U@ENC(@p@_value, format_version, least_version, kept_extras, octets) | blist(octets, written_len))

implement @p@_record_write {@p@_value}{format_version,least_version}{kept_extras} (record) =
  case+ record of
  | @C@Record(format_version, least_version, @p@, extras) => let
      val specs = @p@_specs()
      val (fields | vals) = @p@_to_vals(@p@)
      val (written | record_bytes) = record_write(specs, @K@, format_version, least_version, vals, extras)
      val () = gvalsv_free(vals)
      val () = specsv_free(specs)
    in (@U@ENC_mk(fields, written) | record_bytes) end

#pub fun @p@_record_read {octets:bytes}{byte_count:nat} (list: blist(octets, byte_count)): [outcome:@p@res] (@U@DEC(octets, outcome) | @p@read(outcome))

implement @p@_record_read {octets}{byte_count} (list) = let
  val specs = @p@_specs()
  val (read | read_outcome) = record_read(specs, @K@, list)
  val () = specsv_free(specs)
in
  case+ read_outcome of
  | ~RR_ok(format_version, least_version, vals, extras) => let
      val (fields | @p@) = @p@_of_vals(vals)
    in (@U@DEC_ok(fields, read) | @QU@_ok(@C@Record(format_version, least_version, @p@, extras))) end
  | ~RR_loss(format_version, least_version, vals, extras, lost) => let
      val (fields | @p@) = @p@_of_vals(vals)
    in (@U@DEC_loss(fields, read) | @QU@_loss(@C@Record(format_version, least_version, @p@, extras), lost)) end
  | ~RR_notquire() => (@U@DEC_notquire(read) | @QU@_notquire())
  | ~RR_newer() => (@U@DEC_newer(read) | @QU@_newer())
  | ~RR_damaged() => (@U@DEC_damaged(read) | @QU@_damaged())
end

(* A result of reading as another it is the same as *)
#pub fun @p@_read_recast {first,second:@p@res} (same: @U@RES(first, second) | read: @p@read(first)): @p@read(second)

implement @p@_read_recast {first,second} (same | read) = let
  prval @U@RES_refl() = same
in read end

(* A decoding as the decoding it is the same as *)
#pub prfun @p@_dec_recast {octets:bytes}{first,second:@p@res} (@U@RES(first, second), @U@DEC(octets, first)): @U@DEC(octets, second)

primplement @p@_dec_recast {octets}{first,second} (same, dec) = let
  prval @U@RES_refl() = same
in dec end
""")
emit("end")
text = "\n".join(lines) + "\n"
RESULT_PREFIX = "BR" if NAME == "book" else "IR"
text = text.replace("@QU@", RESULT_PREFIX).replace("@ql@", RESULT_PREFIX.lower()).replace("@K@", str(KIND)).replace("@U@", UPPER).replace("@C@", CAPITAL).replace("@p@", PREFIX)
open(f"src/{PREFIX}rec.bats", "w").write(text)
