# Generates src/<name>image.bats: a stored record as values (an image) indexed by the record it holds,
# the groups that differ between two images, and a record patched with the groups of an image.
# What is proved: an image is the record's value (book_image_of and book_of_image keep it), a string of
# an image is held by the cells of its array (bytesarr's bstr), and a number is the number its bytes
# make (fields' int32v), so a record written from an image and read again is that image.
# usage: python3 gen-image.py book | index
import sys, os
NAME = sys.argv[1]
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from record_tables import tables
GROUPS, KIND = tables(NAME)
P = NAME
C = NAME.capitalize()
QU = "BR" if NAME == "book" else "IR"
X = f"{P}x"
fields = [f for g in GROUPS for f in g[2]]
ints = [n for n, k in fields if k == "i"]
strs = [n for n, k in fields if k == "s"]
Pv = f"{P}v"
Prec = f"{P}record"
o = []
w = o.append


def quant():
    return "".join(f"{{{n}:int}}" if k == "i" else f"{{{n}:bytes}}" for n, k in fields)


def field_types():
    return ", ".join(f"int32v({n})" if k == "i" else f"bstr({n})" for n, k in fields)


def index_term():
    return f"{X}_mk({', '.join(n for n, _ in fields)})"


def pat(prefix):
    return ", ".join(f"{prefix}_{n}" for n, _ in fields)


bits = {g[0]: 1 << gi for gi, g in enumerate(GROUPS)}


def group_of(name):
    for g in GROUPS:
        for n, k in g[2]:
            if n == name:
                return g


w(f"(* {P}image -- a stored {P} as values, indexed by the {P} they hold: what differs between two, and a record patched with it.\n   Generated by scripts/gen-image.py {P} *)\n")
w("#target wasm begin\n")
w('#include "share/atspre_staload.hats"\n')
w("#use array as A\n#use arith as AR\n")
for m in ["bytes", "fields", "schema", "record", "bytesarr", f"{P}rec"]:
    w(f'staload "{m}.sats"')
w("")
w(f"(* A stored {P} as values: each number as its four bytes, each string in an array that holds it.\n   The index says which {P} it is. *)")
w(f"#pub datavtype {P}_image({X}) =\n  | {quant()}\n    {C}Image({index_term()}) of ({field_types()})\n")
w(f"(* The image of a {P}, or none: a string too long for an array *)")
w(f"#pub datavtype {P}_imaged({X}) =\n  | {{x:{X}}} {C}Imaged(x) of {P}_image(x)\n  | {{x:{X}}} {C}NotImaged(x) of ()\n")
numbers_fields = ", ".join(f"{n} = Int" for n in ints)
w(f"(* The numbers of a stored {P}, by name *)\n#pub typedef {P}_numbers = @{{{numbers_fields}}}\n")

# free
w(f"#pub fun {P}_image_free {{x:{X}}} (image: {P}_image(x)): void\n")
w(f"implement {P}_image_free {{x}} (image) =\n  case+ image of\n  | ~{C}Image({pat('a')}) => let")
for n, k in fields:
    w(f"      val () = {'int32_free' if k == 'i' else 'bstr_free'}(a_{n})")
w("    in () end\n")
# copy
w(f"#pub fun {P}_image_copy {{x:{X}}} (image: !{P}_image(x)): {P}_image(x)\n")
w(f"implement {P}_image_copy {{x}} (image) =\n  case+ image of\n  | {C}Image({pat('a')}) => let")
for n, k in fields:
    w(f"      val c_{n} = {'int32_copy' if k == 'i' else 'bstr_copy'}(a_{n})")
w(f"    in {C}Image({', '.join('c_' + n for n, _ in fields)}) end\n")
# numbers
w(f"(* The numbers of an image *)\n#pub fun {P}_image_numbers {{x:{X}}} (image: !{P}_image(x)): {P}_numbers\n")
nums = ", ".join(f"{n} = int32_value(a_{n})" for n in ints)
w(f"implement {P}_image_numbers {{x}} (image) =\n  case+ image of\n  | {C}Image({pat('a')}) => @{{{nums}}}\n")
# strings
w("(* A string of an image: its length, and a copy of its bytes in an array one longer *)")
for n in strs:
    w(f"#pub fun {P}_image_{n} {{x:{X}}} (image: !{P}_image(x)): [l:agz][len:nat | len < 256] @($A.arr(byte, l, len + 1), int len)\n")
    w(f"implement {P}_image_{n} {{x}} (image) =\n  case+ image of\n  | {C}Image({pat('a')}) => array_of_bstr(a_{n})\n")
# group bits
for g in GROUPS:
    w(f"(* the bit of the group {g[0]} in a mask of groups *)\n#pub fn {P}_group_{g[0].lower()} (): int\n\nimplement {P}_group_{g[0].lower()} () = {bits[g[0]]}\n")
w(f"(* every group *)\n#pub fn {P}_group_all (): int\n\nimplement {P}_group_all () = {(1 << len(GROUPS)) - 1}\n")
merge_fields = ", ".join(f"{n} = (if $AR.band_int_int(keep_mask, {bits[group_of(n)[0]]}) <> 0 then kept.{n} else other.{n})" for n in ints)
w(f"(* The numbers of kept in the groups of keep_mask, and the others' of other *)\n#pub fun {P}_numbers_merge (kept: {P}_numbers, other: {P}_numbers, keep_mask: int): {P}_numbers\n")
w(f"implement {P}_numbers_merge (kept, other, keep_mask) = @{{{merge_fields}}}\n")


def differs(g, a, b):
    parts = []
    for n, k in g[2]:
        if k == "i":
            parts.append(f"(int32_value({a}_{n}) <> int32_value({b}_{n}))")
        else:
            parts.append(f"(~bstr_equal({a}_{n}, {b}_{n}))")
    return " || ".join(parts)


w(f"(* The groups whose fields differ in two images, as a mask *)\n#pub fun {P}_image_diff {{x,y:{X}}} (first: !{P}_image(x), second: !{P}_image(y)): int\n")
w(f"implement {P}_image_diff {{x,y}} (first, second) =\n  case+ first of\n  | {C}Image({pat('a')}) =>\n    (case+ second of\n     | {C}Image({pat('b')}) => let")
for g in GROUPS:
    w(f"         val m_{g[0].lower()} = (if {differs(g, 'a', 'b')} then {bits[g[0]]} else 0): int")
sumexpr = "0"
for g in GROUPS:
    sumexpr = f"$AR.add_int_int({sumexpr}, m_{g[0].lower()})"
w(f"       in {sumexpr} end)\n")

# of / to book
w(f"(* The image of a {P}: the very {P} *)\n#pub fun {P}_image_of {{x:{X}}} ({P}: !{Pv}(x)): {P}_image(x)\n")
w(f"implement {P}_image_of {{x}} ({P}) =\n  case+ {P} of\n  | {C}V({pat('b')}) => let")
for n, k in fields:
    if k == "i":
        w(f"      val n_{n} = int32_copy(b_{n})")
    else:
        w(f"      val s_{n} = bstr_of_blist(b_{n})")
iargs = ", ".join(f"n_{n}" if k == "i" else f"s_{n}" for n, k in fields)
w(f"    in {C}Image({iargs}) end\n")

w(f"(* The {P} an image holds *)\n#pub fun {P}_of_image {{x:{X}}} (image: !{P}_image(x)): {Pv}(x)\n")
w(f"implement {P}_of_image {{x}} (image) =\n  case+ image of\n  | {C}Image({pat('a')}) => let")
for n, k in fields:
    if k == "i":
        w(f"      val n_{n} = int32_copy(a_{n})")
    else:
        w(f"      val l_{n} = blist_of_bstr(a_{n})")
cargs = ", ".join(f"n_{n}" if k == "i" else f"l_{n}" for n, k in fields)
w(f"    in {C}V({cargs}) end\n")

# record level
w(f"(* The image of a stored {P}, as read *)\n#pub fun {P}_record_image {{x:{X}}}{{ver,minver:int}}{{e:extras}} (record: !{Prec}(x, ver, minver, e)): {P}_image(x)\n")
w(f"implement {P}_record_image {{x}}{{ver,minver}}{{e}} (record) =\n  case+ record of {C}Record(_, _, {P}, _) => {P}_image_of({P})\n")
w(f"(* A new record of an image: the format version this Quire writes, and no chunks kept. It holds the very {P} the image does. *)\n#pub fun {P}_record_new {{x:{X}}} (image: !{P}_image(x)): {Prec}(x, 1, 1, ex_nil())\n")
w(f"implement {P}_record_new {{x}} (image) = {C}Record(1, 1, {P}_of_image(image), EXV_nil())\n")
w(f"fn {P}_free_book {{x:{X}}} ({P}: {Pv}(x)): void =\n  case+ {P} of\n  | ~{C}V({pat('f')}) => let")
for n, k in fields:
    w(f"      val () = {'int32_free' if k == 'i' else 'blist_free'}(f_{n})")
w("    in () end\n")
w(f"(* A record freed *)\n#pub fun {P}_record_free {{x:{X}}}{{ver,minver:int}}{{e:extras}} (record: {Prec}(x, ver, minver, e)): void\n")
w(f"implement {P}_record_free {{x}}{{ver,minver}}{{e}} (record) =\n  case+ record of\n  | ~{C}Record(_, _, {P}, extras) => let\n      val () = {P}_free_book({P})\n    in extrasv_free(extras) end\n")
# patch
w("""(* The number of the record, or the image's *)
fn _pick_number {a,b:int} (take: bool, kept: int32v(a), other: !int32v(b)): [v:int] int32v(v) =
  if take then let val () = int32_free(kept) in int32_copy(other) end else kept

(* The bytes of the record, or those the image's array holds *)
fn _pick_text {first,second:bytes}{n:nat | n < 256} (take: bool, kept: blist(first, n), other: !bstr(second)): [bs:bytes][len:nat | len < 256] blist(bs, len) =
  if take then let val () = blist_free(kept) in blist_of_bstr(other) end else kept
""")
w(f"(* The record with the groups in the mask taken from the image, and the others as they are *)")
w(f"#pub fun {P}_record_patch {{x,y:{X}}}{{ver,minver:int}}{{e:extras}} (record: {Prec}(x, ver, minver, e), image: !{P}_image(y), mask: int)\n  : [z:{X}] {Prec}(z, ver, minver, e)\n")
w(f"implement {P}_record_patch {{x,y}}{{ver,minver}}{{e}} (record, image, mask) =\n  case+ record of\n  | ~{C}Record(ver, minver, {P}, extras) =>\n    (case+ {P} of\n     | ~{C}V({pat('f')}) =>\n       (case+ image of\n        | {C}Image({pat('a')}) => let")
for g in GROUPS:
    w(f"            val take_{g[0].lower()} = $AR.band_int_int(mask, {bits[g[0]]}) <> 0")
for g in GROUPS:
    for n, k in g[2]:
        t = f"take_{g[0].lower()}"
        if k == "i":
            w(f"            val c_{n} = _pick_number({t}, f_{n}, a_{n})")
        else:
            w(f"            val c_{n} = _pick_text({t}, f_{n}, a_{n})")
cargs = ", ".join(f"c_{n}" for n, _ in fields)
w(f"          in {C}Record(ver, minver, {C}V({cargs}), extras) end))\n")

# make from plain data
strs_decl = ", ".join(f"{n}: $A.arr(byte, {n}_loc, {n}_len + 1), {n}_len: int {n}_len" for n in strs)
quant_loc = ",".join(f"{n}_loc" for n in strs)
quant_len = ",".join(f"{n}_len" for n in strs)
lencon = "; ".join(f"{n}_len < 256" for n in strs)
w(f"(* An image of numbers and strings (each in an array one longer than the string, which it takes), or none when a number is not one of 32 bits *)")
w(f"#pub fun {P}_image_make {{{quant_loc}:agz}}{{{quant_len}:nat | {lencon}}}\n  (numbers: {P}_numbers, {strs_decl}): [x:{X}] {P}_imaged(x)\n")
make_args = ", ".join(f"{n}, {n}_len" for n in strs)
w(f"implement {P}_image_make (numbers, {', '.join(n + ', ' + n + '_len' for n in strs)}) = let")
w("  fn release {l:agz}{len:nat | len < 256} (array: $A.arr(byte, l, len + 1)): void = $A.free<byte>(array)")


def free_arrays(pad):
    for n in strs:
        w(f"{pad}val () = $A.free<byte>({n})")


def free_numbers(pad, upto):
    for m in ints[:upto]:
        w(f"{pad}val () = int32_free(n_{m})")


w("in")
for i, n in enumerate(ints):
    pad = "  " + "  " * i
    w(f"{pad}case+ int32_make(numbers.{n}) of")
    w(f"{pad}| ~I32_unrepresentable() => let")
    free_numbers(pad + "    ", i)
    free_arrays(pad + "    ")
    w(f"{pad}  in {C}NotImaged() end")
    w(f"{pad}| ~I32_made(n_{n}) =>")
pad = "  " + "  " * len(ints)
w(f"{pad}let")
for n in strs:
    w(f"{pad}  val s_{n} = bstr_of_array({n}, {n}_len)")
    w(f"{pad}  val () = $A.free<byte>({n})")
args = ", ".join(f"n_{n}" if k == "i" else f"s_{n}" for n, k in fields)
w(f"{pad}in {C}Imaged({C}Image({args})) end")
w("end\n")
# round trip
w(f"""(* An image written as a record and read back: an image of the very {P}. That the bytes read are
   those written is the checked part (a {P} written is read back, whatever bytes they are);
   the image comes out of the record read, not out of the one written. *)
#pub fun {P}_image_roundtrip {{x:{X}}} (image: !{P}_image(x)): {P}_image(x)

implement {P}_image_roundtrip {{x}} (image) = let
  val record = {P}_record_new(image)
  val (written | list) = {P}_record_write(record)
  val () = {P}_record_free(record)
  val (whole | count) = blist_len(list)
  val (read_proof | read) = {P}_record_read(list)
  prval same = {P}_enc_dec(whole, written, read_proof)
  val checked = {P}_read_recast(same | read)
in
  case+ checked of
  | ~{QU}_ok(record_read) => let
      val back = {P}_record_image(record_read)
      val () = {P}_record_free(record_read)
    in back end
end
""")
w("end")
open(f"src/{P}image.bats", "w").write("\n".join(o) + "\n")
