# Generates src/<name>rec.bats: python3 gen_record.py book | index
import sys
NAME = sys.argv[1]
U = NAME.upper()
P = NAME
C = NAME.capitalize()
BOOK_GROUPS = [
  # tag, mode, fields (name, kind)
  ("AUTH", "req", [("author", "s")]),
  ("BOOK", "req", [("id_high", "i"), ("id_low", "i")]),
  ("COLL", "opt", [("collections", "i"), ("collections_modified", "i")]),
  ("ELSE", "opt", [("minutes_elsewhere", "i"), ("pages_elsewhere", "i")]),
  ("FNSH", "opt", [("finished_at", "i"), ("finished_modified", "i")]),
  ("PLCE", "opt", [("chapter", "i"), ("chapters", "i"), ("page", "i"), ("pages", "i"), ("anchor", "i"), ("place_modified", "i"), ("place_declined", "i")]),
  ("SERI", "opt", [("series", "s"), ("series_number", "i")]),
  ("SHLF", "opt", [("shelf", "i"), ("added", "i"), ("opened", "i"), ("shelf_modified", "i")]),
  ("SIZE", "opt", [("file_size", "i"), ("cover", "i"), ("done", "i")]),
  ("TIME", "opt", [("minutes_read", "i"), ("pages_read", "i")]),
  ("TITL", "req", [("title", "s")]),
]
BOOK_KIND = 1
INDEX_GROUPS = [
  ("LEGA", "opt", [("legacy_crc_high", "i"), ("legacy_crc_low", "i")]),
  ("NAMS", "req", [("name_count", "i")] + [(f"name{k}", "s") for k in range(8)]),
]
INDEX_KIND = 2
GROUPS = BOOK_GROUPS if NAME == "book" else INDEX_GROUPS
KIND = BOOK_KIND if NAME == "book" else INDEX_KIND
fields = [f for g in GROUPS for f in g[2]]

def bytes_lit(tag):
    out = "bnil()"
    for ch in reversed(tag):
        out = f"bcons({ord(ch)}, {out})"
    return out

def static_name(name):
    return name

o = []
w = o.append
w("(* @p@rec -- the library's @p@ record: its groups and fields, generated by scripts/gen-@p@rec.py *)\n")
w("#target wasm begin\n")
w('#include "share/atspre_staload.hats"\n')
for m in ["bytes","crc","chunk","seq","fields","schema","record"]:
    w(f'staload "{m}.sats"')
w("")
# datasort
params = ", ".join("int" if k == "i" else "bytes" for _, k in fields)
w(f"#pub datasort @p@x =\n  | @p@x_mk of ({params})\n")
# layouts and specs
def layout(g):
    s = "lo_nil()"
    for _, k in reversed(g[2]):
        s = f"lo_i32({s})" if k == "i" else f"lo_str({s})"
    return s
def default_vals(g):
    s = "fv_nil()"
    for _, k in reversed(g[2]):
        s = f"fv_i32(0, {s})" if k == "i" else f"fv_str(bnil(), {s})"
    return s
spec = "gs_nil()"
for g in reversed(GROUPS):
    spec = f"gs_cons({bytes_lit(g[0])}, {layout(g)}, m_{g[1]}(), {default_vals(g)}, {spec})"
w(f"#pub stadef @U@_SPECS = {spec}\n")
w(f"#pub stadef @U@_KIND = {KIND}\n")
# the spec at run time
def layoutv(g):
    s = "LYV_nil()"
    for _, k in reversed(g[2]):
        s = f"LYV_i32({s})" if k == "i" else f"LYV_str({s})"
    return s
def defaultv(g):
    s = "FVV_nil()"
    for _, k in reversed(g[2]):
        s = f"FVV_i32(int32_zero(), {s})" if k == "i" else f"FVV_str(blist_nil(), {s})"
    return s
def tagv(tag):
    s = "blist_nil()"
    for ch in reversed(tag):
        s = f"blist_cons({ord(ch)}, {s})"
    return s
runtime = "SPV_nil()"
for g in reversed(GROUPS):
    runtime = f"SPV_cons(TAGNOT_mk() | {tagv(g[0])}, {layoutv(g)}, Mode{g[1].capitalize()}(), {defaultv(g)}, {runtime})"
w(f"#pub fun @p@_specs (): specsv(@U@_SPECS, {len(GROUPS)})\n")
w(f"implement @p@_specs () = {runtime}\n")
# @U@V
def vals_term(group_fields_vals):
    pass
def group_vals_static(g):
    s = "fv_nil()"
    for name, k in reversed(g[2]):
        s = f"fv_i32({name}, {s})" if k == "i" else f"fv_str({name}, {s})"
    return s
gv = "gv_nil()"
for g in reversed(GROUPS):
    gv = f"gv_cons({group_vals_static(g)}, {gv})"
names = ", ".join(n for n, _ in fields)
quant_i = ",".join(n for n, k in fields if k == "i")
quant_s = ",".join(n for n, k in fields if k == "s")
w(f"(* @U@V(x, vals): the values of the groups are the fields of the @p@ x *)")
w(f"#pub dataprop @U@V(@p@x, gvals) =\n  | {{{quant_i}:int}}{{{quant_s}:bytes}}\n    @U@V_mk(@p@x_mk({names}), {gv})\n")
# runtime struct
decl = []
for name, k in fields:
    if k == "i":
        decl.append(f"int32v({name})")
    else:
        decl.append(f"blist({name}, {name}_len)")
quant_len = ",".join(n + "_len" for n, k in fields if k == "s")
quant_i_range = "{" + ",".join(n for n, k in fields if k == "i") + ":int}"
w(f"#pub datavtype @p@v(@p@x) =\n  | {quant_i_range}{{{quant_s}:bytes}}{{{quant_len}:nat | " + "; ".join(f"{n}_len < 256" for n, k in fields if k == "s") + f"}}\n    @C@V(@p@x_mk({names})) of ({', '.join(decl)})\n")
# to_vals
w("(* The record as the values of its groups, with the proof that they are its fields *)")
w(f"#pub fun @p@_to_vals {{x:@p@x}} (@p@: !@p@v(x)): [vals:gvals] (@U@V(x, vals) | gvalsv(@U@_SPECS, vals, {len(GROUPS)}))\n")
w("implement @p@_to_vals {x} (@p@) =\n  case+ @p@ of")
pat = ", ".join(n for n, _ in fields)
w(f"  | @C@V({pat}) => (@U@V_mk() | " )
def build(g):
    s = "FVV_nil()"
    for name, k in reversed(g[2]):
        s = f"FVV_i32(int32_copy({name}), {s})" if k == "i" else f"FVV_str(blist_copy({name}), {s})"
    return s
gvv = "GVV_nil()"
for g in reversed(GROUPS):
    gvv = f"GVV_cons({build(g)}, {gvv})"
w(f"    {gvv})\n")

# of_vals
w("(* The record made of the values of its groups, with the proof that they are its fields *)")
w(f"#pub fun @p@_of_vals {{vals:gvals}}{{kv:nat}} (vals: gvalsv(@U@_SPECS, vals, kv)): [x:@p@x] (@U@V(x, vals) | @p@v(x))\n")
def pat(g):
    s = "~FVV_nil()"
    for name, k in reversed(g[2]):
        s = f"~FVV_i32({name}, {s})" if k == "i" else f"~FVV_str({name}, {s})"
    return s
gpat = "~GVV_nil()"
for g in reversed(GROUPS):
    gpat = f"~GVV_cons({pat(g)}, {gpat})"
w("implement @p@_of_vals {vals}{kv} (vals) =")
w(f"  case+ vals of")
w("  | " + gpat + " => (@U@V_mk() | @C@V(" + ", ".join(n for n,_ in fields) + "))\n")

w("""
(* what reading a stored @p@ comes to *)
#pub datasort @p@res =
  | br_ok of (@p@x, int, int, extras)
  | br_loss of (@p@x, int, int, extras, lost)
  | br_notquire of ()
  | br_newer of ()
  | br_damaged of ()

(* @U@ENC(x, ver, minver, e, bs): bs is the @p@ x, written in the format ver,
   readable from minver, with the chunks e kept *)
#pub dataprop @U@ENC(@p@x, int, int, extras, bytes) =
  | {x:@p@x}{ver,minver:int}{e:extras}{vals:gvals}{bs:bytes}
    @U@ENC_mk(x, ver, minver, e, bs) of (@U@V(x, vals), ENCODES(@U@_SPECS, @U@_KIND, rx_mk(ver, minver, vals, e), bs))

(* @U@DEC(bs, res): reading bs as a @p@ comes to res *)
#pub dataprop @U@DEC(bytes, @p@res) =
  | {x:@p@x}{ver,minver:int}{e:extras}{vals:gvals}{bs:bytes}
    @U@DEC_ok(bs, br_ok(x, ver, minver, e)) of (@U@V(x, vals), DECODES(@U@_SPECS, @U@_KIND, bs, rr_ok(rx_mk(ver, minver, vals, e))))
  | {x:@p@x}{ver,minver:int}{e:extras}{t:lost}{vals:gvals}{bs:bytes}
    @U@DEC_loss(bs, br_loss(x, ver, minver, e, t)) of (@U@V(x, vals), DECODES(@U@_SPECS, @U@_KIND, bs, rr_loss(rx_mk(ver, minver, vals, e), t)))
  | {bs:bytes} @U@DEC_notquire(bs, br_notquire()) of DECODES(@U@_SPECS, @U@_KIND, bs, rr_notquire())
  | {bs:bytes} @U@DEC_newer(bs, br_newer()) of DECODES(@U@_SPECS, @U@_KIND, bs, rr_newer())
  | {bs:bytes} @U@DEC_damaged(bs, br_damaged()) of DECODES(@U@_SPECS, @U@_KIND, bs, rr_damaged())

(* a @p@ record at run time: its format version, the least version that reads it, the @p@,
   and the chunks kept *)
#pub datavtype @p@record(@p@x, int, int, extras) =
  | {x:@p@x}{ver,minver:int | 0 <= ver; ver < 256; 0 <= minver; minver <= READER}{e:extras}{ke:nat}
    @C@Record(x, ver, minver, e) of (int ver, int minver, @p@v(x), extrasv(e, ke))

#pub datavtype @p@read(@p@res) =
  | {x:@p@x}{ver,minver:int}{e:extras} BR_ok(br_ok(x, ver, minver, e)) of @p@record(x, ver, minver, e)
  | {x:@p@x}{ver,minver:int}{e:extras}{t:lost}{kl:nat} BR_loss(br_loss(x, ver, minver, e, t)) of (@p@record(x, ver, minver, e), lostv(t, kl))
  | BR_notquire(br_notquire())
  | BR_newer(br_newer())
  | BR_damaged(br_damaged())

#pub fun @p@_write {x:@p@x}{ver,minver:int}{e:extras} (record: !@p@record(x, ver, minver, e))
  : [bs:bytes][m:nat] (@U@ENC(x, ver, minver, e, bs) | blist(bs, m))

implement @p@_write {x}{ver,minver}{e} (record) =
  case+ record of
  | @C@Record(ver, minver, @p@, extras) => let
      val specs = @p@_specs()
      val (fields | vals) = @p@_to_vals(@p@)
      val (written | out) = record_write(specs, @K@, ver, minver, vals, extras)
      val () = gvalsv_free(vals)
      val () = specsv_free(specs)
    in (@U@ENC_mk(fields, written) | out) end

#pub fun @p@_read {bs:bytes}{n:nat} (list: blist(bs, n)): [res:@p@res] (@U@DEC(bs, res) | @p@read(res))

implement @p@_read {bs}{n} (list) = let
  val specs = @p@_specs()
  val (read | out) = record_read(specs, @K@, list)
  val () = specsv_free(specs)
in
  case+ out of
  | ~RR_ok(ver, minver, vals, extras) => let
      val (fields | @p@) = @p@_of_vals(vals)
    in (@U@DEC_ok(fields, read) | BR_ok(@C@Record(ver, minver, @p@, extras))) end
  | ~RR_loss(ver, minver, vals, extras, lost) => let
      val (fields | @p@) = @p@_of_vals(vals)
    in (@U@DEC_loss(fields, read) | BR_loss(@C@Record(ver, minver, @p@, extras), lost)) end
  | ~RR_notquire() => (@U@DEC_notquire(read) | BR_notquire())
  | ~RR_newer() => (@U@DEC_newer(read) | BR_newer())
  | ~RR_damaged() => (@U@DEC_damaged(read) | BR_damaged())
end
""")
w("end")
text = "\n".join(o) + "\n"
text = text.replace("@K@", str(KIND)).replace("@U@", U).replace("@C@", C).replace("@p@", P)
open(f"src/{P}rec.bats", "w").write(text)
