# Generates src/<name>image.bats: a stored record as values (an image) indexed by the record it holds,
# the groups that differ between two images, and a record patched with the groups of an image.
# What is proved: an image is the record's value (book_image_of and book_of_image keep it), a string of
# an image is held by the cells of its array (bytesarr's bstr), and a number is the number its bytes
# make (fields' int32v), so a record written from an image and read again is that image.
# usage: python3 gen-image.py book | index
import sys
import os
NAME = sys.argv[1]
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from record_tables import tables
GROUPS, KIND = tables(NAME)
PREFIX = NAME
CAPITAL = NAME.capitalize()
RESULT_PREFIX = "BR" if NAME == "book" else "IR"
SORT = f"{PREFIX}x"
fields = [field for group in GROUPS for field in group[2]]
ints = [name for name, kind in fields if kind == "i"]
strs = [name for name, kind in fields if kind == "s"]
VALUE = f"{PREFIX}v"
RECORD = f"{PREFIX}record"
lines = []
emit = lines.append


def quant():
    return "".join(f"{{{name}:int}}" if kind == "i" else f"{{{name}:bytes}}" for name, kind in fields)


def field_types():
    return ", ".join(f"int32v({name})" if kind == "i" else f"bstr({name})" for name, kind in fields)


def index_term():
    return f"{SORT}_mk({', '.join(name for name, _ in fields)})"


def pattern(prefix):
    return ", ".join(f"{prefix}_{name}" for name, _ in fields)


bits = {group[0]: 1 << group_index for group_index, group in enumerate(GROUPS)}


def group_of(field_name):
    for group in GROUPS:
        for name, kind in group[2]:
            if name == field_name:
                return group


emit(f"(* {PREFIX}image -- a stored {PREFIX} as values, indexed by the {PREFIX} they hold: what differs between two, and a record patched with it.\n   Generated by scripts/gen-image.py {PREFIX} *)\n")
emit("#target wasm begin\n")
emit('#include "share/atspre_staload.hats"\n')
emit("#use array as A\n#use arith as AR\n")
for module in ["bytes", "fields", "schema", "record", "bytesarr", f"{PREFIX}rec"]:
    emit(f'staload "{module}.sats"')
emit("")
emit(f"(* A stored {PREFIX} as values: each number as its four bytes, each string in an array that holds it.\n   The index says which {PREFIX} it is. *)")
emit(f"#pub datavtype {PREFIX}_image({SORT}) =\n  | {quant()}\n    {CAPITAL}Image({index_term()}) of ({field_types()})\n")
emit(f"(* The image of a {PREFIX}, or none: a string too long for an array *)")
emit(f"#pub datavtype {PREFIX}_imaged({SORT}) =\n  | {{{PREFIX}_value:{SORT}}} {CAPITAL}Imaged({PREFIX}_value) of {PREFIX}_image({PREFIX}_value)\n  | {{{PREFIX}_value:{SORT}}} {CAPITAL}NotImaged({PREFIX}_value) of ()\n")
numbers_fields = ", ".join(f"{name} = Int" for name in ints)
emit(f"(* The numbers of a stored {PREFIX}, by name *)\n#pub typedef {PREFIX}_numbers = @{{{numbers_fields}}}\n")

# free
emit(f"#pub fun {PREFIX}_image_free {{{PREFIX}_value:{SORT}}} (image: {PREFIX}_image({PREFIX}_value)): void\n")
emit(f"implement {PREFIX}_image_free {{{PREFIX}_value}} (image) =\n  case+ image of\n  | ~{CAPITAL}Image({pattern('image')}) => let")
for name, kind in fields:
    emit(f"      val () = {'int32_free' if kind == 'i' else 'bstr_free'}(image_{name})")
emit("    in () end\n")
# copy
emit(f"#pub fun {PREFIX}_image_copy {{{PREFIX}_value:{SORT}}} (image: !{PREFIX}_image({PREFIX}_value)): {PREFIX}_image({PREFIX}_value)\n")
emit(f"implement {PREFIX}_image_copy {{{PREFIX}_value}} (image) =\n  case+ image of\n  | {CAPITAL}Image({pattern('image')}) => let")
for name, kind in fields:
    emit(f"      val copy_{name} = {'int32_copy' if kind == 'i' else 'bstr_copy'}(image_{name})")
emit(f"    in {CAPITAL}Image({', '.join('copy_' + name for name, _ in fields)}) end\n")
# numbers
emit(f"(* The numbers of an image *)\n#pub fun {PREFIX}_image_numbers {{{PREFIX}_value:{SORT}}} (image: !{PREFIX}_image({PREFIX}_value)): {PREFIX}_numbers\n")
number_values = ", ".join(f"{name} = int32_value(image_{name})" for name in ints)
emit(f"implement {PREFIX}_image_numbers {{{PREFIX}_value}} (image) =\n  case+ image of\n  | {CAPITAL}Image({pattern('image')}) => @{{{number_values}}}\n")
# strings
emit("(* A string of an image: its length, and a copy of its bytes in an array one longer *)")
for name in strs:
    emit(f"#pub fun {PREFIX}_image_{name} {{{PREFIX}_value:{SORT}}} (image: !{PREFIX}_image({PREFIX}_value)): [text_loc:agz][text_len:nat | text_len < 256] @($A.arr(byte, text_loc, text_len + 1), int text_len)\n")
    emit(f"implement {PREFIX}_image_{name} {{{PREFIX}_value}} (image) =\n  case+ image of\n  | {CAPITAL}Image({pattern('image')}) => array_of_bstr(image_{name})\n")
# group bits
for group in GROUPS:
    emit(f"(* the bit of the group {group[0]} in a mask of groups *)\n#pub fn {PREFIX}_group_{group[0].lower()} (): int\n\nimplement {PREFIX}_group_{group[0].lower()} () = {bits[group[0]]}\n")
emit(f"(* every group *)\n#pub fn {PREFIX}_group_all (): int\n\nimplement {PREFIX}_group_all () = {(1 << len(GROUPS)) - 1}\n")
merge_fields = ", ".join(f"{name} = (if $AR.band_int_int(keep_mask, {bits[group_of(name)[0]]}) <> 0 then kept.{name} else other.{name})" for name in ints)
emit(f"(* The numbers of kept in the groups of keep_mask, and the others' of other *)\n#pub fun {PREFIX}_numbers_merge (kept: {PREFIX}_numbers, other: {PREFIX}_numbers, keep_mask: int): {PREFIX}_numbers\n")
emit(f"implement {PREFIX}_numbers_merge (kept, other, keep_mask) = @{{{merge_fields}}}\n")


def differs(group, first, second):
    parts = []
    for name, kind in group[2]:
        if kind == "i":
            parts.append(f"(int32_value({first}_{name}) <> int32_value({second}_{name}))")
        else:
            parts.append(f"(~bstr_equal({first}_{name}, {second}_{name}))")
    return " || ".join(parts)


emit(f"(* The groups whose fields differ in two images, as a mask *)\n#pub fun {PREFIX}_image_diff {{first_value,second_value:{SORT}}} (first: !{PREFIX}_image(first_value), second: !{PREFIX}_image(second_value)): int\n")
emit(f"implement {PREFIX}_image_diff {{first_value,second_value}} (first, second) =\n  case+ first of\n  | {CAPITAL}Image({pattern('first')}) =>\n    (case+ second of\n     | {CAPITAL}Image({pattern('second')}) => let")
for group in GROUPS:
    emit(f"         val differs_{group[0].lower()} = (if {differs(group, 'first', 'second')} then {bits[group[0]]} else 0): int")
sum_expr = "0"
for group in GROUPS:
    sum_expr = f"$AR.add_int_int({sum_expr}, differs_{group[0].lower()})"
emit(f"       in {sum_expr} end)\n")

# of / to book
emit(f"(* The image of a {PREFIX}: the very {PREFIX} *)\n#pub fun {PREFIX}_image_of {{{PREFIX}_value:{SORT}}} ({PREFIX}: !{VALUE}({PREFIX}_value)): {PREFIX}_image({PREFIX}_value)\n")
emit(f"implement {PREFIX}_image_of {{{PREFIX}_value}} ({PREFIX}) =\n  case+ {PREFIX} of\n  | {CAPITAL}V({pattern('field')}) => let")
for name, kind in fields:
    if kind == "i":
        emit(f"      val number_{name} = int32_copy(field_{name})")
    else:
        emit(f"      val text_{name} = bstr_of_blist(field_{name})")
image_args = ", ".join(f"number_{name}" if kind == "i" else f"text_{name}" for name, kind in fields)
emit(f"    in {CAPITAL}Image({image_args}) end\n")

emit(f"(* The {PREFIX} an image holds *)\n#pub fun {PREFIX}_of_image {{{PREFIX}_value:{SORT}}} (image: !{PREFIX}_image({PREFIX}_value)): {VALUE}({PREFIX}_value)\n")
emit(f"implement {PREFIX}_of_image {{{PREFIX}_value}} (image) =\n  case+ image of\n  | {CAPITAL}Image({pattern('image')}) => let")
for name, kind in fields:
    if kind == "i":
        emit(f"      val number_{name} = int32_copy(image_{name})")
    else:
        emit(f"      val list_{name} = blist_of_bstr(image_{name})")
value_args = ", ".join(f"number_{name}" if kind == "i" else f"list_{name}" for name, kind in fields)
emit(f"    in {CAPITAL}V({value_args}) end\n")

# record level
emit(f"(* The image of a stored {PREFIX}, as read *)\n#pub fun {PREFIX}_record_image {{{PREFIX}_value:{SORT}}}{{format_version,least_version:int}}{{kept_extras:extras}} (record: !{RECORD}({PREFIX}_value, format_version, least_version, kept_extras)): {PREFIX}_image({PREFIX}_value)\n")
emit(f"implement {PREFIX}_record_image {{{PREFIX}_value}}{{format_version,least_version}}{{kept_extras}} (record) =\n  case+ record of {CAPITAL}Record(_, _, {PREFIX}, _) => {PREFIX}_image_of({PREFIX})\n")
emit(f"(* A new record of an image: the format version this Quire writes, and no chunks kept. It holds the very {PREFIX} the image does. *)\n#pub fun {PREFIX}_record_new {{{PREFIX}_value:{SORT}}} (image: !{PREFIX}_image({PREFIX}_value)): {RECORD}({PREFIX}_value, 1, 1, ex_nil())\n")
emit(f"implement {PREFIX}_record_new {{{PREFIX}_value}} (image) = {CAPITAL}Record(1, 1, {PREFIX}_of_image(image), EXV_nil())\n")
emit(f"fn {PREFIX}_free_book {{{PREFIX}_value:{SORT}}} ({PREFIX}: {VALUE}({PREFIX}_value)): void =\n  case+ {PREFIX} of\n  | ~{CAPITAL}V({pattern('field')}) => let")
for name, kind in fields:
    emit(f"      val () = {'int32_free' if kind == 'i' else 'blist_free'}(field_{name})")
emit("    in () end\n")
emit(f"(* A record freed *)\n#pub fun {PREFIX}_record_free {{{PREFIX}_value:{SORT}}}{{format_version,least_version:int}}{{kept_extras:extras}} (record: {RECORD}({PREFIX}_value, format_version, least_version, kept_extras)): void\n")
emit(f"implement {PREFIX}_record_free {{{PREFIX}_value}}{{format_version,least_version}}{{kept_extras}} (record) =\n  case+ record of\n  | ~{CAPITAL}Record(_, _, {PREFIX}, extras) => let\n      val () = {PREFIX}_free_book({PREFIX})\n    in extrasv_free(extras) end\n")
# patch
emit("""(* The number of the record, or the image's *)
fn _pick_number {kept_number,other_number:int} (take: bool, kept: int32v(kept_number), other: !int32v(other_number)): [picked_number:int] int32v(picked_number) =
  if take then let val () = int32_free(kept) in int32_copy(other) end else kept

(* The bytes of the record, or those the image's array holds *)
fn _pick_text {kept_octets,other_octets:bytes}{kept_len:nat | kept_len < 256} (take: bool, kept: blist(kept_octets, kept_len), other: !bstr(other_octets)): [picked_octets:bytes][picked_len:nat | picked_len < 256] blist(picked_octets, picked_len) =
  if take then let val () = blist_free(kept) in blist_of_bstr(other) end else kept
""")
emit(f"(* The record with the groups in the mask taken from the image, and the others as they are *)")
emit(f"#pub fun {PREFIX}_record_patch {{record_value,image_value:{SORT}}}{{format_version,least_version:int}}{{kept_extras:extras}} (record: {RECORD}(record_value, format_version, least_version, kept_extras), image: !{PREFIX}_image(image_value), mask: int)\n  : [patched_value:{SORT}] {RECORD}(patched_value, format_version, least_version, kept_extras)\n")
emit(f"implement {PREFIX}_record_patch {{record_value,image_value}}{{format_version,least_version}}{{kept_extras}} (record, image, mask) =\n  case+ record of\n  | ~{CAPITAL}Record(format_version, least_version, {PREFIX}, extras) =>\n    (case+ {PREFIX} of\n     | ~{CAPITAL}V({pattern('field')}) =>\n       (case+ image of\n        | {CAPITAL}Image({pattern('image')}) => let")
for group in GROUPS:
    emit(f"            val take_{group[0].lower()} = $AR.band_int_int(mask, {bits[group[0]]}) <> 0")
for group in GROUPS:
    for name, kind in group[2]:
        take = f"take_{group[0].lower()}"
        if kind == "i":
            emit(f"            val chosen_{name} = _pick_number({take}, field_{name}, image_{name})")
        else:
            emit(f"            val chosen_{name} = _pick_text({take}, field_{name}, image_{name})")
chosen_args = ", ".join(f"chosen_{name}" for name, _ in fields)
emit(f"          in {CAPITAL}Record(format_version, least_version, {CAPITAL}V({chosen_args}), extras) end))\n")

# make from plain data
strs_decl = ", ".join(f"{name}: $A.arr(byte, {name}_loc, {name}_len + 1), {name}_len: int {name}_len" for name in strs)
quant_loc = ",".join(f"{name}_loc" for name in strs)
quant_len = ",".join(f"{name}_len" for name in strs)
len_bounds = "; ".join(f"{name}_len < 256" for name in strs)
emit(f"(* An image of numbers and strings (each in an array one longer than the string, which it takes), or none when a number is not one of 32 bits *)")
emit(f"#pub fun {PREFIX}_image_make {{{quant_loc}:agz}}{{{quant_len}:nat | {len_bounds}}}\n  (numbers: {PREFIX}_numbers, {strs_decl}): [{PREFIX}_value:{SORT}] {PREFIX}_imaged({PREFIX}_value)\n")
emit(f"implement {PREFIX}_image_make (numbers, {', '.join(name + ', ' + name + '_len' for name in strs)}) = let")


def free_arrays(indent):
    for name in strs:
        emit(f"{indent}val () = $A.free<byte>({name})")


def free_numbers(indent, upto):
    for name in ints[:upto]:
        emit(f"{indent}val () = int32_free(number_{name})")


emit("in")
for index, name in enumerate(ints):
    indent = "  " + "  " * index
    emit(f"{indent}case+ int32_make(numbers.{name}) of")
    emit(f"{indent}| ~I32_unrepresentable() => let")
    free_numbers(indent + "    ", index)
    free_arrays(indent + "    ")
    emit(f"{indent}  in {CAPITAL}NotImaged() end")
    emit(f"{indent}| ~I32_made(number_{name}) =>")
indent = "  " + "  " * len(ints)
emit(f"{indent}let")
for name in strs:
    emit(f"{indent}  val text_{name} = bstr_of_array({name}, {name}_len)")
    emit(f"{indent}  val () = $A.free<byte>({name})")
make_args = ", ".join(f"number_{name}" if kind == "i" else f"text_{name}" for name, kind in fields)
emit(f"{indent}in {CAPITAL}Imaged({CAPITAL}Image({make_args})) end")
emit("end\n")
# round trip
emit(f"""(* An image written as a record and read back: an image of the very {PREFIX}. That the bytes read are
   those written is the checked part (a {PREFIX} written is read back, whatever bytes they are);
   the image comes out of the record read, not out of the one written. *)
#pub fun {PREFIX}_image_roundtrip {{{PREFIX}_value:{SORT}}} (image: !{PREFIX}_image({PREFIX}_value)): {PREFIX}_image({PREFIX}_value)

implement {PREFIX}_image_roundtrip {{{PREFIX}_value}} (image) = let
  val record = {PREFIX}_record_new(image)
  val (written | list) = {PREFIX}_record_write(record)
  val () = {PREFIX}_record_free(record)
  val (whole | byte_count) = blist_len(list)
  val (read_proof | read) = {PREFIX}_record_read(list)
  prval same = {PREFIX}_enc_dec(whole, written, read_proof)
  val checked = {PREFIX}_read_recast(same | read)
in
  case+ checked of
  | ~{RESULT_PREFIX}_ok(record_read) => let
      val back = {PREFIX}_record_image(record_read)
      val () = {PREFIX}_record_free(record_read)
    in back end
end
""")
emit("end")
open(f"src/{PREFIX}image.bats", "w").write("\n".join(lines) + "\n")
