(* A failure's next step with StorageFull left out: a banner for it
   would say what happened and nothing to do about it (#360) *)
fn _static_remedy (failed: failure): remedy =
  case+ failed of
  | PartNotRead() => ImportAgain()
  | LibraryNotAdded() => ReopenQuire()
  | HandedBookNotAdded() => ReopenQuire()
  | SettingsNotRead() => ReopenQuire()
  | CataloguesNotRead() => ReopenQuire()
  | DictionariesNotRead() => ReopenQuire()
  | AnnotationsNotRead() => ReopenQuire()
  | BookFileLost() => ReopenQuire()
  | BookStorageFailed() => ReopenQuire()
  | RecordFromNewerQuire() => ReopenQuire()
  | RecordDamaged() => ReopenQuire()
  | RecordNotQuires() => ReopenQuire()
  | BooksNotRead() => ReopenQuire()
  | DetailsDamaged() => ReopenQuire()
  | CollectionsNotRead() => ReopenQuire()
  | NarrationNotPlayable() => ReopenQuire()
  | RotationNotLockable() => ReopenQuire()
  | GrantNotTaken() => ReopenQuire()
  | GrantNoAnswer() => ReopenQuire()
  | TextNotCopied() => ReopenQuire()
  | DetailsNotCopied() => ReopenQuire()
  | BooksNotReadCanSetAside() => ReopenQuire()
  | CollectionsNotReadCanSetAside() => ReopenQuire()
  | AsideNotRead() => ReopenQuire()
  | AsideIncomplete() => ReopenQuire()
