(* app -- the app's elements, made once at startup *)

#target wasm begin

#include "share/atspre_staload.hats"
#use array as A

staload "ui.sats"
staload "style.sats"

fn _hide {ni:pos | ni < 256} (id: string ni): void = ui_show(id, false)

(* The library view: toolbar, error banner, import progress, the list of
   books and the empty-library message *)
fn _library (): void = let
  val () = ui_el("bats-root", "qllc", TDiv, "lib")
  val () = ui_role("qllc", RMain)
  val () = ui_el("qllc", "qltb", TDiv, "bar")
  val () = ui_el("qltb", "qatl", TH1, "ttl")
  val () = ui_text("qatl", "Quire")
  val () = ui_text_btn("qltb", "qshf", "btn", "Library")
  val () = ui_text_btn("qltb", "qsrt", "btn", "Sort: Last opened")
  val () = ui_el("qltb", "qibn", TDiv, "btn btn-p")
  val () = ui_file_input("qibn", "qfin", "Import EPUB", ".epub,application/epub+zip", true)
  val () = ui_icon_btn("qltb", "qlgr", "ibtn", IcGear, "Library menu")
  val () = ui_el("qltb", "qlsb", TDiv, "sfield")
  val () = ui_field("qlsb", "qlsq", FSearch, "search", "Search the library")
  val () = ui_icon_btn("qlsb", "qlsx", "ibtn sclear", IcClose, "Clear search")
  val () = _hide("qlsx")
  (* error banner *)
  val () = ui_el("qllc", "qerr", TDiv, "banner")
  val () = ui_role("qerr", RAlert)
  val () = ui_add("qerr", "qert", TSpan)
  val () = ui_icon_btn("qerr", "qerx", "ibtn", IcClose, "Dismiss")
  val () = _hide("qerr")
  (* import progress *)
  val () = ui_el("qllc", "qimp", TDiv, "imp")
  val () = ui_role("qimp", RStatus)
  val () = ui_el("qimp", "qimn", TDiv, "imp-n")
  val () = ui_el("qimp", "qims", TDiv, "imp-s")
  val () = ui_el("qimp", "qimb", TDiv, "imp-bar")
  val () = ui_el("qimb", "qimf", TDiv, "imp-fill")
  val () = _hide("qimp")
  (* the books *)
  val () = ui_el("qllc", "qlst", TDiv, "list")
  val () = ui_named("qlst", NRegion, "Books")
  val () = ui_el("qllc", "qelb", TDiv, "empty")
in ui_text("qelb", "Import an EPUB file to start reading.") end

(* The book menu (its More button, a right-click or a long press on a
   card) *)
fn _context_menu (): void = let
  val () = ui_el("bats-root", "qctx", TDiv, "ovl")
  val () = ui_el("qctx", "qcmb", TDiv, "menu")
  val () = ui_named("qcmb", NMenu, "Book menu")
  val () = ui_menuitem("qcmb", "qcmi", "Book info", Plain)
  val () = ui_menuitem("qcmb", "qcmh", "Hide", Plain)
  val () = ui_menuitem("qcmb", "qcma", "Archive", Plain)
  val () = ui_menuitem("qcmb", "qcmd", "Delete", Danger)
in _hide("qctx") end

(* The library menu (the gear) *)
fn _library_menu (): void = let
  val () = ui_el("bats-root", "qlmn", TDiv, "ovl")
  val () = ui_el("qlmn", "qlmb", TDiv, "menu")
  val () = ui_named("qlmb", NMenu, "Library menu")
  val () = ui_menuitem("qlmb", "qlme", "Export backup", Plain)
  val () = ui_el("qlmb", "qlmi", TDiv, "mi btn")
  val () = ui_file_input("qlmi", "qbfi", "Import backup", ".json,application/json", false)
  val () = ui_menuitem("qlmb", "qlmr", "Factory reset", Danger)
  val () = ui_menuitem("qlmb", "qlmc", "Close", Plain)
in _hide("qlmn") end

(* The dialog: its buttons' labels and tones are set when it opens *)
fn _modal (): void = let
  val () = ui_el("bats-root", "qmod", TDiv, "ovl")
  val () = ui_el("qmod", "qmbx", TDiv, "mbox")
  val () = ui_labelled("qmbx", NModal, "qmtt")
  val () = ui_el("qmbx", "qmtt", TDiv, "mtitle")
  val () = ui_add("qmbx", "qmtx", TDiv)
  val () = ui_field("qmbx", "qmta", FText, "mta", "Note")
  val () = _hide("qmta")
  val () = ui_el("qmbx", "qmbs", TDiv, "mbtns")
  val () = ui_text_btn("qmbs", "qmb1", "btn", "-")
  val () = ui_text_btn("qmbs", "qmb2", "btn btn-p", "-")
in _hide("qmod") end

(* A labelled row of the book info view *)
fn _row {nr,nv:pos | nr < 256; nv < 256}{nl:pos | nl < 256} (rid: string nr, vid: string nv, label: string nl): void = let
  val () = ui_el("qinn", rid, TDiv, "irow")
  val () = ui_add(rid, vid, TSpan)
  val () = ui_text(vid, label)
in end

(* The book info view *)
fn _info (): void = let
  val () = ui_el("bats-root", "qinf", TDiv, "info")
  val () = ui_named("qinf", NDialog, "Book info")
  val () = ui_el("qinf", "qinn", TDiv, "info-in")
  val () = ui_text_btn("qinn", "qinx", "btn", "\xE2\x86\x90 Library")
  val () = ui_img("qinn", "qinc", "icov")
  val () = ui_el("qinn", "qint", TDiv, "it")
  val () = ui_el("qinn", "qina", TDiv, "ba")
  val () = _row("qirp", "qilp", "Progress")
  val () = ui_add("qirp", "qivp", TB)
  val () = _row("qira", "qila", "Added")
  val () = ui_add("qira", "qiva", TB)
  val () = _row("qirl", "qill", "Last read")
  val () = ui_add("qirl", "qivl", TB)
  val () = _row("qirs", "qils", "Size")
  val () = ui_add("qirs", "qivs", TB)
  val () = ui_el("qinn", "qinb", TDiv, "mbtns")
  val () = ui_text_btn("qinb", "qinh", "btn", "Hide")
  val () = ui_text_btn("qinb", "qinr", "btn", "Archive")
  val () = ui_text_btn("qinb", "qind", "btn danger", "Delete")
in _hide("qinf") end

(* The reader: its bars, the content, the scrubber, the selection
   toolbar and the back-after-a-jump button *)
fn _reader (): void = let
  val () = ui_el("bats-root", "qrvw", TDiv, "rv")
  val () = ui_role("qrvw", RMain)
  val () = ui_el("qrvw", "qrnv", TDiv, "top")
  val () = ui_named("qrnv", NNavigation, "Book")
  val () = ui_icon_btn("qrnv", "qbbk", "ibtn", IcBack, "Back to library")
  val () = ui_el("qrnv", "qcht", TDiv, "ctitle")
  val () = ui_role("qcht", RHeading)
  val () = ui_icon_btn("qrnv", "qbmk", "ibtn", IcStar, "Bookmark this page")
  val () = ui_attr("qbmk", APressed, "false")
  val () = ui_icon_btn("qrnv", "qsch", "ibtn", IcSearch, "Search in book")
  val () = ui_el("qrvw", "qcnt", TDiv, "caf")
  val () = ui_attr("qcnt", ATabindex, "0")
  val () = ui_named("qcnt", NDocument, "Page")
  val () = ui_text_btn("qrvw", "qpbk", "pback", "\xE2\x86\xA9 Back")
  val () = _hide("qpbk")
  val () = ui_el("qrvw", "qsel", TDiv, "seltb")
  val () = ui_named("qsel", NToolbar, "Selection")
  val () = ui_text_btn("qsel", "qslh", "btn", "Highlight")
  val () = ui_text_btn("qsel", "qsln", "btn", "Note")
  val () = ui_text_btn("qsel", "qslc", "btn", "Copy")
  val () = ui_text_btn("qsel", "qsls", "btn", "Search")
  val () = _hide("qsel")
  val () = ui_el("qrvw", "qrbb", TDiv, "bot")
  val () = ui_named("qrbb", NToolbar, "Page controls")
  val () = ui_icon_btn("qrbb", "qprv", "ibtn", IcPrev, "Previous page")
  val () = ui_icon_btn("qrbb", "qtcb", "ibtn", IcContents, "Contents")
  val () = ui_icon_btn("qrbb", "qset", "ibtn", IcFont, "Typography")
  val () = ui_icon_btn("qrbb", "qanb", "ibtn", IcNotes, "Annotations")
  val () = ui_el("qrbb", "qpgi", TDiv, "pinfo")
  val () = ui_named("qpgi", NStatus, "Page")
  val () = ui_icon_btn("qrbb", "qnxt", "ibtn", IcNext, "Next page")
  (* scrubber *)
  val () = ui_el("qrbb", "qscr", TDiv, "scr")
  val () = ui_el("qscr", "qtrk", TDiv, "trk")
  val () = ui_named("qtrk", NSlider, "Place in book")
  val () = ui_el("qtrk", "qtkl", TDiv, "trk-l")
  val () = ui_el("qtrk", "qtkf", TDiv, "trk-f")
  val () = ui_add("qtrk", "qstk", TDiv)
  val () = ui_el("qtrk", "qsth", TDiv, "thumb")
  val () = ui_el("qtrk", "qstt", TDiv, "tip")
  val () = ui_role("qstt", RTooltip)
  val () = _hide("qstt")
  val () = ui_el("qscr", "qpct", TDiv, "pct")
in _hide("qrvw") end

(* The contents panel: the book's table of contents and its bookmarks *)
fn _toc (): void = let
  val () = ui_el("bats-root", "qtoc", TDiv, "panel")
  val () = ui_named("qtoc", NDialog, "Contents")
  val () = ui_el("qtoc", "qtch", TDiv, "ph")
  val () = ui_el("qtch", "qtcs", TSpan, "tabs")
  val () = ui_named("qtcs", NTablist, "Contents and bookmarks")
  val () = ui_tab("qtcs", "qtct", "Contents", "qtcl", true)
  val () = ui_tab("qtcs", "qtcm", "Bookmarks", "qtbl", false)
  val () = ui_el("qtch", "qtcg", TSpan, "grow")
  val () = ui_icon_btn("qtch", "qtcx", "ibtn", IcClose, "Close")
  val () = ui_el("qtoc", "qtcl", TDiv, "plist")
  val () = ui_labelled("qtcl", NTabpanel, "qtct")
  val () = ui_el("qtoc", "qtbl", TDiv, "plist")
  val () = ui_labelled("qtbl", NTabpanel, "qtcm")
  val () = _hide("qtbl")
in _hide("qtoc") end

(* The settings sheet *)
fn _settings (): void = let
  val () = ui_el("bats-root", "qspn", TDiv, "sheet")
  val () = ui_named("qspn", NDialog, "Typography and theme")
  val () = ui_el("qspn", "qsrf", TDiv, "srow")
  val () = ui_el("qsrf", "qslf", TSpan, "slabel")
  val () = ui_text("qslf", "Font")
  val () = ui_el("qsrf", "qsgf", TDiv, "seg")
  val () = ui_text_btn("qsgf", "qff0", "sbtn", "Literata")
  val () = ui_text_btn("qsgf", "qff1", "sbtn", "Inter")
  val () = ui_text_btn("qsgf", "qff2", "sbtn", "Book")
  (* the sliders' rows: their sliders are made at the settings'
     values (set_sliders) *)
  val () = ui_el("qspn", "qsr1", TDiv, "srow")
  val () = ui_el("qspn", "qsr2", TDiv, "srow")
  val () = ui_el("qspn", "qsr3", TDiv, "srow")
  val () = ui_el("qspn", "qsrt2", TDiv, "srow")
  val () = ui_el("qsrt2", "qslt", TSpan, "slabel")
  val () = ui_text("qslt", "Theme")
  val () = ui_el("qsrt2", "qsgt", TDiv, "seg")
  val () = ui_text_btn("qsgt", "qth0", "sbtn", "Auto")
  val () = ui_text_btn("qsgt", "qth1", "sbtn", "Light")
  val () = ui_text_btn("qsgt", "qth2", "sbtn", "Sepia")
  val () = ui_text_btn("qsgt", "qth3", "sbtn", "Dark")
  (* reset, away from Close and asked first *)
  val () = ui_el("qspn", "qsrb", TDiv, "srow sfoot")
  val () = ui_text_btn("qsrb", "qsrs", "link", "Reset to defaults")
  val () = ui_el("qsrb", "qsrg", TSpan, "grow")
  val () = ui_text_btn("qsrb", "qscl", "btn", "Close")
in _hide("qspn") end

(* The search panel *)
fn _search (): void = let
  val () = ui_el("bats-root", "qsrp", TDiv, "panel panel-r")
  val () = ui_named("qsrp", NDialog, "Search in book")
  val () = ui_el("qsrp", "qsrh", TDiv, "sbar")
  val () = ui_field("qsrh", "qsri", FSearch, "search", "Search in book")
  val () = ui_icon_btn("qsrh", "qsrx", "ibtn", IcClose, "Close search")
  val () = ui_el("qsrp", "qsrm", TDiv, "snav")
  val () = ui_role("qsrm", RStatus)
  val () = ui_el("qsrp", "qsrl", TDiv, "plist")
  val () = ui_named("qsrl", NRegion, "Results")
  (* the results' bar, over the page once one is opened *)
  val () = ui_el("qrvw", "qsrn", TDiv, "snavf")
  val () = ui_named("qsrn", NToolbar, "Search results")
  val () = ui_icon_btn("qsrn", "qsrv", "ibtn", IcPrev, "Previous result")
  val () = ui_add("qsrn", "qsrc", TSpan)
  val () = ui_role("qsrc", RStatus)
  val () = ui_icon_btn("qsrn", "qsrw", "ibtn", IcNext, "Next result")
  val () = ui_icon_btn("qsrn", "qsrz", "ibtn", IcClose, "Close search")
  val () = _hide("qsrn")
in _hide("qsrp") end

(* The annotations panel *)
fn _annotations (): void = let
  val () = ui_el("bats-root", "qanp", TDiv, "panel panel-r")
  val () = ui_named("qanp", NDialog, "Annotations")
  val () = ui_el("qanp", "qanh", TDiv, "ph")
  val () = ui_el("qanh", "qang", TSpan, "grow")
  val () = ui_text("qang", "Annotations")
  val () = ui_text_btn("qanh", "qanx", "btn", "Export")
  val () = ui_icon_btn("qanh", "qanc", "ibtn", IcClose, "Close")
  val () = ui_el("qanp", "qanl", TDiv, "plist")
in _hide("qanp") end

(* Makes every element of the app, in the root element bats-root *)
#pub fn app_build (): void

implement app_build () = let
  (* the page's loading screen goes *)
  val () = ui_clear("bats-root")
  val () = ui_class("bats-root", "app th-light")
  val () = ui_add("bats-root", "qcss", TStyle)
  val @(css, cssn) = app_style()
  val () = ui_text_buf("qcss", css, cssn)
  val () = ui_add("bats-root", "qdyn", TStyle)
  val () = ui_add("bats-root", "qfnt", TStyle)
  val () = _library()
  val () = _context_menu()
  val () = _library_menu()
  val () = _info()
  val () = _reader()
  val () = _toc()
  val () = _settings()
  val () = _search()
  val () = _annotations()
in _modal() end

end (* #target wasm *)
