(* app -- the app's elements, made once at startup *)

#target wasm begin

#include "share/atspre_staload.hats"
#use array as A

staload "ui.sats"
staload "theme.sats"

fn _hide {ni:pos | ni < 256} (id: string ni): void = ui_show(id, false)

(* The library view: toolbar, error banner, import progress, the list of
   books and the empty-library message *)
fn _library (): void = let
  val () = ui_el("bats-root", "qllc", "div", "lib")
  val () = ui_attr("qllc", "role", "main")
  val () = ui_el("qllc", "qltb", "div", "bar")
  val () = ui_el("qltb", "qatl", "h1", "ttl")
  val () = ui_text("qatl", "Quire")
  val () = ui_btn("qltb", "qshf", "btn", "Library")
  val () = ui_attr("qshf", "aria-label", "Shelf shown")
  val () = ui_btn("qltb", "qsrt", "btn", "Sort: Last opened")
  val () = ui_el("qltb", "qibn", "div", "btn btn-p")
  val () = ui_file_input("qibn", "qfin", "Import EPUB", ".epub,application/epub+zip", "Import EPUB", true)
  val () = ui_btn("qltb", "qlgr", "ibtn", "\xE2\x9A\x99")
  val () = ui_attr("qlgr", "aria-label", "Library menu")
  val () = ui_el("qltb", "qlsq", "input", "search")
  val () = ui_attr("qlsq", "type", "search")
  val () = ui_attr("qlsq", "placeholder", "Search title or author")
  val () = ui_attr("qlsq", "aria-label", "Search the library")
  (* error banner *)
  val () = ui_el("qllc", "qerr", "div", "banner")
  val () = ui_attr("qerr", "role", "alert")
  val () = ui_add("qerr", "qert", "span")
  val () = ui_btn("qerr", "qerx", "ibtn", "\xE2\x9C\x95")
  val () = ui_attr("qerx", "aria-label", "Dismiss")
  val () = _hide("qerr")
  (* import progress *)
  val () = ui_el("qllc", "qimp", "div", "imp")
  val () = ui_attr("qimp", "role", "status")
  val () = ui_el("qimp", "qimn", "div", "imp-n")
  val () = ui_el("qimp", "qims", "div", "imp-s")
  val () = ui_el("qimp", "qimb", "div", "imp-bar")
  val () = ui_el("qimb", "qimf", "div", "imp-fill")
  val () = _hide("qimp")
  (* the books *)
  val () = ui_el("qllc", "qlst", "div", "list")
  val () = ui_attr("qlst", "role", "region")
  val () = ui_attr("qlst", "aria-label", "Books")
  val () = ui_el("qllc", "qelb", "div", "empty")
in ui_text("qelb", "Import an EPUB file to start reading ...") end

(* The book menu (right-click or long-press on a card) *)
fn _context_menu (): void = let
  val () = ui_el("bats-root", "qctx", "div", "ovl")
  val () = ui_el("qctx", "qcmb", "div", "menu")
  val () = ui_attr("qcmb", "role", "menu")
  val () = ui_btn("qcmb", "qcmi", "mi", "Book info")
  val () = ui_btn("qcmb", "qcmh", "mi", "Hide")
  val () = ui_btn("qcmb", "qcma", "mi", "Archive")
  val () = ui_btn("qcmb", "qcmd", "mi", "Delete")
in _hide("qctx") end

(* The library menu (the gear) *)
fn _library_menu (): void = let
  val () = ui_el("bats-root", "qlmn", "div", "ovl")
  val () = ui_el("qlmn", "qlmb", "div", "menu")
  val () = ui_attr("qlmb", "role", "menu")
  val () = ui_btn("qlmb", "qlme", "mi", "Export backup")
  val () = ui_el("qlmb", "qlmi", "div", "mi btn")
  val () = ui_file_input("qlmi", "qbfi", "Import backup", ".json,application/json", "Import backup", false)
  val () = ui_btn("qlmb", "qlmr", "mi", "Factory reset")
  val () = ui_btn("qlmb", "qlmc", "mi", "Close")
in _hide("qlmn") end

(* The dialog *)
fn _modal (): void = let
  val () = ui_el("bats-root", "qmod", "div", "ovl")
  val () = ui_el("qmod", "qmbx", "div", "mbox")
  val () = ui_attr("qmbx", "role", "dialog")
  val () = ui_attr("qmbx", "aria-modal", "true")
  val () = ui_attr("qmbx", "aria-labelledby", "qmtt")
  val () = ui_el("qmbx", "qmtt", "div", "mtitle")
  val () = ui_add("qmbx", "qmtx", "div")
  val () = ui_el("qmbx", "qmta", "textarea", "mta")
  val () = ui_attr("qmta", "aria-label", "Note")
  val () = _hide("qmta")
  val () = ui_el("qmbx", "qmbs", "div", "mbtns")
  val () = ui_btn("qmbs", "qmb3", "btn", "-")
  val () = ui_btn("qmbs", "qmb1", "btn", "-")
  val () = ui_btn("qmbs", "qmb2", "btn btn-p", "-")
in _hide("qmod") end

(* A labelled row of the book info view *)
fn _row {nr,nv:pos | nr < 256; nv < 256}{nl:pos | nl < 256} (rid: string nr, vid: string nv, label: string nl): void = let
  val () = ui_el("qinn", rid, "div", "irow")
  val () = ui_add(rid, vid, "span")
  val () = ui_text(vid, label)
in end

(* The book info view *)
fn _info (): void = let
  val () = ui_el("bats-root", "qinf", "div", "info")
  val () = ui_attr("qinf", "role", "dialog")
  val () = ui_attr("qinf", "aria-label", "Book info")
  val () = ui_el("qinf", "qinn", "div", "info-in")
  val () = ui_btn("qinn", "qinx", "btn", "\xE2\x86\x90 Library")
  val () = ui_el("qinn", "qinc", "img", "icov")
  val () = ui_attr("qinc", "alt", "cover")
  val () = ui_el("qinn", "qint", "div", "it")
  val () = ui_el("qinn", "qina", "div", "ba")
  val () = _row("qirp", "qilp", "Progress")
  val () = ui_add("qirp", "qivp", "b")
  val () = _row("qira", "qila", "Added")
  val () = ui_add("qira", "qiva", "b")
  val () = _row("qirl", "qill", "Last read")
  val () = ui_add("qirl", "qivl", "b")
  val () = _row("qirs", "qils", "Size")
  val () = ui_add("qirs", "qivs", "b")
  val () = ui_el("qinn", "qinb", "div", "mbtns")
  val () = ui_btn("qinb", "qinh", "btn", "Hide")
  val () = ui_btn("qinb", "qinr", "btn", "Archive")
  val () = ui_btn("qinb", "qind", "btn", "Delete")
in _hide("qinf") end

(* The reader: its bars, the content, the scrubber, the selection
   toolbar and the back-after-a-jump button *)
fn _reader (): void = let
  val () = ui_el("bats-root", "qrvw", "div", "rv")
  val () = ui_attr("qrvw", "role", "main")
  val () = ui_el("qrvw", "qrnv", "div", "top")
  val () = ui_attr("qrnv", "role", "navigation")
  val () = ui_attr("qrnv", "aria-label", "Book")
  val () = ui_btn("qrnv", "qbbk", "ibtn", "\xE2\x86\x90")
  val () = ui_attr("qbbk", "aria-label", "Back to library")
  val () = ui_el("qrnv", "qcht", "div", "ctitle")
  val () = ui_btn("qrnv", "qbmk", "ibtn", "\xE2\x98\x86")
  val () = ui_attr("qbmk", "aria-label", "Bookmark this page")
  val () = ui_attr("qbmk", "aria-pressed", "false")
  val () = ui_btn("qrnv", "qsch", "ibtn", "\xF0\x9F\x94\x8D")
  val () = ui_attr("qsch", "aria-label", "Search in book")
  val () = ui_el("qrvw", "qcnt", "div", "caf")
  val () = ui_attr("qcnt", "tabindex", "0")
  val () = ui_attr("qcnt", "role", "document")
  val () = ui_attr("qcnt", "aria-label", "Page")
  val () = ui_btn("qrvw", "qpbk", "pback", "\xE2\x86\xA9 Back")
  val () = _hide("qpbk")
  val () = ui_el("qrvw", "qsel", "div", "seltb")
  val () = ui_attr("qsel", "role", "toolbar")
  val () = ui_btn("qsel", "qslh", "btn", "Highlight")
  val () = ui_btn("qsel", "qsln", "btn", "Note")
  val () = ui_btn("qsel", "qslc", "btn", "Copy")
  val () = ui_btn("qsel", "qsls", "btn", "Search")
  val () = _hide("qsel")
  val () = ui_el("qrvw", "qrbb", "div", "bot")
  val () = ui_attr("qrbb", "role", "toolbar")
  val () = ui_btn("qrbb", "qprv", "ibtn", "\xE2\x80\xB9")
  val () = ui_attr("qprv", "aria-label", "Previous page")
  val () = ui_btn("qrbb", "qtcb", "ibtn", "\xE2\x98\xB0")
  val () = ui_attr("qtcb", "aria-label", "Contents")
  val () = ui_btn("qrbb", "qset", "ibtn", "Aa")
  val () = ui_attr("qset", "aria-label", "Typography")
  val () = ui_btn("qrbb", "qanb", "ibtn", "\xE2\x8B\xAF")
  val () = ui_attr("qanb", "aria-label", "Annotations")
  val () = ui_el("qrbb", "qpgi", "div", "pinfo")
  val () = ui_attr("qpgi", "aria-live", "polite")
  val () = ui_btn("qrbb", "qnxt", "ibtn", "\xE2\x80\xBA")
  val () = ui_attr("qnxt", "aria-label", "Next page")
  (* scrubber *)
  val () = ui_el("qrbb", "qscr", "div", "scr")
  val () = ui_el("qscr", "qtrk", "div", "trk")
  val () = ui_attr("qtrk", "role", "slider")
  val () = ui_attr("qtrk", "aria-label", "Page in chapter")
  val () = ui_el("qtrk", "qtkl", "div", "trk-l")
  val () = ui_el("qtrk", "qtkf", "div", "trk-f")
  val () = ui_add("qtrk", "qstk", "div")
  val () = ui_el("qtrk", "qsth", "div", "thumb")
  val () = ui_el("qtrk", "qstt", "div", "tip")
  val () = _hide("qstt")
  val () = ui_el("qscr", "qpct", "div", "pct")
in _hide("qrvw") end

(* The contents panel: the book's table of contents and its bookmarks *)
fn _toc (): void = let
  val () = ui_el("bats-root", "qtoc", "div", "panel")
  val () = ui_attr("qtoc", "role", "dialog")
  val () = ui_attr("qtoc", "aria-label", "Contents")
  val () = ui_el("qtoc", "qtch", "div", "ph")
  val () = ui_el("qtch", "qtcs", "span", "tabs")
  val () = ui_attr("qtcs", "role", "tablist")
  val () = ui_btn("qtcs", "qtct", "tab", "Contents")
  val () = ui_attr("qtct", "role", "tab")
  val () = ui_attr("qtct", "aria-controls", "qtcl")
  val () = ui_attr("qtct", "aria-selected", "true")
  val () = ui_btn("qtcs", "qtcm", "tab", "Bookmarks")
  val () = ui_attr("qtcm", "role", "tab")
  val () = ui_attr("qtcm", "aria-controls", "qtbl")
  val () = ui_attr("qtcm", "aria-selected", "false")
  val () = ui_el("qtch", "qtcg", "span", "grow")
  val () = ui_btn("qtch", "qtcx", "ibtn", "\xE2\x9C\x95")
  val () = ui_attr("qtcx", "aria-label", "Close")
  val () = ui_el("qtoc", "qtcl", "div", "plist")
  val () = ui_attr("qtcl", "role", "tabpanel")
  val () = ui_el("qtoc", "qtbl", "div", "plist")
  val () = ui_attr("qtbl", "role", "tabpanel")
  val () = _hide("qtbl")
in _hide("qtoc") end


(* The settings sheet *)
fn _settings (): void = let
  val () = ui_el("bats-root", "qspn", "div", "sheet")
  val () = ui_attr("qspn", "role", "dialog")
  val () = ui_attr("qspn", "aria-label", "Typography and theme")
  val () = ui_el("qspn", "qsrf", "div", "srow")
  val () = ui_el("qsrf", "qslf", "span", "slabel")
  val () = ui_text("qslf", "Font")
  val () = ui_el("qsrf", "qsgf", "div", "seg")
  val () = ui_btn("qsgf", "qff0", "sbtn", "Literata")
  val () = ui_btn("qsgf", "qff1", "sbtn", "Inter")
  val () = ui_btn("qsgf", "qff2", "sbtn", "Book")
  (* the sliders' rows: their sliders are made at the settings'
     values (set_sliders) *)
  val () = ui_el("qspn", "qsr1", "div", "srow")
  val () = ui_el("qspn", "qsr2", "div", "srow")
  val () = ui_el("qspn", "qsr3", "div", "srow")
  val () = ui_el("qspn", "qsrt2", "div", "srow")
  val () = ui_el("qsrt2", "qslt", "span", "slabel")
  val () = ui_text("qslt", "Theme")
  val () = ui_el("qsrt2", "qsgt", "div", "seg")
  val () = ui_btn("qsgt", "qth0", "sbtn", "Auto")
  val () = ui_btn("qsgt", "qth1", "sbtn", "Light")
  val () = ui_btn("qsgt", "qth2", "sbtn", "Sepia")
  val () = ui_btn("qsgt", "qth3", "sbtn", "Dark")
  val () = ui_el("qspn", "qsrb", "div", "srow")
  val () = ui_btn("qsrb", "qsrs", "link", "Reset to defaults")
  val () = ui_el("qsrb", "qsrg", "span", "grow")
  val () = ui_btn("qsrb", "qscl", "btn", "Close")
in _hide("qspn") end

(* The search panel *)
fn _search (): void = let
  val () = ui_el("bats-root", "qsrp", "div", "panel panel-r")
  val () = ui_attr("qsrp", "role", "dialog")
  val () = ui_attr("qsrp", "aria-label", "Search in book")
  val () = ui_el("qsrp", "qsrh", "div", "sbar")
  val () = ui_add("qsrh", "qsri", "input")
  val () = ui_attr("qsri", "type", "search")
  val () = ui_attr("qsri", "placeholder", "Search in book")
  val () = ui_attr("qsri", "aria-label", "Search in book")
  val () = ui_btn("qsrh", "qsrx", "ibtn", "\xE2\x9C\x95")
  val () = ui_attr("qsrx", "aria-label", "Close search")
  val () = ui_el("qsrp", "qsrm", "div", "snav")
  val () = ui_attr("qsrm", "aria-live", "polite")
  val () = ui_el("qsrp", "qsrl", "div", "plist")
  (* the results' bar, over the page once one is opened *)
  val () = ui_el("qrvw", "qsrn", "div", "snavf")
  val () = ui_attr("qsrn", "role", "toolbar")
  val () = ui_attr("qsrn", "aria-label", "Search results")
  val () = ui_btn("qsrn", "qsrv", "ibtn", "\xE2\x80\xB9")
  val () = ui_attr("qsrv", "aria-label", "Previous result")
  val () = ui_add("qsrn", "qsrc", "span")
  val () = ui_attr("qsrc", "aria-live", "polite")
  val () = ui_btn("qsrn", "qsrw", "ibtn", "\xE2\x80\xBA")
  val () = ui_attr("qsrw", "aria-label", "Next result")
  val () = ui_btn("qsrn", "qsrz", "ibtn", "\xE2\x9C\x95")
  val () = ui_attr("qsrz", "aria-label", "Close search")
  val () = _hide("qsrn")
in _hide("qsrp") end

(* The annotations panel *)
fn _annotations (): void = let
  val () = ui_el("bats-root", "qanp", "div", "panel panel-r")
  val () = ui_attr("qanp", "role", "dialog")
  val () = ui_attr("qanp", "aria-label", "Annotations")
  val () = ui_el("qanp", "qanh", "div", "ph")
  val () = ui_el("qanh", "qang", "span", "grow")
  val () = ui_text("qang", "Annotations")
  val () = ui_btn("qanh", "qanx", "btn", "Export")
  val () = ui_btn("qanh", "qanc", "ibtn", "\xE2\x9C\x95")
  val () = ui_attr("qanc", "aria-label", "Close")
  val () = ui_el("qanp", "qanl", "div", "plist")
in _hide("qanp") end

(* Makes every element of the app, in the root element bats-root *)
#pub fn app_build (): void

implement app_build () = let
  (* the page's loading screen goes *)
  val () = ui_clear("bats-root")
  val () = ui_attr("bats-root", "class", "app th-light")
  val () = ui_add("bats-root", "qcss", "style")
  val () = ui_text_long("qcss", app_css())
  val () = ui_add("bats-root", "qdyn", "style")
  val () = ui_add("bats-root", "qfnt", "style")
  val () = _library()
  val () = _context_menu()
  val () = _library_menu()
  val () = _info()
  val () = _reader()
  val () = _toc()
  val () = _settings()
  val () = _search()
  val () = _annotations()
in _modal() end

end (* #target wasm *)
