(* indeximage -- a stored index as values, indexed by the index they hold: what differs between two, and a record patched with it.
   Generated by scripts/gen-image.py index *)

#target wasm begin

#include "share/atspre_staload.hats"

#use array as A
#use arith as AR

staload "bytes.sats"
staload "fields.sats"
staload "schema.sats"
staload "record.sats"
staload "bytesarr.sats"
staload "indexrec.sats"

(* A stored index as values: each number as its four bytes, each string in an array that holds it.
   The index says which index it is. *)
#pub datavtype index_image(indexx) =
  | {legacy_size:int}{legacy_sum:int}{name_count:int}{name0:bytes}{name1:bytes}{name2:bytes}{name3:bytes}{name4:bytes}{name5:bytes}{name6:bytes}{name7:bytes}
    IndexImage(indexx_mk(legacy_size, legacy_sum, name_count, name0, name1, name2, name3, name4, name5, name6, name7)) of (int32v(legacy_size), int32v(legacy_sum), int32v(name_count), bstr(name0), bstr(name1), bstr(name2), bstr(name3), bstr(name4), bstr(name5), bstr(name6), bstr(name7))

(* The image of a index, or none: a string too long for an array *)
#pub datavtype index_imaged(indexx) =
  | {x:indexx} IndexImaged(x) of index_image(x)
  | {x:indexx} IndexNotImaged(x) of ()

(* The numbers of a stored index, by name *)
#pub typedef index_numbers = @{legacy_size = Int, legacy_sum = Int, name_count = Int}

#pub fun index_image_free {x:indexx} (image: index_image(x)): void

implement index_image_free {x} (image) =
  case+ image of
  | ~IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => let
      val () = int32_free(a_legacy_size)
      val () = int32_free(a_legacy_sum)
      val () = int32_free(a_name_count)
      val () = bstr_free(a_name0)
      val () = bstr_free(a_name1)
      val () = bstr_free(a_name2)
      val () = bstr_free(a_name3)
      val () = bstr_free(a_name4)
      val () = bstr_free(a_name5)
      val () = bstr_free(a_name6)
      val () = bstr_free(a_name7)
    in () end

#pub fun index_image_copy {x:indexx} (image: !index_image(x)): index_image(x)

implement index_image_copy {x} (image) =
  case+ image of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => let
      val c_legacy_size = int32_copy(a_legacy_size)
      val c_legacy_sum = int32_copy(a_legacy_sum)
      val c_name_count = int32_copy(a_name_count)
      val c_name0 = bstr_copy(a_name0)
      val c_name1 = bstr_copy(a_name1)
      val c_name2 = bstr_copy(a_name2)
      val c_name3 = bstr_copy(a_name3)
      val c_name4 = bstr_copy(a_name4)
      val c_name5 = bstr_copy(a_name5)
      val c_name6 = bstr_copy(a_name6)
      val c_name7 = bstr_copy(a_name7)
    in IndexImage(c_legacy_size, c_legacy_sum, c_name_count, c_name0, c_name1, c_name2, c_name3, c_name4, c_name5, c_name6, c_name7) end

(* The numbers of an image *)
#pub fun index_image_numbers {x:indexx} (image: !index_image(x)): index_numbers

implement index_image_numbers {x} (image) =
  case+ image of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => @{legacy_size = int32_value(a_legacy_size), legacy_sum = int32_value(a_legacy_sum), name_count = int32_value(a_name_count)}

(* A string of an image: its length, and a copy of its bytes in an array one longer *)
#pub fun index_image_name0 {x:indexx} (image: !index_image(x)): [l:agz][len:nat | len < 256] @($A.arr(byte, l, len + 1), int len)

implement index_image_name0 {x} (image) =
  case+ image of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => array_of_bstr(a_name0)

#pub fun index_image_name1 {x:indexx} (image: !index_image(x)): [l:agz][len:nat | len < 256] @($A.arr(byte, l, len + 1), int len)

implement index_image_name1 {x} (image) =
  case+ image of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => array_of_bstr(a_name1)

#pub fun index_image_name2 {x:indexx} (image: !index_image(x)): [l:agz][len:nat | len < 256] @($A.arr(byte, l, len + 1), int len)

implement index_image_name2 {x} (image) =
  case+ image of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => array_of_bstr(a_name2)

#pub fun index_image_name3 {x:indexx} (image: !index_image(x)): [l:agz][len:nat | len < 256] @($A.arr(byte, l, len + 1), int len)

implement index_image_name3 {x} (image) =
  case+ image of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => array_of_bstr(a_name3)

#pub fun index_image_name4 {x:indexx} (image: !index_image(x)): [l:agz][len:nat | len < 256] @($A.arr(byte, l, len + 1), int len)

implement index_image_name4 {x} (image) =
  case+ image of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => array_of_bstr(a_name4)

#pub fun index_image_name5 {x:indexx} (image: !index_image(x)): [l:agz][len:nat | len < 256] @($A.arr(byte, l, len + 1), int len)

implement index_image_name5 {x} (image) =
  case+ image of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => array_of_bstr(a_name5)

#pub fun index_image_name6 {x:indexx} (image: !index_image(x)): [l:agz][len:nat | len < 256] @($A.arr(byte, l, len + 1), int len)

implement index_image_name6 {x} (image) =
  case+ image of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => array_of_bstr(a_name6)

#pub fun index_image_name7 {x:indexx} (image: !index_image(x)): [l:agz][len:nat | len < 256] @($A.arr(byte, l, len + 1), int len)

implement index_image_name7 {x} (image) =
  case+ image of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => array_of_bstr(a_name7)

(* the bit of the group LEGA in a mask of groups *)
#pub fn index_group_lega (): int

implement index_group_lega () = 1

(* the bit of the group NAMS in a mask of groups *)
#pub fn index_group_nams (): int

implement index_group_nams () = 2

(* every group *)
#pub fn index_group_all (): int

implement index_group_all () = 3

(* The numbers of kept in the groups of keep_mask, and the others' of other *)
#pub fun index_numbers_merge (kept: index_numbers, other: index_numbers, keep_mask: int): index_numbers

implement index_numbers_merge (kept, other, keep_mask) = @{legacy_size = (if $AR.band_int_int(keep_mask, 1) <> 0 then kept.legacy_size else other.legacy_size), legacy_sum = (if $AR.band_int_int(keep_mask, 1) <> 0 then kept.legacy_sum else other.legacy_sum), name_count = (if $AR.band_int_int(keep_mask, 2) <> 0 then kept.name_count else other.name_count)}

(* The groups whose fields differ in two images, as a mask *)
#pub fun index_image_diff {x,y:indexx} (first: !index_image(x), second: !index_image(y)): int

implement index_image_diff {x,y} (first, second) =
  case+ first of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) =>
    (case+ second of
     | IndexImage(b_legacy_size, b_legacy_sum, b_name_count, b_name0, b_name1, b_name2, b_name3, b_name4, b_name5, b_name6, b_name7) => let
         val m_lega = (if (int32_value(a_legacy_size) <> int32_value(b_legacy_size)) || (int32_value(a_legacy_sum) <> int32_value(b_legacy_sum)) then 1 else 0): int
         val m_nams = (if (int32_value(a_name_count) <> int32_value(b_name_count)) || (~bstr_equal(a_name0, b_name0)) || (~bstr_equal(a_name1, b_name1)) || (~bstr_equal(a_name2, b_name2)) || (~bstr_equal(a_name3, b_name3)) || (~bstr_equal(a_name4, b_name4)) || (~bstr_equal(a_name5, b_name5)) || (~bstr_equal(a_name6, b_name6)) || (~bstr_equal(a_name7, b_name7)) then 2 else 0): int
       in $AR.add_int_int($AR.add_int_int(0, m_lega), m_nams) end)

(* The image of a index: the very index *)
#pub fun index_image_of {x:indexx} (index: !indexv(x)): index_image(x)

implement index_image_of {x} (index) =
  case+ index of
  | IndexV(b_legacy_size, b_legacy_sum, b_name_count, b_name0, b_name1, b_name2, b_name3, b_name4, b_name5, b_name6, b_name7) => let
      val n_legacy_size = int32_copy(b_legacy_size)
      val n_legacy_sum = int32_copy(b_legacy_sum)
      val n_name_count = int32_copy(b_name_count)
      val s_name0 = bstr_of_blist(b_name0)
      val s_name1 = bstr_of_blist(b_name1)
      val s_name2 = bstr_of_blist(b_name2)
      val s_name3 = bstr_of_blist(b_name3)
      val s_name4 = bstr_of_blist(b_name4)
      val s_name5 = bstr_of_blist(b_name5)
      val s_name6 = bstr_of_blist(b_name6)
      val s_name7 = bstr_of_blist(b_name7)
    in IndexImage(n_legacy_size, n_legacy_sum, n_name_count, s_name0, s_name1, s_name2, s_name3, s_name4, s_name5, s_name6, s_name7) end

(* The index an image holds *)
#pub fun index_of_image {x:indexx} (image: !index_image(x)): indexv(x)

implement index_of_image {x} (image) =
  case+ image of
  | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => let
      val n_legacy_size = int32_copy(a_legacy_size)
      val n_legacy_sum = int32_copy(a_legacy_sum)
      val n_name_count = int32_copy(a_name_count)
      val l_name0 = blist_of_bstr(a_name0)
      val l_name1 = blist_of_bstr(a_name1)
      val l_name2 = blist_of_bstr(a_name2)
      val l_name3 = blist_of_bstr(a_name3)
      val l_name4 = blist_of_bstr(a_name4)
      val l_name5 = blist_of_bstr(a_name5)
      val l_name6 = blist_of_bstr(a_name6)
      val l_name7 = blist_of_bstr(a_name7)
    in IndexV(n_legacy_size, n_legacy_sum, n_name_count, l_name0, l_name1, l_name2, l_name3, l_name4, l_name5, l_name6, l_name7) end

(* The image of a stored index, as read *)
#pub fun index_record_image {x:indexx}{ver,minver:int}{e:extras} (record: !indexrecord(x, ver, minver, e)): index_image(x)

implement index_record_image {x}{ver,minver}{e} (record) =
  case+ record of IndexRecord(_, _, index, _) => index_image_of(index)

(* A new record of an image: the format version this Quire writes, and no chunks kept. It holds the very index the image does. *)
#pub fun index_record_new {x:indexx} (image: !index_image(x)): indexrecord(x, 1, 1, ex_nil())

implement index_record_new {x} (image) = IndexRecord(1, 1, index_of_image(image), EXV_nil())

fn index_free_book {x:indexx} (index: indexv(x)): void =
  case+ index of
  | ~IndexV(f_legacy_size, f_legacy_sum, f_name_count, f_name0, f_name1, f_name2, f_name3, f_name4, f_name5, f_name6, f_name7) => let
      val () = int32_free(f_legacy_size)
      val () = int32_free(f_legacy_sum)
      val () = int32_free(f_name_count)
      val () = blist_free(f_name0)
      val () = blist_free(f_name1)
      val () = blist_free(f_name2)
      val () = blist_free(f_name3)
      val () = blist_free(f_name4)
      val () = blist_free(f_name5)
      val () = blist_free(f_name6)
      val () = blist_free(f_name7)
    in () end

(* A record freed *)
#pub fun index_record_free {x:indexx}{ver,minver:int}{e:extras} (record: indexrecord(x, ver, minver, e)): void

implement index_record_free {x}{ver,minver}{e} (record) =
  case+ record of
  | ~IndexRecord(_, _, index, extras) => let
      val () = index_free_book(index)
    in extrasv_free(extras) end

(* The number of the record, or the image's *)
fn _pick_number {a,b:int} (take: bool, kept: int32v(a), other: !int32v(b)): [v:int] int32v(v) =
  if take then let val () = int32_free(kept) in int32_copy(other) end else kept

(* The bytes of the record, or those the image's array holds *)
fn _pick_text {first,second:bytes}{n:nat | n < 256} (take: bool, kept: blist(first, n), other: !bstr(second)): [bs:bytes][len:nat | len < 256] blist(bs, len) =
  if take then let val () = blist_free(kept) in blist_of_bstr(other) end else kept

(* The record with the groups in the mask taken from the image, and the others as they are *)
#pub fun index_record_patch {x,y:indexx}{ver,minver:int}{e:extras} (record: indexrecord(x, ver, minver, e), image: !index_image(y), mask: int)
  : [z:indexx] indexrecord(z, ver, minver, e)

implement index_record_patch {x,y}{ver,minver}{e} (record, image, mask) =
  case+ record of
  | ~IndexRecord(ver, minver, index, extras) =>
    (case+ index of
     | ~IndexV(f_legacy_size, f_legacy_sum, f_name_count, f_name0, f_name1, f_name2, f_name3, f_name4, f_name5, f_name6, f_name7) =>
       (case+ image of
        | IndexImage(a_legacy_size, a_legacy_sum, a_name_count, a_name0, a_name1, a_name2, a_name3, a_name4, a_name5, a_name6, a_name7) => let
            val take_lega = $AR.band_int_int(mask, 1) <> 0
            val take_nams = $AR.band_int_int(mask, 2) <> 0
            val c_legacy_size = _pick_number(take_lega, f_legacy_size, a_legacy_size)
            val c_legacy_sum = _pick_number(take_lega, f_legacy_sum, a_legacy_sum)
            val c_name_count = _pick_number(take_nams, f_name_count, a_name_count)
            val c_name0 = _pick_text(take_nams, f_name0, a_name0)
            val c_name1 = _pick_text(take_nams, f_name1, a_name1)
            val c_name2 = _pick_text(take_nams, f_name2, a_name2)
            val c_name3 = _pick_text(take_nams, f_name3, a_name3)
            val c_name4 = _pick_text(take_nams, f_name4, a_name4)
            val c_name5 = _pick_text(take_nams, f_name5, a_name5)
            val c_name6 = _pick_text(take_nams, f_name6, a_name6)
            val c_name7 = _pick_text(take_nams, f_name7, a_name7)
          in IndexRecord(ver, minver, IndexV(c_legacy_size, c_legacy_sum, c_name_count, c_name0, c_name1, c_name2, c_name3, c_name4, c_name5, c_name6, c_name7), extras) end))

(* An image of numbers and strings (each in an array one longer than the string, which it takes), or none when a number is not one of 32 bits *)
#pub fun index_image_make {name0_loc,name1_loc,name2_loc,name3_loc,name4_loc,name5_loc,name6_loc,name7_loc:agz}{name0_len,name1_len,name2_len,name3_len,name4_len,name5_len,name6_len,name7_len:nat | name0_len < 256; name1_len < 256; name2_len < 256; name3_len < 256; name4_len < 256; name5_len < 256; name6_len < 256; name7_len < 256}
  (numbers: index_numbers, name0: $A.arr(byte, name0_loc, name0_len + 1), name0_len: int name0_len, name1: $A.arr(byte, name1_loc, name1_len + 1), name1_len: int name1_len, name2: $A.arr(byte, name2_loc, name2_len + 1), name2_len: int name2_len, name3: $A.arr(byte, name3_loc, name3_len + 1), name3_len: int name3_len, name4: $A.arr(byte, name4_loc, name4_len + 1), name4_len: int name4_len, name5: $A.arr(byte, name5_loc, name5_len + 1), name5_len: int name5_len, name6: $A.arr(byte, name6_loc, name6_len + 1), name6_len: int name6_len, name7: $A.arr(byte, name7_loc, name7_len + 1), name7_len: int name7_len): [x:indexx] index_imaged(x)

implement index_image_make (numbers, name0, name0_len, name1, name1_len, name2, name2_len, name3, name3_len, name4, name4_len, name5, name5_len, name6, name6_len, name7, name7_len) = let
  fn release {l:agz}{len:nat | len < 256} (array: $A.arr(byte, l, len + 1)): void = $A.free<byte>(array)
in
  case+ int32_make(numbers.legacy_size) of
  | ~I32_unrepresentable() => let
      val () = $A.free<byte>(name0)
      val () = $A.free<byte>(name1)
      val () = $A.free<byte>(name2)
      val () = $A.free<byte>(name3)
      val () = $A.free<byte>(name4)
      val () = $A.free<byte>(name5)
      val () = $A.free<byte>(name6)
      val () = $A.free<byte>(name7)
    in IndexNotImaged() end
  | ~I32_made(n_legacy_size) =>
    case+ int32_make(numbers.legacy_sum) of
    | ~I32_unrepresentable() => let
        val () = int32_free(n_legacy_size)
        val () = $A.free<byte>(name0)
        val () = $A.free<byte>(name1)
        val () = $A.free<byte>(name2)
        val () = $A.free<byte>(name3)
        val () = $A.free<byte>(name4)
        val () = $A.free<byte>(name5)
        val () = $A.free<byte>(name6)
        val () = $A.free<byte>(name7)
      in IndexNotImaged() end
    | ~I32_made(n_legacy_sum) =>
      case+ int32_make(numbers.name_count) of
      | ~I32_unrepresentable() => let
          val () = int32_free(n_legacy_size)
          val () = int32_free(n_legacy_sum)
          val () = $A.free<byte>(name0)
          val () = $A.free<byte>(name1)
          val () = $A.free<byte>(name2)
          val () = $A.free<byte>(name3)
          val () = $A.free<byte>(name4)
          val () = $A.free<byte>(name5)
          val () = $A.free<byte>(name6)
          val () = $A.free<byte>(name7)
        in IndexNotImaged() end
      | ~I32_made(n_name_count) =>
        let
          val s_name0 = bstr_of_array(name0, name0_len)
          val () = $A.free<byte>(name0)
          val s_name1 = bstr_of_array(name1, name1_len)
          val () = $A.free<byte>(name1)
          val s_name2 = bstr_of_array(name2, name2_len)
          val () = $A.free<byte>(name2)
          val s_name3 = bstr_of_array(name3, name3_len)
          val () = $A.free<byte>(name3)
          val s_name4 = bstr_of_array(name4, name4_len)
          val () = $A.free<byte>(name4)
          val s_name5 = bstr_of_array(name5, name5_len)
          val () = $A.free<byte>(name5)
          val s_name6 = bstr_of_array(name6, name6_len)
          val () = $A.free<byte>(name6)
          val s_name7 = bstr_of_array(name7, name7_len)
          val () = $A.free<byte>(name7)
        in IndexImaged(IndexImage(n_legacy_size, n_legacy_sum, n_name_count, s_name0, s_name1, s_name2, s_name3, s_name4, s_name5, s_name6, s_name7)) end
end

(* An image written as a record and read back: an image of the very index. That the bytes read are
   those written is the checked part (a index written is read back, whatever bytes they are);
   the image comes out of the record read, not out of the one written. *)
#pub fun index_image_roundtrip {x:indexx} (image: !index_image(x)): index_image(x)

implement index_image_roundtrip {x} (image) = let
  val record = index_record_new(image)
  val (written | list) = index_record_write(record)
  val () = index_record_free(record)
  val (whole | count) = blist_len(list)
  val (read_proof | read) = index_record_read(list)
  prval same = index_enc_dec(whole, written, read_proof)
  val checked = index_read_recast(same | read)
in
  case+ checked of
  | ~IR_ok(record_read) => let
      val back = index_record_image(record_read)
      val () = index_record_free(record_read)
    in back end
end

end
