(* indexrec -- the library's index record: its groups and fields, generated by scripts/gen-record.py *)

#target wasm begin

#include "share/atspre_staload.hats"

staload "bytes.sats"
staload "crc.sats"
staload "chunk.sats"
staload "seq.sats"
staload "fields.sats"
staload "schema.sats"
staload "record.sats"

#pub datasort indexx =
  | indexx_mk of (int, int, int, bytes, bytes, bytes, bytes, bytes, bytes, bytes, bytes)

#pub stadef INDEX_SPECS = gs_cons(bcons(76, bcons(69, bcons(71, bcons(65, bnil())))), lo_i32(lo_i32(lo_nil())), m_opt(), fv_i32(0, fv_i32(0, fv_nil())), gs_cons(bcons(78, bcons(65, bcons(77, bcons(83, bnil())))), lo_i32(lo_str(lo_str(lo_str(lo_str(lo_str(lo_str(lo_str(lo_str(lo_nil()))))))))), m_req(), fv_i32(0, fv_str(bnil(), fv_str(bnil(), fv_str(bnil(), fv_str(bnil(), fv_str(bnil(), fv_str(bnil(), fv_str(bnil(), fv_str(bnil(), fv_nil()))))))))), gs_nil()))

#pub stadef INDEX_KIND = 2

#pub fun index_specs (): specsv(INDEX_SPECS, 2)

implement index_specs () = SPV_cons(TAGNOT_mk() | blist_cons(76, blist_cons(69, blist_cons(71, blist_cons(65, blist_nil())))), LYV_i32(LYV_i32(LYV_nil())), ModeOpt(), FVV_i32(int32_zero(), FVV_i32(int32_zero(), FVV_nil())), SPV_cons(TAGNOT_mk() | blist_cons(78, blist_cons(65, blist_cons(77, blist_cons(83, blist_nil())))), LYV_i32(LYV_str(LYV_str(LYV_str(LYV_str(LYV_str(LYV_str(LYV_str(LYV_str(LYV_nil()))))))))), ModeReq(), FVV_i32(int32_zero(), FVV_str(blist_nil(), FVV_str(blist_nil(), FVV_str(blist_nil(), FVV_str(blist_nil(), FVV_str(blist_nil(), FVV_str(blist_nil(), FVV_str(blist_nil(), FVV_str(blist_nil(), FVV_nil()))))))))), SPV_nil()))

(* INDEXV(x, vals): the values of the groups are the fields of the index x *)
#pub dataprop INDEXV(indexx, gvals) =
  | {legacy_size,legacy_sum,name_count:int}{name0,name1,name2,name3,name4,name5,name6,name7:bytes}
    INDEXV_mk(indexx_mk(legacy_size, legacy_sum, name_count, name0, name1, name2, name3, name4, name5, name6, name7), gv_cons(fv_i32(legacy_size, fv_i32(legacy_sum, fv_nil())), gv_cons(fv_i32(name_count, fv_str(name0, fv_str(name1, fv_str(name2, fv_str(name3, fv_str(name4, fv_str(name5, fv_str(name6, fv_str(name7, fv_nil()))))))))), gv_nil())))

#pub datavtype indexv(indexx) =
  | {legacy_size,legacy_sum,name_count:int}{name0,name1,name2,name3,name4,name5,name6,name7:bytes}{name0_len,name1_len,name2_len,name3_len,name4_len,name5_len,name6_len,name7_len:nat | name0_len < 256; name1_len < 256; name2_len < 256; name3_len < 256; name4_len < 256; name5_len < 256; name6_len < 256; name7_len < 256}
    IndexV(indexx_mk(legacy_size, legacy_sum, name_count, name0, name1, name2, name3, name4, name5, name6, name7)) of (int32v(legacy_size), int32v(legacy_sum), int32v(name_count), blist(name0, name0_len), blist(name1, name1_len), blist(name2, name2_len), blist(name3, name3_len), blist(name4, name4_len), blist(name5, name5_len), blist(name6, name6_len), blist(name7, name7_len))

(* The record as the values of its groups, with the proof that they are its fields *)
#pub fun index_to_vals {x:indexx} (index: !indexv(x)): [vals:gvals] (INDEXV(x, vals) | gvalsv(INDEX_SPECS, vals, 2))

implement index_to_vals {x} (index) =
  case+ index of
  | IndexV(legacy_size, legacy_sum, name_count, name0, name1, name2, name3, name4, name5, name6, name7) => (INDEXV_mk() | 
    GVV_cons(FVV_i32(int32_copy(legacy_size), FVV_i32(int32_copy(legacy_sum), FVV_nil())), GVV_cons(FVV_i32(int32_copy(name_count), FVV_str(blist_copy(name0), FVV_str(blist_copy(name1), FVV_str(blist_copy(name2), FVV_str(blist_copy(name3), FVV_str(blist_copy(name4), FVV_str(blist_copy(name5), FVV_str(blist_copy(name6), FVV_str(blist_copy(name7), FVV_nil()))))))))), GVV_nil())))

(* The record made of the values of its groups, with the proof that they are its fields *)
#pub fun index_of_vals {vals:gvals}{kv:nat} (vals: gvalsv(INDEX_SPECS, vals, kv)): [x:indexx] (INDEXV(x, vals) | indexv(x))

implement index_of_vals {vals}{kv} (vals) =
  case+ vals of
  | ~GVV_cons(~FVV_i32(legacy_size, ~FVV_i32(legacy_sum, ~FVV_nil())), ~GVV_cons(~FVV_i32(name_count, ~FVV_str(name0, ~FVV_str(name1, ~FVV_str(name2, ~FVV_str(name3, ~FVV_str(name4, ~FVV_str(name5, ~FVV_str(name6, ~FVV_str(name7, ~FVV_nil()))))))))), ~GVV_nil())) => (INDEXV_mk() | IndexV(legacy_size, legacy_sum, name_count, name0, name1, name2, name3, name4, name5, name6, name7))


(* what reading a stored index comes to *)
#pub datasort indexres =
  | ir_ok of (indexx, int, int, extras)
  | ir_loss of (indexx, int, int, extras, lost)
  | ir_notquire of ()
  | ir_newer of ()
  | ir_damaged of ()

(* INDEXENC(x, ver, minver, e, bs): bs is the index x, written in the format ver,
   readable from minver, with the chunks e kept *)
#pub dataprop INDEXENC(indexx, int, int, extras, bytes) =
  | {x:indexx}{ver,minver:int}{e:extras}{vals:gvals}{bs:bytes}
    INDEXENC_mk(x, ver, minver, e, bs) of (INDEXV(x, vals), ENCODES(INDEX_SPECS, INDEX_KIND, rx_mk(ver, minver, vals, e), bs))

(* INDEXDEC(bs, res): reading bs as a index comes to res *)
#pub dataprop INDEXDEC(bytes, indexres) =
  | {x:indexx}{ver,minver:int}{e:extras}{vals:gvals}{bs:bytes}
    INDEXDEC_ok(bs, ir_ok(x, ver, minver, e)) of (INDEXV(x, vals), DECODES(INDEX_SPECS, INDEX_KIND, bs, rr_ok(rx_mk(ver, minver, vals, e))))
  | {x:indexx}{ver,minver:int}{e:extras}{t:lost}{vals:gvals}{bs:bytes}
    INDEXDEC_loss(bs, ir_loss(x, ver, minver, e, t)) of (INDEXV(x, vals), DECODES(INDEX_SPECS, INDEX_KIND, bs, rr_loss(rx_mk(ver, minver, vals, e), t)))
  | {bs:bytes} INDEXDEC_notquire(bs, ir_notquire()) of DECODES(INDEX_SPECS, INDEX_KIND, bs, rr_notquire())
  | {bs:bytes} INDEXDEC_newer(bs, ir_newer()) of DECODES(INDEX_SPECS, INDEX_KIND, bs, rr_newer())
  | {bs:bytes} INDEXDEC_damaged(bs, ir_damaged()) of DECODES(INDEX_SPECS, INDEX_KIND, bs, rr_damaged())

(* a index record at run time: its format version, the least version that reads it, the index,
   and the chunks kept *)
#pub datavtype indexrecord(indexx, int, int, extras) =
  | {x:indexx}{ver,minver:int | 0 <= ver; ver < 256; 0 <= minver; minver <= READER}{e:extras}{ke:nat}
    IndexRecord(x, ver, minver, e) of (int ver, int minver, indexv(x), extrasv(e, ke))

#pub datavtype indexread(indexres) =
  | {x:indexx}{ver,minver:int}{e:extras} IR_ok(ir_ok(x, ver, minver, e)) of indexrecord(x, ver, minver, e)
  | {x:indexx}{ver,minver:int}{e:extras}{t:lost}{kl:nat} IR_loss(ir_loss(x, ver, minver, e, t)) of (indexrecord(x, ver, minver, e), lostv(t, kl))
  | IR_notquire(ir_notquire())
  | IR_newer(ir_newer())
  | IR_damaged(ir_damaged())

#pub fun index_record_write {x:indexx}{ver,minver:int}{e:extras} (record: !indexrecord(x, ver, minver, e))
  : [bs:bytes][m:nat] (INDEXENC(x, ver, minver, e, bs) | blist(bs, m))

implement index_record_write {x}{ver,minver}{e} (record) =
  case+ record of
  | IndexRecord(ver, minver, index, extras) => let
      val specs = index_specs()
      val (fields | vals) = index_to_vals(index)
      val (written | out) = record_write(specs, 2, ver, minver, vals, extras)
      val () = gvalsv_free(vals)
      val () = specsv_free(specs)
    in (INDEXENC_mk(fields, written) | out) end

#pub fun index_record_read {bs:bytes}{n:nat} (list: blist(bs, n)): [res:indexres] (INDEXDEC(bs, res) | indexread(res))

implement index_record_read {bs}{n} (list) = let
  val specs = index_specs()
  val (read | out) = record_read(specs, 2, list)
  val () = specsv_free(specs)
in
  case+ out of
  | ~RR_ok(ver, minver, vals, extras) => let
      val (fields | index) = index_of_vals(vals)
    in (INDEXDEC_ok(fields, read) | IR_ok(IndexRecord(ver, minver, index, extras))) end
  | ~RR_loss(ver, minver, vals, extras, lost) => let
      val (fields | index) = index_of_vals(vals)
    in (INDEXDEC_loss(fields, read) | IR_loss(IndexRecord(ver, minver, index, extras), lost)) end
  | ~RR_notquire() => (INDEXDEC_notquire(read) | IR_notquire())
  | ~RR_newer() => (INDEXDEC_newer(read) | IR_newer())
  | ~RR_damaged() => (INDEXDEC_damaged(read) | IR_damaged())
end

end
