(* overlay_rules -- the rules of the menus, dialogs, toasts, banners and the
   other overlays *)

#target wasm begin

#include "share/atspre_staload.hats"
staload "palette.sats"
staload "palette_proofs.sats"
staload "sheet.sats"
staload GT = "gestures/src/tracker.sats"
staload "declarations.sats"

(* The axes the image viewer's scroller (gestures region 2) hands the
   recognizer: none, since it takes a pinch, so the stylesheet's
   touch-action for .imbox comes from them and the browser leaves every
   gesture to the viewer *)
#pub fn image_zoom_axes (): $GT.axes

implement image_zoom_axes () = $GT.AxNone()

#pub fn overlay_rules {left:nat | left >= 6826} (sheet: sheet(left, false, false)): [after:nat | after >= left - 6826] sheet(after, false, false)

(* The image viewer and toasts, from .imview on *)
fn overlay_rules_image_viewer_and_toasts {left:nat | left >= 2600} (sheet: sheet(left, false, false)): [after:nat | after >= left - 2600] sheet(after, false, false) = let
  (* a book's image, full screen, on the bars' dark ground (a picture is
     best seen on a dark one, and every theme's bar is dark); the fingers
     zoom and pan it (image_viewer.bats) *)
  val sheet = rule(sheet, ".imview")
  val sheet = lay(sheet, Position(), "fixed")
  val sheet = lay(sheet, Left(), "0")
  val sheet = lay(sheet, Right(), "0")
  val sheet = lay(sheet, Top(), "0")
  val sheet = lay(sheet, Bottom(), "0")
  val sheet = lay(sheet, ZIndex(), "14")
  val sheet = fill(sheet, RoleBar())
  val sheet = close(sheet)
  (* the scroller: the picture's box is as large as it, or larger when
     zoomed, and the scroller scrolls it; margin auto (not centring by
     the flex container) keeps a larger box's start reachable. The
     fingers are the picture's own (touch-action from the region's axes,
     as the page's is), the browser's pinch is not *)
  val sheet = rule(sheet, ".imbox")
  val sheet = lay(sheet, Width(), "100%")
  val sheet = lay(sheet, Height(), "100%")
  val sheet = lay(sheet, Overflow(), "auto")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, TouchAction(), $GT.touch_action(image_zoom_axes(), true))
  val sheet = close(sheet)
  val sheet = rule(sheet, ".imimg")
  val sheet = lay(sheet, Display(), "block")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = lay(sheet, Margin(), "auto")
  val sheet = lay(sheet, Width(), "100%")
  val sheet = lay(sheet, Height(), "100%")
  val sheet = lay(sheet, ObjectFit(), "contain")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".imclose")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Top(), "max(8px,var(--safe-top))")
  val sheet = lay(sheet, Right(), "max(8px,var(--safe-right))")
  val sheet = surf(S_barfg_barhi | sheet, RoleBarText(), RoleBarHigh())
  val sheet = lay(sheet, BorderRadius(), "50%")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".imzoom")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Left(), "50%")
  val sheet = lay(sheet, Bottom(), "max(8px,var(--safe-bottom))")
  val sheet = centre_x(sheet)
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".imzoom .btn")
  val sheet = surf(S_barfg_barhi | sheet, RoleBarText(), RoleBarHigh())
  val sheet = lay(sheet, BorderRadius(), "24px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".toast")
  val sheet = lay(sheet, Position(), "fixed")
  val sheet = lay(sheet, Left(), "50%")
  val sheet = lay(sheet, Bottom(), "calc(env(safe-area-inset-bottom) + 112px)")
  val sheet = centre_x(sheet)
  (* over the overlays (a panel that removes something offers it back
     here, while it is still open) *)
  val sheet = lay(sheet, ZIndex(), "21")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "12px")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = surf(S_barfg_bar | sheet, RoleBarText(), RoleBar())
  val sheet = lay(sheet, BorderRadius(), "8px")
  val sheet = spaced(sheet, Padding(), SpaceSmall())
  val sheet = spaced(sheet, PaddingLeft(), SpaceLarge())
  val sheet = spaced(sheet, PaddingRight(), SpaceMedium())
  val sheet = lay(sheet, BoxShadow(), "0 2px 12px rgba(0,0,0,.35)")
  val sheet = lay(sheet, Width(), "max-content")
  val sheet = lay(sheet, BoxSizing(), "border-box")
  val sheet = lay(sheet, MaxWidth(), "min(420px,100vw - 2*max(16px,var(--safe-left),var(--safe-right)))")
  val sheet = close(sheet)
  (* a toast's words wrap, its buttons keep their width (the Undo toast
     has Undo and Dismiss beside its words) *)
  val sheet = rule(sheet, ".toast > span")
  val sheet = lay(sheet, Flex(), "1 1 auto")
  val sheet = lay(sheet, MinWidth(), "0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".toast > button")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = close(sheet)
  (* the copy status, above the Undo toast: text alone, with no button *)
  val sheet = rule(sheet, ".toast.tcopy")
  val sheet = lay(sheet, Bottom(), "calc(env(safe-area-inset-bottom) + 168px)")
  val sheet = lay(sheet, Padding(), "10px 16px")
  val sheet = close(sheet)
  (* the offer of a new version, above the copy status *)
  val sheet = rule(sheet, ".toast.tnew")
  val sheet = lay(sheet, Bottom(), "calc(env(safe-area-inset-bottom) + 224px)")
  val sheet = close(sheet)
  (* the scrim under a reader panel (.panel, .sheet, at 12), over the
     reader and its bars: a ground with no text, as the dialog's veil *)
  val sheet = rule(sheet, ".scrim")
  val sheet = lay(sheet, Position(), "fixed")
  val sheet = lay(sheet, Inset(), "0")
  val sheet = veil(sheet)
  val sheet = lay(sheet, ZIndex(), "11")
  val sheet = close(sheet)
  (* the focus stops around the reader's panels: fixed, so the focus
     coming to one scrolls nothing, and empty *)
  val sheet = rule(sheet, ".fstop")
  val sheet = lay(sheet, Position(), "fixed")
  val sheet = lay(sheet, Top(), "0")
  val sheet = lay(sheet, Left(), "0")
  val sheet = close(sheet)
in sheet end

(* The menus, from .ovl on *)
fn overlay_rules_menus {left:nat | left >= 1721} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1721] sheet(after, false, false) = let
  val sheet = rule(sheet, ".ovl")
  val sheet = lay(sheet, Position(), "fixed")
  val sheet = lay(sheet, Inset(), "0")
  val sheet = lay(sheet, Padding(), "var(--safe-top) var(--safe-right) var(--safe-bottom) var(--safe-left)")
  val sheet = lay(sheet, BoxSizing(), "border-box")
  val sheet = veil(sheet)
  val sheet = lay(sheet, ZIndex(), "20")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, JustifyContent(), "center")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".menu,.mbox")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = lay(sheet, BorderRadius(), "8px")
  val sheet = spaced(sheet, Padding(), SpaceSmall())
  val sheet = lay(sheet, MinWidth(), "200px")
  val sheet = lay(sheet, MaxWidth(), "min(92vw,420px)")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = lay(sheet, BoxShadow(), "0 4px 24px rgba(0,0,0,.3)")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".mi")
  val sheet = lay(sheet, TextAlign(), "left")
  val sheet = lay(sheet, Padding(), "12px 14px")
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = close(sheet)
  (* a menu of choices (the sort and view menu): the group's name, and the
     current choice checked by a mark drawn in the item's own text colour
     (the checkbox of Material's menus) *)
  val sheet = rule(sheet, ".mgroup")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".mhead")
  val sheet = lay(sheet, FontWeight(), "600")
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = lay(sheet, Padding(), "8px 14px 4px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".mi[role=menuitemradio]")
  val sheet = lay(sheet, Position(), "relative")
  val sheet = lay(sheet, PaddingLeft(), "40px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".mi[aria-checked=true]::before")
  val () = raw(sheet, "content:\"\";position:absolute;left:18px;top:50%;width:6px;height:12px;margin-top:-9px;border:solid currentColor;border-width:0 2px 2px 0;transform:rotate(45deg);")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".mi:hover")
  val sheet = surf(S_fg_line | sheet, RoleText(), RoleLine())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".mi[data-harm=y]")
  val sheet = surf(S_danger_card | sheet, RoleDanger(), RoleCard())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".mi[data-harm=y]:hover")
  val sheet = surf(S_danger_line | sheet, RoleDanger(), RoleLine())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".menu .mi.btn")
  val sheet = no_line(sheet)
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = lay(sheet, JustifyContent(), "flex-start")
  val sheet = lay(sheet, Padding(), "12px 14px")
  val sheet = lay(sheet, FontSize(), "inherit")
  val sheet = close(sheet)
  (* a dialog: Material's 24 px round it, 16 px between its parts *)
  val sheet = rule(sheet, ".mbox")
  val sheet = spaced(sheet, Padding(), SpaceExtraLarge())
  val sheet = spaced(sheet, Gap(), SpaceLarge())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".mtitle")
  val sheet = lay(sheet, FontWeight(), "bold")
  val sheet = lay(sheet, FontSize(), "18px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".mname")
  val sheet = lay(sheet, Font(), "inherit")
  val sheet = lay(sheet, Padding(), "8px")
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = close(sheet)
  (* the sync panel: what it does, then its fields, one a line *)
  val sheet = rule(sheet, ".sabout")
  val sheet = lay(sheet, Padding(), "4px 0")
  val sheet = close(sheet)
in sheet end

(* The dialog fields and book info, from .sfields on *)
fn overlay_rules_dialog_fields_and_book_info {left:nat | left >= 1601} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1601] sheet(after, false, false) = let
  val sheet = rule(sheet, ".sfields")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = lay(sheet, Margin(), "8px 0")
  val sheet = close(sheet)
  (* a book's collections, one toggle a line *)
  val sheet = rule(sheet, ".seg.cseg")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = lay(sheet, Margin(), "8px 0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".cnone")
  val sheet = surf(S_muted_card | sheet, RoleMuted(), RoleCard())
  val sheet = lay(sheet, Padding(), "8px 0")
  val sheet = lay(sheet, FontStyle(), "italic")
  val sheet = close(sheet)
  (* the reading statistics: a label and its number a line *)
  val sheet = rule(sheet, ".srow")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, JustifyContent(), "space-between")
  val sheet = lay(sheet, Gap(), "16px")
  val sheet = lay(sheet, Padding(), "8px 0")
  val sheet = surf(S_muted_card | sheet, RoleMuted(), RoleCard())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".srow b")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".mta")
  val sheet = lay(sheet, MinHeight(), "120px")
  val sheet = lay(sheet, Font(), "inherit")
  val sheet = lay(sheet, Padding(), "8px")
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".mbtns")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = lay(sheet, JustifyContent(), "flex-end")
  val sheet = lay(sheet, FlexWrap(), "wrap")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".btn[data-harm=y]")
  val sheet = surf(S_danger_card | sheet, RoleDanger(), RoleCard())
  val sheet = line(sheet, AllSides(), 1, RoleDanger())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".info")
  val sheet = lay(sheet, Position(), "fixed")
  val sheet = lay(sheet, Inset(), "0")
  val sheet = lay(sheet, ZIndex(), "15")
  val sheet = surf(S_fg_bg | sheet, RoleText(), RoleGround())
  val sheet = lay(sheet, Overflow(), "auto")
  val sheet = lay(sheet, Padding(), "max(12px,var(--safe-top)) max(16px,var(--safe-right)) max(24px,var(--safe-bottom)) max(16px,var(--safe-left))")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".info-in")
  val sheet = lay(sheet, MaxWidth(), "600px")
  val sheet = lay(sheet, Margin(), "0 auto")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = spaced(sheet, Gap(), SpaceSmall())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".info-in>.btn")
  val sheet = lay(sheet, AlignSelf(), "flex-start")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".icov")
  val sheet = lay(sheet, Width(), "160px")
  val sheet = lay(sheet, MaxWidth(), "50vw")
  val sheet = lay(sheet, MaxHeight(), "300px")
  val sheet = lay(sheet, ObjectFit(), "contain")
  val sheet = lay(sheet, AlignSelf(), "center")
  val sheet = lay(sheet, BorderRadius(), "4px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".it")
  val sheet = lay(sheet, FontFamily(), "Literata,Georgia,serif")
  val sheet = lay(sheet, FontSize(), "22px")
  val sheet = lay(sheet, FontWeight(), "bold")
  val sheet = close(sheet)
  (* Book info's accessibility section: its title, and each group's *)
  val sheet = rule(sheet, ".a11y")
  val sheet = lay(sheet, MarginTop(), "16px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".a11yt")
  val sheet = lay(sheet, FontWeight(), "600")
  val sheet = lay(sheet, FontSize(), "18px")
  val sheet = close(sheet)
in sheet end

(* The accessibility rows, from .a11yg on *)
fn overlay_rules_accessibility_rows {left:nat | left >= 347} (sheet: sheet(left, false, false)): [after:nat | after >= left - 347] sheet(after, false, false) = let
  val sheet = rule(sheet, ".a11yg")
  val sheet = lay(sheet, FontWeight(), "600")
  val sheet = lay(sheet, MarginTop(), "10px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".irow")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, JustifyContent(), "space-between")
  val sheet = line(sheet, BottomSide(), 1, RoleLine())
  val sheet = lay(sheet, Padding(), "8px 0")
  val sheet = surf(S_muted_bg | sheet, RoleMuted(), RoleGround())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".irow b")
  val sheet = surf(S_fg_bg | sheet, RoleText(), RoleGround())
  val sheet = lay(sheet, FontWeight(), "normal")
  val sheet = close(sheet)
in sheet end

implement overlay_rules (sheet) = let
  val sheet = overlay_rules_image_viewer_and_toasts(sheet)
  val sheet = overlay_rules_menus(sheet)
  val sheet = overlay_rules_dialog_fields_and_book_info(sheet)
  val sheet = overlay_rules_accessibility_rows(sheet)
in sheet end

end
