(* panel_rules -- the rules of the panels the reader opens: contents, search,
   annotations, statistics, dictionaries and the screens that follow
   Android's settings pattern *)

#target wasm begin

#include "share/atspre_staload.hats"
staload "palette.sats"
staload "palette_proofs.sats"
staload "sheet.sats"
staload "declarations.sats"

#pub fn panel_rules {left:nat | left >= 6700} (sheet: sheet(left, false, false)): [after:nat | after >= left - 6700] sheet(after, false, false)

(* The panel frame and tabs, from .panel on *)
fn panel_rules_panel_frame_and_tabs {left:nat | left >= 1536} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1536] sheet(after, false, false) = let
  val sheet = rule(sheet, ".panel")
  val sheet = lay(sheet, Position(), "fixed")
  val sheet = lay(sheet, Top(), "0")
  val sheet = lay(sheet, Bottom(), "0")
  val sheet = lay(sheet, Left(), "0")
  (* a modal side panel leaves a strip of the scrim, a tap on which
     closes it: as wide as the screen less 56 px, as Material's modal
     navigation drawer *)
  val sheet = lay(sheet, Width(), "min(420px,calc(100vw - 56px))")
  val sheet = lay(sheet, ZIndex(), "12")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = lay(sheet, BoxShadow(), "2px 0 16px rgba(0,0,0,.3)")
  val sheet = lay(sheet, Padding(), "var(--safe-top) 0 var(--safe-bottom) var(--safe-left)")
  val sheet = lay(sheet, BoxSizing(), "border-box")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".panel-r")
  val sheet = lay(sheet, Left(), "auto")
  val sheet = lay(sheet, Right(), "0")
  val sheet = lay(sheet, PaddingLeft(), "0")
  val sheet = lay(sheet, PaddingRight(), "var(--safe-right)")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".ph")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = spaced(sheet, Gap(), SpaceSmall())
  val sheet = spaced(sheet, Padding(), SpaceSmall())
  val sheet = line(sheet, BottomSide(), 1, RoleLine())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".ph .grow")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, MinWidth(), "0")
  val sheet = lay(sheet, FontWeight(), "bold")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".ph .ibtn")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = close(sheet)
  (* three tabs and Close fit the panel's head at 320px: the tabs are at
     least 48px tall (the base rule), so their sides give the room *)
  val sheet = rule(sheet, ".ph .tab")
  val sheet = spaced_pair(sheet, Padding(), SpaceSmall(), SpaceTight())
  val sheet = close(sheet)
  (* a header's buttons keep their whole text: the title gives way *)
  val sheet = rule(sheet, ".ph .btn")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = spaced(sheet, Padding(), SpaceSmall())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".tabs")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "4px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".tab")
  val sheet = spaced(sheet, Padding(), SpaceSmall())
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = close(sheet)
  (* the chosen tab keeps the card and is told apart by an underline in
     the accent, proven 3:1 on the card (quire#358) *)
  val sheet = rule(sheet, ".tab[aria-selected=true]")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = underline(E_accent_card | sheet, RoleAccent(), RoleCard())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".plist")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, Overflow(), "auto")
  (* its rows inset from the panel's sides, as Material's navigation
     drawer insets its items *)
  val sheet = spaced_pair(sheet, Padding(), SpaceTight(), SpaceSmall())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".pi")
  val sheet = lay(sheet, Display(), "block")
  val sheet = lay(sheet, Width(), "100%")
  val sheet = lay(sheet, TextAlign(), "left")
  val sheet = spaced_pair(sheet, Padding(), SpaceMedium(), SpaceLarge())
  val sheet = lay(sheet, BoxSizing(), "border-box")
  val sheet = lay(sheet, BorderRadius(), "8px")
  val sheet = line(sheet, BottomSide(), 1, RoleLine())
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = close(sheet)
in sheet end

(* The contents and highlights, from .pi[aria-current=true] on *)
fn panel_rules_contents_and_highlights {left:nat | left >= 1558} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1558] sheet(after, false, false) = let
  val sheet = rule(sheet, ".pi[aria-current=true]")
  val sheet = lay(sheet, FontWeight(), "bold")
  val sheet = surf(S_fg_line | sheet, RoleText(), RoleLine())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".pi1")
  val sheet = lay(sheet, PaddingLeft(), "30px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".pi2")
  val sheet = lay(sheet, PaddingLeft(), "46px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".pi3")
  val sheet = lay(sheet, PaddingLeft(), "62px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".snip")
  val sheet = lay(sheet, Display(), "block")
  val sheet = surf(S_muted_card | sheet, RoleMuted(), RoleCard())
  val sheet = lay(sheet, FontSize(), "13px")
  val sheet = lay(sheet, MarginTop(), "2px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".hq")
  val sheet = lay(sheet, Display(), "block")
  val sheet = line(sheet, LeftSide(), 3, RoleAccent())
  val sheet = lay(sheet, PaddingLeft(), "8px")
  val sheet = lay(sheet, FontStyle(), "italic")
  val sheet = close(sheet)
  (* a highlight's quote, marked as it is on the page, after its style's
     name *)
  val sheet = rule(sheet, ".hq-yellow")
  val sheet = surf(S_fg_hl | sheet, RoleText(), RoleHighlight())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".hq-orange")
  val sheet = surf(S_fg_hl2 | sheet, RoleText(), RoleSecondHighlight())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".hq-under")
  val sheet = lay(sheet, TextDecoration(), "underline 3px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".hstyle")
  val sheet = lay(sheet, Display(), "block")
  val sheet = lay(sheet, FontSize(), "12px")
  val sheet = surf(S_muted_card | sheet, RoleMuted(), RoleCard())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".seg.afilter")
  val sheet = lay(sheet, Margin(), "8px 12px")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".hn")
  val sheet = lay(sheet, Display(), "block")
  val sheet = lay(sheet, MarginTop(), "4px")
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".hbtns")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = lay(sheet, MarginTop(), "6px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".hbtns button")
  val sheet = lay(sheet, Padding(), "4px 12px")
  val sheet = line(sheet, AllSides(), 1, RoleLine())
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".hrow")
  val sheet = line(sheet, BottomSide(), 1, RoleLine())
  val sheet = lay(sheet, Padding(), "8px 12px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".hgo")
  val sheet = lay(sheet, Display(), "block")
  val sheet = lay(sheet, Width(), "100%")
  val sheet = lay(sheet, TextAlign(), "left")
  val sheet = lay(sheet, Padding(), "4px 0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".hgo *")
  val sheet = lay(sheet, PointerEvents(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".pi.hgo")
  val sheet = lay(sheet, Padding(), "10px 14px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".pi.hgo .snip")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = lay(sheet, MarginTop(), "0")
  val sheet = lay(sheet, LineHeight(), "1.45")
  val sheet = close(sheet)
in sheet end

(* The settings sheet, from .grp on *)
fn panel_rules_settings_sheet {left:nat | left >= 1612} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1612] sheet(after, false, false) = let
  val sheet = rule(sheet, ".grp")
  val sheet = lay(sheet, FontWeight(), "bold")
  val sheet = lay(sheet, Padding(), "12px 12px 4px")
  val sheet = surf(S_muted_card | sheet, RoleMuted(), RoleCard())
  val sheet = lay(sheet, FontSize(), "13px")
  val sheet = lay(sheet, LetterSpacing(), ".04em")
  val sheet = lay(sheet, TextTransform(), "uppercase")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".sheet")
  val sheet = lay(sheet, Position(), "fixed")
  val sheet = lay(sheet, Left(), "0")
  val sheet = lay(sheet, Right(), "0")
  val sheet = lay(sheet, Bottom(), "0")
  val sheet = lay(sheet, ZIndex(), "12")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = lay(sheet, Padding(), "12px max(16px,var(--safe-right)) 0 max(16px,var(--safe-left))")
  val sheet = lay(sheet, BoxShadow(), "0 -2px 16px rgba(0,0,0,.3)")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = lay(sheet, Gap(), "10px")
  val sheet = lay(sheet, MaxWidth(), "520px")
  val sheet = lay(sheet, Margin(), "0 auto")
  val sheet = lay(sheet, BorderRadius(), "12px 12px 0 0")
  (* taller than a short screen allows: it scrolls, within the height
     shown (dvh: in full screen, and in a WebView, vh can be more) *)
  val sheet = lay(sheet, MaxHeight(), "85dvh")
  val sheet = lay(sheet, Overflow(), "auto")
  val sheet = close(sheet)
  (* a sheet's head, its Close in it: held at the sheet's top as the
     rest scrolls, so Close is always in reach (as Apple Books' sheet
     keeps its close at its top) *)
  val sheet = rule(sheet, ".shead")
  val sheet = lay(sheet, Position(), "sticky")
  val sheet = lay(sheet, Top(), "-12px")
  val sheet = lay(sheet, ZIndex(), "1")
  val sheet = lay(sheet, Margin(), "-12px -16px 0")
  val sheet = lay(sheet, Padding(), "12px 16px 6px")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = line(sheet, BottomSide(), 1, RoleLine())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".shead .grow")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, FontWeight(), "bold")
  val sheet = close(sheet)
  (* its rows keep their height, and the sheet scrolls instead *)
  val sheet = rule(sheet, ".sheet>*")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = close(sheet)
  (* its foot pads the sheet's bottom and is held there as the rest
     scrolls, on the sheet's ground, so nothing scrolls under the
     navigation bar (#341) *)
  val sheet = rule(sheet, ".sheet>.sfoot")
  val sheet = lay(sheet, Position(), "sticky")
  val sheet = lay(sheet, Bottom(), "0")
  val sheet = lay(sheet, ZIndex(), "1")
  val sheet = lay(sheet, PaddingBottom(), "max(16px,var(--safe-bottom))")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = close(sheet)
  (* a note's text, over the page: a long one scrolls *)
  val sheet = rule(sheet, ".fntext")
  val sheet = lay(sheet, MaxHeight(), "50dvh")
  val sheet = lay(sheet, Overflow(), "auto")
  val sheet = lay(sheet, LineHeight(), "1.5")
  val sheet = close(sheet)
  (* a dictionary's article, as text: its line breaks kept *)
  val sheet = rule(sheet, ".dart")
  val sheet = lay(sheet, WhiteSpace(), "pre-wrap")
  val sheet = close(sheet)
  (* a catalogue's book: its cover, title and author, and Get *)
  val sheet = rule(sheet, ".bkrow")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Gap(), "12px")
  val sheet = lay(sheet, Padding(), "10px 14px")
  val sheet = line(sheet, BottomSide(), 1, RoleLine())
  val sheet = close(sheet)
  (* the fields that add a catalogue *)
  val sheet = rule(sheet, ".cform")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = close(sheet)
in sheet end

(* The setting rows, from .srow on *)
fn panel_rules_setting_rows {left:nat | left >= 1521} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1521] sheet(after, false, false) = let
  val sheet = rule(sheet, ".srow")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Gap(), "10px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".slabel")
  val sheet = lay(sheet, Width(), "7em")
  val sheet = surf(S_muted_card | sheet, RoleMuted(), RoleCard())
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".srow input[type=range]")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = accent(E_accent_card | sheet, RoleAccent(), RoleCard())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".sval")
  val sheet = lay(sheet, Width(), "3em")
  val sheet = lay(sheet, TextAlign(), "right")
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".seg")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "6px")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, FlexWrap(), "wrap")
  val sheet = close(sheet)
  (* a segment is never narrower than its label (the 44 px minimum
     would let it shrink under it and cut it, #265): the segments that
     do not fit go to the next line, and a label wider than the line
     wraps in its segment *)
  val sheet = rule(sheet, ".seg button")
  val sheet = lay(sheet, Flex(), "1 0 auto")
  val sheet = lay(sheet, MaxWidth(), "100%")
  val sheet = lay(sheet, Padding(), "8px 6px")
  val sheet = line(sheet, AllSides(), 1, RoleLine())
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".seg button[aria-pressed=true]")
  val sheet = surf(S_accentfg_accent | sheet, RoleAccentText(), RoleAccent())
  val sheet = line(sheet, AllSides(), 1, RoleAccent())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".sfoot")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = lay(sheet, JustifyContent(), "space-between")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".link")
  val sheet = surf(S_accent_card | sheet, RoleAccent(), RoleCard())
  val sheet = lay(sheet, TextDecoration(), "underline")
  val sheet = lay(sheet, Padding(), "6px 0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".sbar")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = spaced(sheet, Gap(), SpaceSmall())
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = spaced(sheet, Padding(), SpaceSmall())
  val sheet = line(sheet, BottomSide(), 1, RoleLine())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".sbar input")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, Padding(), "6px 10px")
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = lay(sheet, Font(), "inherit")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".snav")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, JustifyContent(), "center")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = spaced(sheet, Padding(), SpaceSmall())
  val sheet = line(sheet, TopSide(), 1, RoleLine())
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = close(sheet)
in sheet end

implement panel_rules (sheet) = let
  val sheet = panel_rules_panel_frame_and_tabs(sheet)
  val sheet = panel_rules_contents_and_highlights(sheet)
  val sheet = panel_rules_settings_sheet(sheet)
  val sheet = panel_rules_setting_rows(sheet)
in sheet end

end
