(* reader_rules -- the reader's rules: the page, its bars, the footer, the
   scrubber and the marks *)

#target wasm begin

#include "share/atspre_staload.hats"
staload "palette.sats"
staload "palette_proofs.sats"
staload "sheet.sats"
staload "declarations.sats"
staload "page_size.sats"

#pub fn reader_rules {left:nat | left >= 10450} (sheet: sheet(left, false, false)): [after:nat | after >= left - 10450] sheet(after, false, false)

(* The bars and title, from .rv on *)
fn reader_rules_bars_and_title {left:nat | left >= 1642} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1642] sheet(after, false, false) = let
  (* the reader is the window, whatever a viewport unit says (in an
     Android WebView 100vh can be taller than what is shown, so the page
     and a sheet's bottom could pass the screen's edge, #275): fixed to
     the layout viewport, nothing behind it scrolls *)
  val sheet = rule(sheet, ".rv")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = lay(sheet, Position(), "fixed")
  val sheet = lay(sheet, Inset(), "0")
  (* The visible reading area, given once here: what the page's
     paddings keep clear (its columns are the page's height less them,
     so the column is exactly that area), the running footer's place,
     and a vertical page's column gap (#296). The footer sits 8px above
     the screen's bottom inset (Android's navigation bar, which an app
     drawn edge to edge has under it), 16px tall, and the text keeps
     half a line (at least 12px) clear of the footer below and of the
     top inset (the status bar) above: Material 3 spaces on 4dp steps
     and pads what the system bars would cover by their insets.
     A line-height unit (lh) in a variable is the line of the element
     that uses it: the page's *)
  val sheet = lay(sheet, FooterBottomVariable(), "calc(env(safe-area-inset-bottom) + 8px)")
  val sheet = lay(sheet, FooterHeightVariable(), "16px")
  val sheet = lay(sheet, PageTopVariable(), "max(48px,calc(env(safe-area-inset-top) + max(12px,.5lh)))")
  val sheet = lay(sheet, PageBottomVariable(), "calc(var(--footer-bottom) + var(--footer-height) + max(12px,.5lh))")
  val sheet = surf(S_fg_bg | sheet, RoleText(), RoleGround())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".top,.bot")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Gap(), "4px")
  val sheet = lay(sheet, Padding(), "2px max(6px,var(--safe-right)) 2px max(6px,var(--safe-left))")
  val sheet = surf(S_barfg_bar | sheet, RoleBarText(), RoleBar())
  val sheet = lay(sheet, ZIndex(), "3")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".top")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Top(), "0")
  val sheet = lay(sheet, Left(), "0")
  val sheet = lay(sheet, Right(), "0")
  val sheet = lay(sheet, PaddingTop(), "max(2px,var(--safe-top))")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".bot")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Bottom(), "0")
  val sheet = lay(sheet, Left(), "0")
  val sheet = lay(sheet, Right(), "0")
  val sheet = lay(sheet, FlexWrap(), "wrap")
  val sheet = lay(sheet, PaddingBottom(), "max(2px,var(--safe-bottom))")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".top .ibtn,.bot .ibtn,.snavf .ibtn")
  val sheet = surf(S_barfg_bar | sheet, RoleBarText(), RoleBar())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".top .ibtn:hover,.bot .ibtn:hover,.snavf .ibtn:hover")
  val sheet = surf(S_barfg_barhi | sheet, RoleBarText(), RoleBarHigh())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".ctitle")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = lay(sheet, Overflow(), "hidden")
  val sheet = lay(sheet, WhiteSpace(), "nowrap")
  val sheet = lay(sheet, TextOverflow(), "ellipsis")
  val sheet = close(sheet)
  (* the bottom bar's progress row: the label, a line of its own over
     the scrubber, whole (#274): it wraps before the percentage rather
     than cut anything *)
  (* the offer of the place another device read (sync.bats): a row of
     its own, the bar's first, over the progress row *)
  val sheet = rule(sheet, ".soffer")
  val sheet = lay(sheet, FlexBasis(), "100%")
  val sheet = lay(sheet, Order(), "-1")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, JustifyContent(), "center")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = lay(sheet, PaddingTop(), "6px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".plab")
  val sheet = lay(sheet, FlexBasis(), "100%")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexWrap(), "wrap")
  val sheet = lay(sheet, JustifyContent(), "center")
  val sheet = lay(sheet, AlignItems(), "baseline")
  val sheet = lay(sheet, Gap(), "0 6px")
  val sheet = lay(sheet, MinWidth(), "0")
  val sheet = lay(sheet, PaddingTop(), "6px")
  val sheet = lay(sheet, FontSize(), "13px")
  val sheet = lay(sheet, TextAlign(), "center")
  val sheet = close(sheet)
in sheet end

(* The page indicator and footer, from .pinfo on *)
fn reader_rules_page_indicator_and_footer {left:nat | left >= 1675} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1675] sheet(after, false, false) = let
  val sheet = rule(sheet, ".pinfo")
  val sheet = lay(sheet, WhiteSpace(), "nowrap")
  val sheet = lay(sheet, Flex(), "0 1 auto")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, MinWidth(), "0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".psep")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = close(sheet)
  (* the tools row: each tool a 48 px target, spread evenly; the
     narration's group goes to a line of its own where the row has no
     room for it *)
  val sheet = rule(sheet, ".tools")
  val sheet = lay(sheet, FlexBasis(), "100%")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexWrap(), "wrap")
  val sheet = lay(sheet, JustifyContent(), "space-evenly")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Gap(), "4px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".tools .ibtn")
  val sheet = lay(sheet, Width(), "48px")
  val sheet = lay(sheet, Height(), "48px")
  val sheet = close(sheet)
  (* a long chapter title is cut, and the page numbers after it are not *)
  val sheet = rule(sheet, ".pgt")
  val sheet = lay(sheet, Overflow(), "hidden")
  val sheet = lay(sheet, TextOverflow(), "ellipsis")
  val sheet = lay(sheet, MinWidth(), "0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".pgn,.pgw")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = lay(sheet, WhiteSpace(), "pre")
  val sheet = close(sheet)
  (* the footer's readout, the one part of it a tap reaches: a tap on
     it shows the next *)
  val sheet = rule(sheet, ".rdo")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = lay(sheet, PointerEvents(), "auto")
  val sheet = lay(sheet, Cursor(), "pointer")
  val sheet = close(sheet)
  (* a link out of the app, in a bar: a control's box, not a text link *)
  val sheet = rule(sheet, ".linkout")
  val sheet = lay(sheet, Display(), "inline-flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, TextDecoration(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".chrome-off .top,.chrome-off .bot")
  val sheet = lay(sheet, Display(), "none")
  val sheet = close(sheet)
  (* the running footer, in the page's bottom margin while the bars are
     hidden; taps go through it to the page *)
  val sheet = rule(sheet, ".foot")
  val sheet = lay(sheet, Display(), "none")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Left(), "0")
  val sheet = lay(sheet, Right(), "0")
  val sheet = lay(sheet, Bottom(), "var(--footer-bottom)")
  val sheet = lay(sheet, Height(), "var(--footer-height)")
  val sheet = lay(sheet, LineHeight(), "var(--footer-height)")
  val sheet = lay(sheet, JustifyContent(), "center")
  val sheet = lay(sheet, Padding(), "0 24px")
  val sheet = lay(sheet, FontSize(), "12px")
  val sheet = lay(sheet, WhiteSpace(), "nowrap")
  val sheet = lay(sheet, PointerEvents(), "none")
  val sheet = surf(S_muted_bg | sheet, RoleMuted(), RoleGround())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".chrome-off .foot")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = close(sheet)
  (* the page keeps out of the screen's cutouts and rounded corners
     (the safe area) on every side, in or out of full screen: above and
     below in its paddings (the reading area's, .rv, which keep the
     running footer clear too, #296), and at its sides (a cutout there in
     landscape) in its margins, so its columns, a page each, are the
     safe width (#275) *)
  val sheet = rule(sheet, ".caf")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, Overflow(), "hidden")
  val sheet = lay(sheet, BoxSizing(), "border-box")
  (* the page's width and height, whole pixels: only a page_extent(1) gives their text (page_size.bats) *)
  val () = raw(sheet, page_width_rule(RoundedDown()))
  val () = raw(sheet, page_height_rule(RoundedDown()))
  val sheet = lay(sheet, MarginLeft(), "env(safe-area-inset-left)")
  val sheet = lay(sheet, MarginRight(), "env(safe-area-inset-right)")
  val sheet = lay(sheet, PaddingTop(), "var(--page-top)")
  val sheet = lay(sheet, PaddingBottom(), "var(--page-bottom)")
  val sheet = lay(sheet, ColumnFill(), "auto")
  val sheet = lay(sheet, ColumnGap(), "0")
  val sheet = lay(sheet, ColumnWidth(), "100vw")
  val sheet = lay(sheet, FontFamily(), "Literata,Georgia,serif")
  val sheet = lay(sheet, FontSize(), "18px")
  val sheet = lay(sheet, LineHeight(), "1.6")
  (* a run with no place to break (a megabyte of letters, a long
     address, #423) is broken to the column's width, else it is one line
     that overflows the page and is clipped, the rest out of reach.
     break-word, not anywhere: the same breaking, but the breaks a run
     makes do not count in a box's minimum width, so a table cell holding
     a run still makes its table as wide as the run and the table scrolls
     (#413); anywhere would shrink the table to the column and wrap it *)
  val sheet = lay(sheet, OverflowWrap(), "break-word")
  val sheet = lay(sheet, Outline(), "none")
  val sheet = close(sheet)
in sheet end

(* The book text, from .sprobe on *)
fn reader_rules_book_text {left:nat | left >= 1298} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1298] sheet(after, false, false) = let
  (* shown only by the typography's style, for a spread; a point the
     reader measures, never seen *)
  val sheet = rule(sheet, ".sprobe")
  val sheet = lay(sheet, Display(), "none")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Width(), "1px")
  val sheet = lay(sheet, Height(), "1px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf>*")
  val sheet = lay(sheet, MaxWidth(), "38rem")
  val sheet = lay(sheet, MarginLeft(), "auto")
  val sheet = lay(sheet, MarginRight(), "auto")
  val sheet = lay(sheet, BoxSizing(), "border-box")
  val sheet = close(sheet)
  (* a paragraph's alignment, hyphenation and the space after it are
     the reader's settings (settings.bats, in style-type). Its margins
     are logical: the space after it is below it in horizontal text,
     and beside it (between its columns of lines) in vertical text,
     where a margin below would shorten its lines *)
  val sheet = rule(sheet, ".caf p")
  val sheet = lay(sheet, MarginBlock(), "0 .8em")
  val sheet = lay(sheet, MarginInline(), "auto")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf h1,.caf h2,.caf h3")
  val sheet = lay(sheet, TextAlign(), "center")
  val sheet = lay(sheet, MarginBlock(), "1.5em .5em")
  val sheet = lay(sheet, BreakAfter(), "avoid")
  val sheet = close(sheet)
  (* the pieces of a text of 64 KiB or more (reader.bats' _text_spans) are
     blocks: the inline run of a paragraph drawn across its columns costs
     time in proportion to the square of them in Chrome, so none is longer
     than a piece (#423) *)
  val sheet = rule(sheet, ".caf .run")
  val sheet = lay(sheet, Display(), "block")
  val sheet = close(sheet)
  (* an element the book marks hidden stays hidden (#411) *)
  val sheet = rule(sheet, ".caf .hidden-by-book")
  val sheet = lay(sheet, Display(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf hr")
  val sheet = no_line(sheet)
  val sheet = line(sheet, TopSide(), 1, RoleLine())
  val sheet = lay(sheet, Margin(), "2em auto")
  val sheet = lay(sheet, MaxWidth(), "200px")
  val sheet = close(sheet)
  (* a picture is at most a column's height: the window's less the
     page's paddings *)
  val sheet = rule(sheet, ".caf img")
  val sheet = lay(sheet, MaxWidth(), "100%")
  val sheet = lay(sheet, MaxHeight(), "calc(100dvh - var(--page-top) - var(--page-bottom))")
  val sheet = lay(sheet, ObjectFit(), "contain")
  val sheet = lay(sheet, Height(), "auto")
  val sheet = lay(sheet, Display(), "block")
  val sheet = lay(sheet, Margin(), "0 auto")
  val sheet = lay(sheet, BreakInside(), "avoid")
  val sheet = close(sheet)
  (* a table is a scroll container, as wide as the column and as tall as its
     height at most (#413): a block that scrolls cannot be split between
     columns, so one taller than the page would lose the rows past the
     page's foot *)
  val sheet = rule(sheet, ".caf table")
  val sheet = lay(sheet, Display(), "block")
  val sheet = lay(sheet, Overflow(), "auto")
  val sheet = lay(sheet, MaxWidth(), "100%")
  val sheet = lay(sheet, MaxHeight(), "calc(100dvh - var(--page-top) - var(--page-bottom))")
  val sheet = lay(sheet, BorderCollapse(), "collapse")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf td,.caf th")
  val sheet = line(sheet, AllSides(), 1, RoleLine())
  val sheet = lay(sheet, Padding(), "2px 6px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf a,.caf [role=link]")
  val sheet = surf(S_accent_bg | sheet, RoleAccent(), RoleGround())
  val sheet = lay(sheet, TextDecoration(), "underline")
  val sheet = lay(sheet, Cursor(), "pointer")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf pre")
  val sheet = lay(sheet, WhiteSpace(), "pre-wrap")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf blockquote")
  val sheet = lay(sheet, Margin(), "1em auto")
  val sheet = lay(sheet, FontStyle(), "italic")
  val sheet = close(sheet)
in sheet end

(* The vertical fixed and notes, from .caf.rtl on *)
fn reader_rules_vertical_fixed_and_notes {left:nat | left >= 1130} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1130] sheet(after, false, false) = let
  (* right to left, the page itself: its columns go on to the left, and
     a spread's first page is the right one *)
  val sheet = rule(sheet, ".caf.rtl")
  val sheet = lay(sheet, Direction(), "rtl")
  val sheet = close(sheet)
  (* set vertically (a Chinese, Japanese or Korean book read right to
     left; Mongolian in its script, its lines going on to the right):
     the columns follow the inline axis, down the page, so a page is one
     column and the gap between two, the page's top and bottom paddings
     (.caf), and a turn is exactly the page's height. Always paged, one
     column a screen: these outrank the typography's .caf (style-type,
     settings.bats), whose columns and scroll they replace *)
  val sheet = rule(sheet, ".caf.vertical,.caf.vertical-lr")
  val sheet = lay(sheet, Overflow(), "hidden")
  val sheet = lay(sheet, ColumnWidth(), "100vh")
  val sheet = lay(sheet, ColumnGap(), "calc(var(--page-top) + var(--page-bottom))")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf.vertical")
  val sheet = lay(sheet, WritingMode(), "vertical-rl")
  (* Latin and digits are turned, the default (text-orientation:mixed):
     JLREQ has an English word rotated 90 degrees and only a short number
     or acronym upright, which text-combine-upright:all gives a wrapped
     run (quire#391); upright on the page set every Latin word upright
     too, which no source supports *)
  val sheet = close(sheet)
  (* a run of one or two digits (reader.bats's _tcy_parts wraps it in a
     part of the class tcy), set upright in one cell *)
  val sheet = rule(sheet, ".caf.vertical .tcy,.caf.vertical-lr .tcy")
  (* written as it is: the property's name is longer than lay takes *)
  val () = raw(sheet, "text-combine-upright:all;")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf.vertical-lr")
  val sheet = lay(sheet, WritingMode(), "vertical-lr")
  val sheet = close(sheet)
  (* the lines are the column's height, and the margins' setting is not
     offered (the typography's paddings on the page's children): a
     block takes the page's width, and its lines its height *)
  val sheet = rule(sheet, ".caf.vertical>*,.caf.vertical-lr>*")
  val sheet = lay(sheet, MaxWidth(), "none")
  val sheet = lay(sheet, PaddingLeft(), "0")
  val sheet = lay(sheet, PaddingRight(), "0")
  val sheet = close(sheet)
  (* a fixed-layout page: the page is the whole reader view (the bars
     over it, as they are over a reflowed page), with no columns,
     scroll or paddings, and its box (reader.bats's page-box) centred
     in it, its own size scaled to fit (its inline style, ui_fixed_box_n,
     from _fixed_fit). Not restyled: these outrank the typography's .caf
     and .caf>* (style-type, settings.bats). What is outside the box is
     cut off, as EPUB RS 3.3 says, and its images fit it (the book's
     own CSS, which would size them, is not used) *)
  val sheet = rule(sheet, ".caf.fixed")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, JustifyContent(), "center")
  val sheet = lay(sheet, Padding(), "0")
  val sheet = lay(sheet, Overflow(), "hidden")
  val sheet = lay(sheet, ColumnWidth(), "auto")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf.fixed>*")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = lay(sheet, MaxWidth(), "none")
  val sheet = lay(sheet, Margin(), "0")
  val sheet = lay(sheet, Padding(), "0")
  val sheet = lay(sheet, Overflow(), "hidden")
  val sheet = lay(sheet, ContainerType(), "size")
  val sheet = close(sheet)
  (* a spread's facing page is shown, not marked: what is selected,
     highlighted or read aloud is the page's *)
  val sheet = rule(sheet, ".caf .facing")
  val sheet = lay(sheet, UserSelect(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf.fixed img")
  val sheet = lay(sheet, MaxWidth(), "100cqw")
  val sheet = lay(sheet, MaxHeight(), "100cqh")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".caf figure")
  val sheet = lay(sheet, Margin(), "1em auto")
  val sheet = close(sheet)
  (* an audio or video element, not played: a line says so before its
     fallback content (#424) *)
  val sheet = rule(sheet, ".caf .media-fallback::before")
  val () = raw(sheet, "content:\"Audio or video: Quire does not play it.\";display:block;font-style:italic;")
  val sheet = close(sheet)
  (* a note's text and a caption are set smaller than the text round them,
     and scale with it (#422) *)
  val sheet = rule(sheet, ".caf .note-text,.caf figcaption")
  val sheet = lay(sheet, FontSize(), ".875em")
  val sheet = close(sheet)
in sheet end

(* The marks and bottom bar, from .caf sup on *)
fn reader_rules_marks_and_bottom_bar {left:nat | left >= 1358} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1358] sheet(after, false, false) = let
  val sheet = rule(sheet, ".caf sup,.caf sub")
  val sheet = lay(sheet, LineHeight(), "0")
  val sheet = close(sheet)
  val sheet = rule(sheet, "::highlight(bats-mark-1)")
  val sheet = surf(S_fg_hl | sheet, RoleText(), RoleHighlight())
  val sheet = close(sheet)
  val sheet = rule(sheet, "::highlight(bats-mark-2)")
  val sheet = surf(S_markfg_mark | sheet, RoleMarkText(), RoleMark())
  val sheet = close(sheet)
  (* the orange highlight; and the underline, in the text's own colour
     (so its contrast is the text's), thick enough to tell from a link's *)
  val sheet = rule(sheet, "::highlight(bats-mark-3)")
  val sheet = surf(S_fg_hl2 | sheet, RoleText(), RoleSecondHighlight())
  val sheet = close(sheet)
  (* the sentence read aloud (read_aloud.bats) *)
  val sheet = rule(sheet, "::highlight(bats-mark-5)")
  val sheet = surf(S_markfg_mark | sheet, RoleMarkText(), RoleMark())
  val sheet = close(sheet)
  val sheet = rule(sheet, "::highlight(bats-mark-4)")
  val sheet = lay(sheet, TextDecoration(), "underline 3px")
  val sheet = close(sheet)
  (* the text a book's narration reads (narration.bats): the same proven
     pair as the sentence read aloud *)
  val sheet = rule(sheet, "::highlight(bats-mark-5)")
  val sheet = surf(S_markfg_mark | sheet, RoleMarkText(), RoleMark())
  val sheet = close(sheet)
  (* the narration's controls, in the bottom bar's row *)
  val sheet = rule(sheet, ".ngrp")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Gap(), "4px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".tools .nleave")
  val sheet = lay(sheet, Width(), "auto")
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = lay(sheet, Padding(), "0 8px")
  val sheet = close(sheet)
  (* the scrubber, between the page turns *)
  val sheet = rule(sheet, ".scr")
  val sheet = lay(sheet, Flex(), "1 1 0")
  val sheet = lay(sheet, MinWidth(), "0")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = lay(sheet, Padding(), "0 6px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".trk")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, Position(), "relative")
  val sheet = lay(sheet, Height(), "48px")
  val sheet = lay(sheet, Cursor(), "pointer")
  val sheet = lay(sheet, TouchAction(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".trk-l")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Left(), "0")
  val sheet = lay(sheet, Right(), "0")
  val sheet = lay(sheet, Top(), "20px")
  val sheet = lay(sheet, Height(), "4px")
  val sheet = tint(sheet, true, 30)
  val sheet = lay(sheet, BorderRadius(), "2px")
  val sheet = lay(sheet, PointerEvents(), "none")
  val sheet = close(sheet)
  (* a book read right to left: the bar follows (reader.bats'
     _direction_set, quire#359): the fill from the right, and the page
     turns on the other sides of the scrubber *)
  val sheet = rule(sheet, ".trk.rtl .trk-f")
  val sheet = lay(sheet, Left(), "auto")
  val sheet = lay(sheet, Right(), "0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".bot.rtl .pnext")
  val sheet = lay(sheet, Order(), "1")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".bot.rtl .scr")
  val sheet = lay(sheet, Order(), "2")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".bot.rtl .pprev")
  val sheet = lay(sheet, Order(), "3")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".bot.rtl .tools")
  val sheet = lay(sheet, Order(), "4")
  val sheet = close(sheet)
in sheet end

(* The scrubber, from .trk-f on *)
fn reader_rules_scrubber {left:nat | left >= 2218} (sheet: sheet(left, false, false)): [after:nat | after >= left - 2218] sheet(after, false, false) = let
  val sheet = rule(sheet, ".trk-f")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Left(), "0")
  val sheet = lay(sheet, Top(), "20px")
  val sheet = lay(sheet, Height(), "4px")
  val sheet = fill(sheet, RoleBarText())
  val sheet = lay(sheet, BorderRadius(), "2px")
  val sheet = lay(sheet, PointerEvents(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".tick")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Top(), "18px")
  val sheet = lay(sheet, Width(), "2px")
  val sheet = lay(sheet, Height(), "8px")
  val sheet = tint(sheet, true, 45)
  val sheet = lay(sheet, PointerEvents(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".thumb")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Top(), "10px")
  val sheet = lay(sheet, Width(), "24px")
  val sheet = lay(sheet, Height(), "24px")
  val sheet = lay(sheet, MarginLeft(), "-12px")
  val sheet = lay(sheet, BorderRadius(), "50%")
  val sheet = fill(sheet, RoleBarText())
  val sheet = lay(sheet, PointerEvents(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".tip")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Bottom(), "46px")
  val sheet = centre_x(sheet)
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = lay(sheet, Padding(), "2px 8px")
  val sheet = lay(sheet, BorderRadius(), "4px")
  val sheet = lay(sheet, FontSize(), "13px")
  val sheet = lay(sheet, WhiteSpace(), "nowrap")
  val sheet = lay(sheet, PointerEvents(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".pct")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = lay(sheet, WhiteSpace(), "nowrap")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".pback")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Left(), "max(12px,var(--safe-left))")
  val sheet = lay(sheet, Bottom(), "106px")
  val sheet = lay(sheet, ZIndex(), "4")
  val sheet = surf(S_accentfg_accent | sheet, RoleAccentText(), RoleAccent())
  val sheet = lay(sheet, BorderRadius(), "22px")
  val sheet = lay(sheet, Padding(), "8px 16px")
  val sheet = lay(sheet, BoxShadow(), "0 2px 8px rgba(0,0,0,.3)")
  val sheet = close(sheet)
  (* scrolled, on the chapter's last screen: at the right, apart from
     Back at the left *)
  (* the hint on turning pages, over the page's middle *)
  val sheet = rule(sheet, ".hint")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Left(), "max(16px,var(--safe-left))")
  val sheet = lay(sheet, Right(), "max(16px,var(--safe-right))")
  val sheet = lay(sheet, Top(), "45%")
  val sheet = lay(sheet, Width(), "fit-content")
  val sheet = lay(sheet, Margin(), "0 auto")
  val sheet = lay(sheet, ZIndex(), "4")
  val sheet = surf(S_accentfg_accent | sheet, RoleAccentText(), RoleAccent())
  val sheet = lay(sheet, BorderRadius(), "22px")
  val sheet = lay(sheet, Padding(), "10px 18px")
  val sheet = lay(sheet, BoxShadow(), "0 2px 8px rgba(0,0,0,.3)")
  val sheet = lay(sheet, PointerEvents(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".nextch")
  val sheet = lay(sheet, Left(), "auto")
  val sheet = lay(sheet, Right(), "max(12px,var(--safe-right))")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".seltb")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Left(), "50%")
  (* the top comes from the selection (ui_toolbar_at): above it, else
     below its end handle, kept in the window and the safe area *)
  val sheet = lay(sheet, Top(), "min(max(var(--seltb-top,40%),max(8px,var(--safe-top))),calc(100% - max(8px,var(--safe-bottom)) - var(--seltb-height,56px)))")
  val sheet = centre_x(sheet)
  val sheet = lay(sheet, ZIndex(), "5")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "4px")
  val sheet = surf(S_barfg_bar | sheet, RoleBarText(), RoleBar())
  val sheet = lay(sheet, BorderRadius(), "10px")
  val sheet = spaced(sheet, Padding(), SpaceSmall())
  val sheet = lay(sheet, BoxShadow(), "0 2px 8px rgba(0,0,0,.3)")
  (* no wider than the screen: its items go on a second row instead *)
  val sheet = lay(sheet, Width(), "max-content")
  val sheet = lay(sheet, MaxWidth(), "calc(100vw - 2*max(8px,var(--safe-left),var(--safe-right)))")
  val sheet = lay(sheet, FlexWrap(), "wrap")
  val sheet = lay(sheet, JustifyContent(), "center")
  val sheet = close(sheet)
in sheet end

(* The selection toolbar, from .seltb button on *)
fn reader_rules_selection_toolbar {left:nat | left >= 901} (sheet: sheet(left, false, false)): [after:nat | after >= left - 901] sheet(after, false, false) = let
  val sheet = rule(sheet, ".seltb button,.seltb a")
  val sheet = lay(sheet, Padding(), "8px 14px")
  val sheet = surf(S_barfg_bar | sheet, RoleBarText(), RoleBar())
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = lay(sheet, WhiteSpace(), "nowrap")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".seltb button:hover,.seltb a:hover")
  val sheet = surf(S_barfg_barhi | sheet, RoleBarText(), RoleBarHigh())
  val sheet = close(sheet)
  (* a probe as tall as the least distance the toolbar keeps from the
     window's top (the safe area), for the code to measure (quire#428) *)
  val sheet = rule(sheet, ".seltbfloor")
  val sheet = lay(sheet, Position(), "fixed")
  val sheet = lay(sheet, Top(), "0")
  val sheet = lay(sheet, Left(), "0")
  val sheet = lay(sheet, Width(), "0")
  val sheet = lay(sheet, Height(), "max(8px,var(--safe-top))")
  val sheet = lay(sheet, Visibility(), "hidden")
  val sheet = lay(sheet, PointerEvents(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".snavf")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Left(), "50%")
  val sheet = lay(sheet, Top(), "max(56px,calc(env(safe-area-inset-top) + 54px))")
  val sheet = centre_x(sheet)
  val sheet = lay(sheet, ZIndex(), "6")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "6px")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = surf(S_barfg_bar | sheet, RoleBarText(), RoleBar())
  val sheet = lay(sheet, BorderRadius(), "24px")
  val sheet = lay(sheet, Padding(), "2px 8px")
  val sheet = lay(sheet, BoxShadow(), "0 2px 8px rgba(0,0,0,.3)")
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".snavf span")
  val sheet = lay(sheet, WhiteSpace(), "nowrap")
  val sheet = lay(sheet, Padding(), "0 4px")
  val sheet = close(sheet)
in sheet end

implement reader_rules (sheet) = let
  val sheet = reader_rules_bars_and_title(sheet)
  val sheet = reader_rules_page_indicator_and_footer(sheet)
  val sheet = reader_rules_book_text(sheet)
  val sheet = reader_rules_vertical_fixed_and_notes(sheet)
  val sheet = reader_rules_marks_and_bottom_bar(sheet)
  val sheet = reader_rules_scrubber(sheet)
  val sheet = reader_rules_selection_toolbar(sheet)
in sheet end

end
