(* shell_rules -- the library's rules: the page, its bar and buttons, the
   shelves, the cards and the screens' common parts *)

#target wasm begin

#include "share/atspre_staload.hats"
staload "palette.sats"
staload "palette_proofs.sats"
staload "sheet.sats"
staload "declarations.sats"

#pub fn shell_rules {left:nat | left >= 8300} (sheet: sheet(left, false, false)): [after:nat | after >= left - 8300] sheet(after, false, false)

(* The library page, from body on *)
fn shell_rules_library_page {left:nat | left >= 1831} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1831] sheet(after, false, false) = let
  val sheet = rule(sheet, "body")
  val sheet = lay(sheet, Margin(), "0")
  val sheet = surf(S_fg_bg | sheet, RoleText(), RoleGround())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".app")
  val sheet = lay(sheet, MinHeight(), "100vh")
  val sheet = surf(S_fg_bg | sheet, RoleText(), RoleGround())
  val sheet = lay(sheet, FontFamily(), "Inter,system-ui,sans-serif")
  val sheet = lay(sheet, FontSize(), "16px")
  val sheet = lay(sheet, LineHeight(), "1.4")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".lib")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = lay(sheet, MaxWidth(), "800px")
  val sheet = lay(sheet, Margin(), "0 auto")
  val sheet = lay(sheet, Padding(), "max(12px,var(--safe-top)) max(16px,var(--safe-right)) max(24px,var(--safe-bottom)) max(16px,var(--safe-left))")
  val sheet = lay(sheet, BoxSizing(), "border-box")
  val sheet = lay(sheet, MinHeight(), "100vh")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".lib.drag")
  val sheet = lay(sheet, Outline(), "3px dashed var(--accent)")
  val sheet = lay(sheet, OutlineOffset(), "-8px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".bar")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexWrap(), "wrap")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = lay(sheet, Padding(), "8px 0")
  val sheet = line(sheet, BottomSide(), 1, RoleLine())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".ttl")
  val sheet = lay(sheet, FontFamily(), "Literata,Georgia,serif")
  val sheet = lay(sheet, FontWeight(), "bold")
  val sheet = lay(sheet, FontSize(), "22px")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, Margin(), "0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".btn")
  val sheet = lay(sheet, Display(), "inline-flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, JustifyContent(), "center")
  val sheet = lay(sheet, Padding(), "8px 14px")
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = line(sheet, AllSides(), 1, RoleLine())
  val sheet = lay(sheet, FontSize(), "15px")
  val sheet = lay(sheet, Position(), "relative")
  val sheet = lay(sheet, Overflow(), "hidden")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".btn-p")
  val sheet = surf(S_accentfg_accent | sheet, RoleAccentText(), RoleAccent())
  val sheet = line(sheet, AllSides(), 1, RoleAccent())
  val sheet = close(sheet)
  (* Import while the library cannot be read (its input is inert,
     #374): not the accent's call to act but the muted text on the card,
     a pair proven in every theme, with a cursor that says no (Material 3
     draws a disabled button with its container and text faded) *)
  val sheet = rule(sheet, "#import-button:has(input[inert]),#empty-import:has(input[inert])")
  val sheet = surf(S_muted_card | sheet, RoleMuted(), RoleCard())
  val sheet = lay(sheet, Cursor(), "not-allowed")
  val sheet = close(sheet)
  (* the bar's Import is an icon button (a plus) with the file input
     over it: a div, since a page cannot open the picker itself (#404) *)
  val sheet = rule(sheet, "#import-button")
  val sheet = lay(sheet, Display(), "inline-flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, JustifyContent(), "center")
  val sheet = lay(sheet, Position(), "relative")
  val sheet = lay(sheet, MinWidth(), "48px")
  val sheet = lay(sheet, MinHeight(), "48px")
  val sheet = lay(sheet, Cursor(), "pointer")
  val sheet = close(sheet)
  (* the empty library's message and what it offers, centred *)
  val sheet = rule(sheet, ".eacts")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexWrap(), "wrap")
  val sheet = lay(sheet, JustifyContent(), "center")
  val sheet = lay(sheet, Gap(), "12px")
  val sheet = lay(sheet, MarginTop(), "8px")
  val sheet = close(sheet)
in sheet end

(* The fields and banners, from .btn input[type=file] on *)
fn shell_rules_fields_and_banners {left:nat | left >= 1366} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1366] sheet(after, false, false) = let
  val sheet = rule(sheet, ".btn input[type=file],.ibtn input[type=file]")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Top(), "0")
  val sheet = lay(sheet, Left(), "0")
  val sheet = lay(sheet, Width(), "100%")
  val sheet = lay(sheet, Height(), "100%")
  val sheet = invisible(sheet)
  val sheet = lay(sheet, Cursor(), "pointer")
  val sheet = lay(sheet, FontSize(), "0")
  val sheet = close(sheet)
  (* every icon (ui.bats's CIcon marks it data-icon, whatever its
     class: .ibtn, .cmore) is a glyph of the icon face, in the control's
     own text colour (#295) *)
  val sheet = rule(sheet, "[data-icon]")
  val sheet = lay(sheet, FontFamily(), "'Material Symbols',Inter,system-ui,sans-serif")
  val sheet = close(sheet)
  (* an icon button; text it shows (Skip table) is in the app's face *)
  val sheet = rule(sheet, ".ibtn")
  val sheet = lay(sheet, FontSize(), "24px")
  val sheet = lay(sheet, LineHeight(), "1")
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = surf(S_fg_bg | sheet, RoleText(), RoleGround())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".sfield")
  val sheet = lay(sheet, FlexBasis(), "100%")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Gap(), "4px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".search")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, MinWidth(), "0")
  val sheet = lay(sheet, Padding(), "6px 10px")
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = close(sheet)
  (* the error banner: at the top of the screen, over the library and
     the reader (and over the overlays and toasts) until dismissed *)
  val sheet = rule(sheet, ".banner")
  val sheet = lay(sheet, Position(), "fixed")
  val sheet = lay(sheet, Top(), "max(8px,var(--safe-top))")
  val sheet = lay(sheet, Left(), "50%")
  val sheet = centre_x(sheet)
  val sheet = lay(sheet, ZIndex(), "22")
  val sheet = lay(sheet, Width(), "calc(100% - 2*max(16px,var(--safe-left),var(--safe-right)))")
  val sheet = lay(sheet, MaxWidth(), "640px")
  val sheet = lay(sheet, BoxSizing(), "border-box")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = lay(sheet, FlexWrap(), "wrap")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Padding(), "10px 12px")
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = lay(sheet, BoxShadow(), "0 2px 12px rgba(0,0,0,.35)")
  val sheet = surf(S_bannerfg_banner | sheet, RoleBannerText(), RoleBanner())
  val sheet = close(sheet)
  (* over the library the banner is part of the page, above the header,
     and pushes it down (#374): Material 3 puts a banner under the top app
     bar and moves the content, so nothing is under it. A fixed banner at
     the top hid the title, Import and the menu; one at the foot hid Try
     again on a short phone, because the library's own height is not
     known to it (the app bar wraps to five rows at 320px). The base
     rule's left 50% and translateX(-50%) still centre it when it is
     relative instead of fixed. Over the reader it stays fixed at the
     top while the bars are away (the reader's own bars hide) *)
  val sheet = rule(sheet, ".banner.in-library")
  val sheet = lay(sheet, Position(), "relative")
  val sheet = lay(sheet, Top(), "auto")
  val sheet = lay(sheet, Margin(), "8px 0 0")
  val sheet = close(sheet)
  (* While the reader's bars are up the banner sits under the top bar
     (#374): the bar is the top app bar, and Material 3 puts a banner
     under it (material.io's banners, Flutter's MaterialBanner, Zebra's
     Zeta banner all sit under the app bar; none draws over it); the bar is its safe inset (at least 2px),
     a 44px control and 2px below, and the banner 8px under it. The
     bottom bar is at the other edge, out of its way *)
  val sheet = rule(sheet, ".banner.under-bars")
  val sheet = lay(sheet, Top(), "calc(max(2px,var(--safe-top)) + 54px)")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".banner .ibtn")
  val sheet = surf(S_bannerfg_banner | sheet, RoleBannerText(), RoleBanner())
  val sheet = close(sheet)
in sheet end

(* The import and book lists, from .banner span on *)
fn shell_rules_import_and_book_lists {left:nat | left >= 1354} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1354] sheet(after, false, false) = let
  (* the message takes the row and the buttons wrap under it on a narrow
     window, rather than Report being squeezed until its text is cut *)
  val sheet = rule(sheet, ".banner span")
  val sheet = lay(sheet, Flex(), "1 1 12em")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".imp")
  val sheet = lay(sheet, Margin(), "8px 0")
  val sheet = lay(sheet, Padding(), "10px 12px")
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = line(sheet, AllSides(), 1, RoleLine())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".imp-n")
  val sheet = lay(sheet, FontWeight(), "bold")
  val sheet = lay(sheet, Overflow(), "hidden")
  val sheet = lay(sheet, TextOverflow(), "ellipsis")
  val sheet = lay(sheet, WhiteSpace(), "nowrap")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".imp-s")
  val sheet = surf(S_muted_card | sheet, RoleMuted(), RoleCard())
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".imp-bar")
  val sheet = lay(sheet, Height(), "6px")
  val sheet = fill(sheet, RoleLine())
  val sheet = lay(sheet, BorderRadius(), "3px")
  val sheet = lay(sheet, MarginTop(), "6px")
  val sheet = lay(sheet, Overflow(), "hidden")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".imp-fill")
  val sheet = lay(sheet, Height(), "100%")
  val sheet = fill(sheet, RoleAccent())
  val sheet = lay(sheet, Width(), "0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".list")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = close(sheet)
  (* the library's view controls: which books, list or grid *)
  val sheet = rule(sheet, ".lview")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexWrap(), "wrap")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = lay(sheet, Margin(), "8px 0")
  val sheet = close(sheet)
  (* which books takes its labels' width: when it and List and Grid do
     not fit one line (320 px, #265), List and Grid go to the next *)
  val sheet = rule(sheet, ".lview>.seg")
  val sheet = lay(sheet, Flex(), "1 1 auto")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".seg.vseg")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = close(sheet)
  (* reading aloud, sharing and the screen's controls are shown only
     where the platform has them: by their elements' data-hide
     (read_aloud.bats, sharing.bats, screen_controls.bats) *)
  val sheet = rule(sheet, ".ssel")
  val sheet = lay(sheet, Font(), "inherit")
  val sheet = lay(sheet, Padding(), "6px")
  val sheet = lay(sheet, BorderRadius(), "6px")
  val sheet = lay(sheet, MaxWidth(), "12em")
  val sheet = close(sheet)
  (* the hint for iOS Safari, shown (on) only there (library.bats);
     Install Quire and the storage notes are shown by their elements'
     data-hide (platform.bats) *)
  val sheet = rule(sheet, ".ihint")
  val sheet = lay(sheet, Display(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".ihint.on")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "12px")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Padding(), "12px")
  val sheet = lay(sheet, Margin(), "8px 0")
  val sheet = lay(sheet, BorderRadius(), "8px")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = close(sheet)
  (* the collections, a row of their own under the view's controls *)
  val sheet = rule(sheet, ".crow")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, FlexWrap(), "wrap")
  val sheet = lay(sheet, Gap(), "6px")
  val sheet = lay(sheet, Flex(), "1 1 100%")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = close(sheet)
in sheet end

(* The book cards, from .conth on *)
fn shell_rules_book_cards {left:nat | left >= 1479} (sheet: sheet(left, false, false)): [after:nat | after >= left - 1479] sheet(after, false, false) = let
  val sheet = rule(sheet, ".conth")
  val sheet = lay(sheet, FontWeight(), "600")
  val sheet = lay(sheet, MarginTop(), "8px")
  val sheet = close(sheet)
  (* a grid of covers, the title and progress under each *)
  val sheet = rule(sheet, ".list.grid")
  val sheet = lay(sheet, Display(), "grid")
  (* no rows given, the columns as many as fit *)
  val sheet = lay(sheet, GridTemplate(), "none/repeat(auto-fill,minmax(150px,1fr))")
  val sheet = lay(sheet, Gap(), "12px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".grid .cardrow")
  val sheet = lay(sheet, Position(), "relative")
  val sheet = lay(sheet, Margin(), "0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".grid .card")
  val sheet = lay(sheet, FlexDirection(), "column")
  val sheet = lay(sheet, AlignItems(), "stretch")
  val sheet = lay(sheet, TextAlign(), "center")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".grid .cov")
  val sheet = lay(sheet, Width(), "100%")
  val sheet = lay(sheet, Height(), "auto")
  val sheet = lay(sheet, AspectRatio(), "2/3")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".grid .cmore")
  val sheet = lay(sheet, Position(), "absolute")
  val sheet = lay(sheet, Top(), "6px")
  val sheet = lay(sheet, Right(), "6px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".grid .pbar")
  val sheet = lay(sheet, MaxWidth(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".grid .prog")
  val sheet = lay(sheet, JustifyContent(), "center")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".cardrow")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "stretch")
  val sheet = lay(sheet, Gap(), "6px")
  val sheet = lay(sheet, Margin(), "6px 0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".card")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, MinWidth(), "0")
  val sheet = lay(sheet, TextAlign(), "left")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, Gap(), "12px")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Padding(), "10px")
  val sheet = line(sheet, AllSides(), 1, RoleLine())
  val sheet = lay(sheet, BorderRadius(), "8px")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = lay(sheet, Cursor(), "pointer")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".card *")
  val sheet = lay(sheet, PointerEvents(), "none")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".cmore")
  val sheet = lay(sheet, FontSize(), "22px")
  val sheet = lay(sheet, BorderRadius(), "8px")
  val sheet = surf(S_fg_card | sheet, RoleText(), RoleCard())
  val sheet = line(sheet, AllSides(), 1, RoleLine())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".cov")
  val sheet = lay(sheet, Width(), "48px")
  val sheet = lay(sheet, Height(), "72px")
  val sheet = lay(sheet, ObjectFit(), "cover")
  val sheet = lay(sheet, BorderRadius(), "3px")
  val sheet = lay(sheet, Flex(), "none")
  val sheet = fill(sheet, RoleLine())
  val sheet = close(sheet)
  val sheet = rule(sheet, ".cinfo")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, MinWidth(), "0")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".bt")
  val sheet = lay(sheet, FontWeight(), "bold")
  val sheet = lay(sheet, FontSize(), "16px")
  val sheet = lay(sheet, Overflow(), "hidden")
  val sheet = lay(sheet, TextOverflow(), "ellipsis")
  val sheet = close(sheet)
in sheet end

(* The progress and empty state, from .ba on *)
fn shell_rules_progress_and_empty_state {left:nat | left >= 824} (sheet: sheet(left, false, false)): [after:nat | after >= left - 824] sheet(after, false, false) = let
  val sheet = rule(sheet, ".ba")
  val sheet = surf(S_muted_card | sheet, RoleMuted(), RoleCard())
  val sheet = lay(sheet, FontSize(), "14px")
  val sheet = close(sheet)
  (* a book's series and number *)
  val sheet = rule(sheet, ".bser")
  val sheet = surf(S_muted_card | sheet, RoleMuted(), RoleCard())
  val sheet = lay(sheet, FontSize(), "13px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".prog")
  val sheet = lay(sheet, Display(), "flex")
  val sheet = lay(sheet, AlignItems(), "center")
  val sheet = lay(sheet, Gap(), "8px")
  val sheet = surf(S_muted_card | sheet, RoleMuted(), RoleCard())
  val sheet = lay(sheet, FontSize(), "13px")
  val sheet = lay(sheet, MarginTop(), "4px")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".pbar")
  val sheet = lay(sheet, Flex(), "1")
  val sheet = lay(sheet, MaxWidth(), "160px")
  val sheet = lay(sheet, Height(), "5px")
  val sheet = fill(sheet, RoleLine())
  val sheet = lay(sheet, BorderRadius(), "3px")
  val sheet = lay(sheet, Overflow(), "hidden")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".pfill")
  val sheet = lay(sheet, Height(), "100%")
  val sheet = fill(sheet, RoleAccent())
  val sheet = close(sheet)
  val sheet = rule(sheet, "#library-try-again")
  val sheet = lay(sheet, AlignSelf(), "center")
  val sheet = close(sheet)
  val sheet = rule(sheet, ".empty")
  val sheet = lay(sheet, TextAlign(), "center")
  val sheet = surf(S_muted_bg | sheet, RoleMuted(), RoleGround())
  val sheet = lay(sheet, Padding(), "16px")
  val sheet = lay(sheet, MarginTop(), "15vh")
  val sheet = lay(sheet, FontSize(), "18px")
  val sheet = lay(sheet, FontStyle(), "italic")
  val sheet = close(sheet)
in sheet end

implement shell_rules (sheet) = let
  val sheet = shell_rules_library_page(sheet)
  val sheet = shell_rules_fields_and_banners(sheet)
  val sheet = shell_rules_import_and_book_lists(sheet)
  val sheet = shell_rules_book_cards(sheet)
  val sheet = shell_rules_progress_and_empty_state(sheet)
in sheet end

end
